- Plugin/UtilityPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
- Projects/Features/ArtistFeature/Sources/ArtistMusicViewController.swift
- Projects/Features/PlayerFeature/Sources/NewPlayerViewController.swift
- Projects/Features/SearchFeature/Resources/EntireSectionHeader.xib
- Projects/Features/SearchFeature/Resources/RecentRecordHeaderView.xib
- Projects/Features/SearchFeature/Resources/Search.storyboard
- Projects/Features/SearchFeature/Sources/AfterSearchContentViewController.swift
- Projects/Features/SearchFeature/Sources/AfterSearchViewController.swift
- Projects/Features/SearchFeature/Sources/BeforeSearchContentViewController.swift
- Projects/Features/SearchFeature/Sources/BeforeSearchContentViewModel.swift
- Projects/Features/SearchFeature/Sources/EntireSectionHeader.swift
- Projects/Features/SearchFeature/Sources/RecentRecordHeaderView.swift
- Projects/Features/SearchFeature/Sources/RecentRecordTableViewCell.swift
- Projects/Features/SearchFeature/Sources/SearchViewController.swift
- Projects/Modules/FeatureThirdPartyLib/Project.swift
- Projects/Modules/Utility/Sources/Protocols/ContainerViewType.swift
- Projects/UsertInterfaces/DesignSystem/Resources/SongList/SongListCell.xib
- Projects/UsertInterfaces/DesignSystem/Sources/SongList/SongListCell.swift
- Tuist/Dependencies.swift
https://user-images.githubusercontent.com/48616183/212471195-7036a227-6630-4922-b15e-abfff253cb7f.mp4
> :twisted_rightwards_arrows: 검색 후 화면 밑 기능 개발

- Projects/Features/MainTabFeature/Sources/MainContainerViewController.swift
🔀  :: 탭바 컨트롤러 > 오토레이아웃 대응
Closes #19
> 🔀  :: 탭바 컨트롤러 > 오토레이아웃 대응

- Projects/Features/ArtistFeature/Sources/ArtistMusicContentViewController.swift
- Projects/Features/ArtistFeature/Sources/ArtistMusicViewController.swift
- Projects/Features/ArtistFeature/Sources/ArtistViewController.swift
- Projects/Features/HomeFeature/Sources/HomeViewController.swift
- Projects/Features/MainTabFeature/Resources/Main.storyboard
- Projects/Features/MainTabFeature/Sources/BottomTabBarViewController.swift
- Projects/Features/MainTabFeature/Sources/MainContainerViewController.swift
- Projects/Features/MainTabFeature/Sources/MainTabBarViewController.swift
- Projects/Modules/Utility/Sources/Protocols/ContainerViewType.swift
Modal을 제외한 화면 이동 시(Push) 탭바가 살아있도록 변경
> 🔀  :: Modal을 제외한 화면 이동 시(Push) 탭바가 살아있도록 변경

- Plugin/UtilityPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
- Projects/Features/PlayerFeature/Sources/ViewControllers/PlayerViewController.swift
- Projects/Modules/FeatureThirdPartyLib/Project.swift
- Tuist/Dependencies.swift
YoutubePlayerKit 라이브러리 때문에 빌드가 안되던 문제를 해결합니다.
tuist config 에서 YoutubePlayerKit 제거
> 🔀 :: YoutubePlayerKit 라이브러리를 제거합니다.

- Projects/Features/ArtistFeature/Resources/Artist.storyboard
- Projects/Features/ArtistFeature/Sources/ArtistDetailViewController.swift
- Projects/Features/ArtistFeature/Sources/ArtistMusicViewController.swift
- Projects/Features/ArtistFeature/Sources/ArtistViewController.swift
- Projects/Features/BaseFeature/Sources/BaseViewController.swift
- Projects/Features/SearchFeature/Resources/Search.storyboard
- Projects/Features/SearchFeature/Sources/AfterSearchContentViewController.swift
- Projects/Features/SearchFeature/Sources/AfterSearchViewController.swift
- Projects/Features/SearchFeature/Sources/BeforeSearchContentViewController.swift
- Projects/Features/SearchFeature/Sources/EntireSectionHeader.swift
- Projects/Features/SearchFeature/Sources/RecentRecordHeaderView.swift
- Projects/Features/SearchFeature/Sources/SearchViewController.swift
- Projects/Features/StorageFeature/Resources/Storage.storyboard
- Projects/Features/StorageFeature/Sources/AfterLoginStorageViewController.swift
- Projects/Features/StorageFeature/Sources/FavoriteViewController.swift
- Projects/Features/StorageFeature/Sources/MyPlayListViewController.swift
- Projects/Features/StorageFeature/Sources/QnaContentViewController.swift
- Projects/Features/StorageFeature/Sources/StorageViewController.swift
- Projects/Modules/Utility/Sources/Extensions/Extension+PreferenceManager.swift
- Projects/Modules/Utility/Sources/Extensions/Extension+UIView.swift
- Projects/Modules/Utility/Sources/Extensions/Extension+UIViewController.swift
- Projects/Modules/Utility/Sources/Manager/PreferenceManager.swift
- Projects/UsertInterfaces/DesignSystem/Sources/CommonUI/PlayListDetailViewController.swift
> 🔀:: 코드 최적화

- Projects/Features/StorageFeature/Resources/Storage.storyboard
보관함 로그인 후 탭바 라인 짤리는 문제 수정
Closes #38
> 🔀 :: 보관함 로그인 후 탭바 라인 짤리는 문제 수정

- Projects/Features/SearchFeature/Sources/BeforeSearchContentViewController.swift
- Projects/Features/SearchFeature/Sources/RecentRecordHeaderView.swift
- Projects/Features/SearchFeature/Sources/SearchViewController.swift
- Projects/Features/StorageFeature/Sources/FavoriteViewController.swift
- Projects/Features/StorageFeature/Sources/MyPlayListViewController.swift
- Projects/UsertInterfaces/DesignSystem/Sources/CommonUI/PlayListControlPopupViewController.swift
- Projects/UsertInterfaces/DesignSystem/Sources/CommonUI/PlayListDetailViewController.swift
- Projects/UsertInterfaces/DesignSystem/Sources/CommonUI/ProfilePopViewController.swift
1. 검색화면 키보드라 인한 애니메이션 버그 
2. 롱탭으로 편집 모드 진입(플레이리스트Detail,보관함)
3. 토스트 팝업 테스트
4. 공유 모달 읽기 전용변환
Closes #40 #41
> 🔀  네트워크 작업전 검색화면, 보관함 버그 및 회의에 나오는 새 기능 적용

- Plugin/UtilityPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
- Projects/App/Sources/Application/AppDelegate.swift
- Projects/App/Support/Info.plist
- Projects/Features/StorageFeature/Sources/BeforeLoginStorageViewController.swift
- Projects/Features/StorageFeature/Sources/StorageViewController.swift
- Projects/Modules/FeatureThirdPartyLib/Project.swift
- Projects/UsertInterfaces/DesignSystem/Sources/CommonUI/TextPopupViewController.swift
- Tuist/Dependencies.swift
> :twisted_rightwards_arrows: 네이버 로그인 기본 작업을 완료했습니다.

- Projects/App/Sources/Application/AppComponent+Artist.swift
- Projects/App/Sources/Application/NeedleGenerated.swift
- Projects/Features/ArtistFeature/Resources/Artist.storyboard
- Projects/Features/ArtistFeature/Sources/Components/ArtistDetailComponent.swift
- Projects/Features/ArtistFeature/Sources/Components/ArtistMusicComponent.swift
- Projects/Features/ArtistFeature/Sources/Components/ArtistMusicContentComponent.swift
- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistDetailHeaderViewController.swift
- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistDetailViewController.swift
- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicViewController.swift
- Projects/Features/ArtistFeature/Sources/ViewModels/ArtistMusicContentViewModel.swift
- Projects/Features/ArtistFeature/Sources/Views/ArtistListCell.swift
- Projects/Features/ArtistFeature/Sources/Views/ArtistMusicCell.swift
- Projects/Modules/Utility/Sources/Extensions/Extension+Int.swift
- Projects/Modules/Utility/Sources/Extensions/Extension+String.swift
- Projects/Services/APIKit/Sources/API/ArtistAPI.swift
- Projects/Services/DataMappingModule/Sources/Artist/Response/ArtistSongListResponseDTO.swift
- Projects/Services/DataMappingModule/Sources/Base/ArtistType.swift
- Projects/Services/DataModule/Sources/Artist/Repositories/ArtistRepositoryImpl.swift
- Projects/Services/DataModule/Sources/Artist/UseCases/FetchArtistSongListUseCaseImpl.swift
- Projects/Services/DomainModule/Sources/Artist/Entity/ArtistSongListEntity.swift
- Projects/Services/DomainModule/Sources/Artist/Repository/ArtistRepository.swift
- Projects/Services/DomainModule/Sources/Artist/UseCases/FetchArtistSongListUseCase.swift
- Projects/Services/NetworkModule/Sources/Artist/DataTransfer/FetchArtistSongListTransfer.swift
- Projects/Services/NetworkModule/Sources/Artist/Remote/RemoteArtistDataSource.swift
- Projects/Services/NetworkModule/Sources/Artist/Remote/RemoteArtistDataSourceImpl.swift
아티스트 상세 네트워크 연동
1. 아티스트 노래 목록 가져오기 및 페이징 처리
2. 그라데이션 구현 
3. DI 적용
미작업 현황: 중첩 스크롤링
> 🔀 :: 아티스트 상세 구현 

- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistDetailHeaderViewController.swift
- Projects/Features/MainTabFeature/Resources/TabItemView.xib
- Projects/Modules/Utility/Sources/Extensions/Extension+String.swift
> 🔀 :: 메인 탭바 UI 구성요소 간격 수정

- Projects/App/Sources/Application/AppComponent+Songs.swift
- Projects/App/Sources/Application/NeedleGenerated.swift
- Projects/Features/CommonFeature/Sources/Views/PlayButtonGroupView.swift
- Projects/Features/CommonFeature/Sources/Views/SongListCell.swift
- Projects/Features/SearchFeature/Resources/RecentRecordHeaderView.xib
- Projects/Features/SearchFeature/Sources/Components/AfterSearchComponent.swift
- Projects/Features/SearchFeature/Sources/Components/AfterSearchContentComponent.swift
- Projects/Features/SearchFeature/Sources/Components/SearchComponent.swift
- Projects/Features/SearchFeature/Sources/Enum/Enum+Search .swift
- Projects/Features/SearchFeature/Sources/View/EntireSectionHeader.swift
- Projects/Features/SearchFeature/Sources/View/RecentRecordTableViewCell.swift
- Projects/Features/SearchFeature/Sources/ViewControllers/AfterSearchContentViewController.swift
- Projects/Features/SearchFeature/Sources/ViewControllers/AfterSearchViewController.swift
- Projects/Features/SearchFeature/Sources/ViewControllers/BeforeSearchContentViewController.swift
- Projects/Features/SearchFeature/Sources/ViewControllers/SearchViewController.swift
- Projects/Features/SearchFeature/Sources/ViewModels/AfterSearchContentViewModel.swift
- Projects/Features/SearchFeature/Sources/ViewModels/AfterSearchViewModel.swift
- Projects/Features/StorageFeature/Sources/Views/MyPlayListHeaderView.swift
> :twisted_rightwards_arrows:  검색 후 화면 네트워크 처리 

- Projects/App/Sources/Application/AppComponent+User.swift
- Projects/App/Sources/Application/NeedleGenerated.swift
- Projects/Features/CommonFeature/Sources/Components/ProfilePopComponent.swift
- Projects/Services/APIKit/Sources/API/AuthAPI.swift
- Projects/Services/APIKit/Sources/API/UserAPI.swift
- Projects/Services/DataMappingModule/Sources/User/Response/FavoriteSongsResponseDTO.swift
- Projects/Services/DataMappingModule/Sources/User/Response/SubPlayListResponseDTO.swift
- Projects/Services/DataModule/Sources/User/Repositories/UserRepositoryImpl.swift
- Projects/Services/DataModule/Sources/User/UseCases/FetchFavoriteSongsUseCaseImpl.swift
- Projects/Services/DataModule/Sources/User/UseCases/FetchSubPlayListUseCaseImpl.swift
- Projects/Services/DataModule/Sources/User/UseCases/SetProfileUseCaseImpl.swift
- Projects/Services/DataModule/Sources/User/UseCases/SetUserNameUseCaseImpl.swift
- Projects/Services/DomainModule/Sources/User/Entity/FavoriteSongEntity.swift
- Projects/Services/DomainModule/Sources/User/Entity/SubPlayListEntity.swift
- Projects/Services/DomainModule/Sources/User/Repository/UserRepository.swift
- Projects/Services/DomainModule/Sources/User/UseCases/FetchFavoriteSongsUseCase.swift
- Projects/Services/DomainModule/Sources/User/UseCases/FetchSubPlayListUseCase.swift
- Projects/Services/DomainModule/Sources/User/UseCases/SetProfileUseCase.swift
- Projects/Services/DomainModule/Sources/User/UseCases/SetUserNameUseCase.swift
- Projects/Services/NetworkModule/Sources/User/DataTransfer/FetchFavoriteSongTransfer.swift
- Projects/Services/NetworkModule/Sources/User/DataTransfer/FetchSubPlayListTransfer.swift
- Projects/Services/NetworkModule/Sources/User/Remote/RemoteUserDataSource.swift
- Projects/Services/NetworkModule/Sources/User/Remote/RemoteUserDataSourceImpl.swift
엔드포인트 user에 관한 모든 유저케이스를 구현 했습니다.
- 1.프로필 설정
- 2. 닉네임 설정
- 3. 구독중인 플리목록
- 4. 좋아요 누른 곡 노래 목록
컴포넌트 및 뷰모델까지 구현은 못했습니다.
또한 닉네임설정 뷰컨은 다용도 (플리생성,이름생성 등) 
다양한 기능을 하나의 뷰컨으로 사용하기때문에 컴포넌트 생성 시 고민이 필요..
> :twisted_rightwards_arrows: 유저 API 유즈케이스 구현

- Projects/Services/APIKit/Sources/API/AuthAPI.swift
- Projects/Services/APIKit/Sources/API/PlayListAPI.swift
> 🔀 플레이리스트  모든 API 정의 

- Projects/App/Sources/Application/NeedleGenerated.swift
- Projects/Features/CommonFeature/Sources/Components/ProfilePopComponent.swift
- Projects/Features/CommonFeature/Sources/ViewModels/ProfilePopViewModel.swift
- Projects/Features/StorageFeature/Resources/Storage.storyboard
- Projects/Features/StorageFeature/Sources/ViewControllers/AfterLoginViewController.swift
- Projects/Features/StorageFeature/Sources/ViewControllers/StorageViewController.swift
- Projects/Features/StorageFeature/Sources/ViewModels/AfterLoginStorageViewModel.swift
로그인 후 > 최초 접속 시는 서버 데이터와 유저정보 동기화 하도록 변경
> 🔀 :: 로그인 후 > 최초 접속 시는 서버 데이터와 유저정보 동기화

- Projects/App/Sources/Application/AppComponent+User.swift
- Projects/App/Sources/Application/NeedleGenerated.swift
- Projects/Features/CommonFeature/Resources/CommonUI.storyboard
- Projects/Features/CommonFeature/Sources/Components/ProfilePopComponent.swift
- Projects/Features/CommonFeature/Sources/ViewControllers/ProfilePopViewController.swift
- Projects/Features/CommonFeature/Sources/ViewModels/ProfilePopViewModel.swift
- Projects/Features/CommonFeature/Sources/Views/ProfileCollectionViewCell.swift
- Projects/Services/APIKit/Sources/API/UserAPI.swift
- Projects/Services/DataMappingModule/Sources/User/Response/FetchProfileListResponseDTO.swift
- Projects/Services/DataModule/Sources/User/Repositories/UserRepositoryImpl.swift
- Projects/Services/DataModule/Sources/User/UseCases/FetchProfileListUseCaseImpl.swift
- Projects/Services/DomainModule/Sources/User/Entity/ProfileListEntity.swift
- Projects/Services/DomainModule/Sources/User/Repository/UserRepository.swift
- Projects/Services/DomainModule/Sources/User/UseCases/FetchProfileListUseCase.swift
- Projects/Services/NetworkModule/Sources/User/DataTransfer/FetchProfileListTransfer.swift
- Projects/Services/NetworkModule/Sources/User/Remote/RemoteUserDataSource.swift
- Projects/Services/NetworkModule/Sources/User/Remote/RemoteUserDataSourceImpl.swift
🔀 :: 프로필 리스트 api 연동
Closes #86
> 🔀 :: 프로필 리스트 api 연동

- Projects/App/Sources/Application/AppComponent+Like.swift
- Projects/App/Sources/Application/NeedleGenerated.swift
- Projects/Services/APIKit/Sources/API/LikeAPI.swift
- Projects/Services/DataModule/Sources/Like/Repositories/LikeRepositoryImpl.swift
- Projects/Services/DataModule/Sources/Like/UseCases/AddLikeSongUseCaseImpl.swift
- Projects/Services/DataModule/Sources/Like/UseCases/CancelLikeSongUseCaseImpl.swift
- Projects/Services/DataModule/Sources/Like/UseCases/FetchLikeNumOfSongUseCaseImpl.swift
- Projects/Services/DomainModule/Sources/Like/Repository/LikeRepository.swift
- Projects/Services/DomainModule/Sources/Like/UseCases/AddLikeSongUseCase.swift
- Projects/Services/DomainModule/Sources/Like/UseCases/CancelLikeSongUseCase.swift
- Projects/Services/DomainModule/Sources/Like/UseCases/FetchLikeNumOfSongUseCase.swift
- Projects/Services/NetworkModule/Sources/Like/Remote/RemoteLikeDataSource.swift
- Projects/Services/NetworkModule/Sources/Like/Remote/RemoteLikeDataSourceImpl.swift
> 🔀  좋아요 API  컴포넌트 제외 구현완료

- Projects/Features/CommonFeature/Resources/CommonUI.storyboard
- Projects/Features/CommonFeature/Sources/ViewModels/ProfilePopViewModel.swift
- Projects/Features/StorageFeature/Resources/Storage.storyboard
- Projects/Features/StorageFeature/Sources/ViewModels/AfterLoginStorageViewModel.swift
🔀:: 앱 삭제 > 재설치 후 접속 시 서버 데이터 동기화 로직 수정
앱 삭제 후 재설치해도 키체인이 남아있어서 접속 후 회원 정보 API가 요청되는 로직에서 요청하지 않도록 수정 
> 즉, 앱 삭제 하면 비로그인 상태. 회원정보를 요청할 필요가 없음. 다시 로그인 하는 것이 맞음.
> 🔀:: 앱 삭제 > 재설치 후 접속 시 서버 데이터 동기화 로직 수정

- Projects/Features/CommonFeature/Sources/ViewControllers/ProfilePopViewController.swift
- Projects/Features/CommonFeature/Sources/ViewModels/ProfilePopViewModel.swift
- Projects/Features/StorageFeature/Sources/ViewControllers/RequestViewController.swift
- Projects/Features/StorageFeature/Sources/ViewModels/RequestViewModel.swift
- Projects/Services/DomainModule/Sources/Base/BaseEntity.swift
- Projects/Services/NetworkModule/Sources/Base/BaseRemoteDataSource.swift
> 🔀 :: 프로필 변경, 회원탈퇴 에러 핸들링

- .package.resolved
- Plugin/UtilityPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
- Projects/Modules/FeatureThirdPartyLib/Project.swift
- Projects/Modules/ThirdPartyLib/Project.swift
- Tuist/Dependencies.swift
NativeSPM을 사용해 YouTubePlayerKit, GoogleSignin 사용되게 변경하였습니다.
기존 익스터널로 가지고 오는 spm은 resource 파일을 제대로 인식하지 못하는 문제가 발생하였기 때문에 그런 것들을 가리지 않는 native spm으로 변경하였습니다.
Closes #97
> 🔀 :: Native SPM으로 라이브러리 비정상 작동 해결

- Plugin/UtilityPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
- Projects/Features/PlayerFeature/Sources/PlayState.swift
- Projects/Features/PlayerFeature/Sources/ViewControllers/PlayerViewController.swift
- Projects/Features/PlayerFeature/Sources/ViewModels/PlayerViewModel.swift
- Projects/Features/PlayerFeature/Sources/Views/MiniPlayerView.swift
- Projects/Features/PlayerFeature/Sources/Views/PlayerView.swift
- Projects/Modules/FeatureThirdPartyLib/Project.swift
- Tuist/Dependencies.swift
유튜브킷에서 유튜브플레이어킷으로 전환하였습니다.
유튜브플레이어킷과의 연동을 위해 rx 에서 combine 으로 90% 전환하였습니다.
- 유튜브킷 -> 유튜브플레이어킷으로 전환
- 바인딩: 썸네일 및 블러배경, 미니플레이어 재생바
- 이미지 비율 수정: 서버로부터 받는 이미지 비율이 16:9가 아니므로 scaleAspectFill 로 변경
> 🔀 :: YoutubePlayerKit 으로 변경 및 컴바인 작업

- Projects/Features/PlayerFeature/Sources/ViewControllers/PlayerViewController.swift
- Projects/Features/PlayerFeature/Sources/ViewModels/PlayerViewModel.swift
- Projects/Features/PlayerFeature/Sources/Views/LyricsTabelViewCell.swift
- Projects/Features/PlayerFeature/Sources/Views/PlayerView.swift
- Projects/Services/DataMappingModule/Sources/Songs/Response/LyricsResponseDTO.swift
- Projects/Services/DomainModule/Sources/Songs/Entity/LyricsEntity.swift
- 재생중인 곡이 변경되면 해당 곡의 가사를 불러옵니다.
- 현재 재생중인 부분의 가사를 트래킹합니다.
- 스크롤하여 재생하고싶은 부분의 가사를 화면 가운데로 옮기면 해당 부분의 가사부터 재생됩니다.
https://user-images.githubusercontent.com/60254939/221400945-147afb80-fcc3-4843-919e-447ab0457940.mp4
> 🔀 가사 관련 기능들을 구현합니다.

- Projects/Features/CommonFeature/Resources/CommonUI.storyboard
- Projects/Features/CommonFeature/Sources/ViewControllers/MultiPurposePopupViewController.swift
- Projects/Features/CommonFeature/Sources/ViewModels/MultiPurposePopupViewModel.swift
> 🔀 :: 멀티purpose indicator 추가

- Projects/App/Sources/Application/AppComponent+Playlist.swift
- Projects/App/Sources/Application/NeedleGenerated.swift
- Projects/Features/CommonFeature/Resources/CommonUI.storyboard
- Projects/Features/CommonFeature/Resources/ContainPlayListHeaderView/ContainPlayListHeaderView.xib
- Projects/Features/CommonFeature/Resources/PlayButtonGroup/PlayButtonGroupView.xib
- Projects/Features/CommonFeature/Sources/Components/ContainSongsComponent.swift
- Projects/Features/CommonFeature/Sources/Components/MultiPurposePopComponent.swift
- Projects/Features/CommonFeature/Sources/ViewControllers/ContainSongsViewController.swift
- Projects/Features/CommonFeature/Sources/ViewControllers/MultiPurposePopupViewController.swift
- Projects/Features/CommonFeature/Sources/ViewModels/ContainSongsViewModel.swift
- Projects/Features/CommonFeature/Sources/ViewModels/MultiPurposePopupViewModel.swift
- Projects/Features/CommonFeature/Sources/Views/ContainPlayListHeaderView.swift
- Projects/Features/CommonFeature/Sources/Views/CurrentPlayListTableViewCell.swift
- Projects/Features/CommonFeature/Sources/Views/PlayButtonGroupView.swift
- Projects/Features/CommonFeature/Sources/Views/PlayListTableViewCell.swift
- Projects/Features/SignInFeature/Resources/SignIn.storyboard
- Projects/Features/SignInFeature/Sources/ViewControllers/LoginViewController.swift
- Projects/Features/StorageFeature/Resources/MyPlayListHeader.xib
- Projects/Features/StorageFeature/Resources/Storage.storyboard
- Projects/Features/StorageFeature/Sources/Components/RequestComponent.swift
- Projects/Features/StorageFeature/Sources/ViewControllers/BugReportViewController.swift
- Projects/Features/StorageFeature/Sources/ViewControllers/RequestViewController.swift
- Projects/Features/StorageFeature/Sources/ViewModels/BugReportViewModel.swift
- Projects/Features/StorageFeature/Sources/Views/MyPlayListHeaderView.swift
- Projects/Services/DataMappingModule/Sources/Playlist/Response/PlayListBaseResponseDTO.swift
- Projects/Services/DomainModule/Sources/Playlist/Entity/PlayListBaseEntity.swift
- Projects/Services/NetworkModule/Sources/Playlist/DataTransfer/PlayListBaseTransfer.swift
- 곡 담을 때 플레이리스트와 연결해 줄 호면이 필요하여 구현했습니다. 
- UI작업
- 플레이리스트 정보가져오기 UseCase 적용
- 헤더 버튼 눌를 때 플레이리스트 생성 팝업 
- 담아올 곡 바인딩 및 갯수
- 플리 생성 후 바로 곡 담는 기술 구현
- 곡 담는 UseCase 생성
Closes #이슈번호
> 🔀 플레이리스트 담기 화면  UI 구현 

- Projects/Features/ArtistFeature/Resources/Artist.storyboard
- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistDetailHeaderViewController.swift
- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
- Projects/Features/ArtistFeature/Sources/ViewModels/ArtistMusicContentViewModel.swift
- Projects/Features/ArtistFeature/Sources/ViewModels/ArtistViewModel.swift
- Projects/Features/ArtistFeature/Sources/Views/ArtistListCell.swift
- Projects/Features/SearchFeature/Resources/Search.storyboard
- Projects/Features/SearchFeature/Sources/ViewControllers/SearchViewController.swift
- Projects/Services/DataMappingModule/Sources/Artist/Response/ArtistListResponseDTO.swift
- Projects/Services/DomainModule/Sources/Artist/Entity/ArtistListEntity.swift
- Projects/Services/NetworkModule/Sources/Artist/DataTransfer/FetchArtistListTransfer.swift
> 🔀 :: 아티스트 상세 헤더 UI Fix

- Projects/App/Sources/Application/NeedleGenerated.swift
- Projects/Features/CommonFeature/Sources/ViewControllers/PlayListDetailViewController.swift
- Projects/Features/PlayerFeature/Sources/Components/PlayerComponent.swift
- Projects/Features/PlayerFeature/Sources/ViewControllers/PlayerViewController.swift
- Projects/Features/PlayerFeature/Sources/ViewModels/PlayerViewModel.swift
- Projects/Features/PlayerFeature/Sources/ViewModels/PlaylistViewModel.swift
- Projects/Features/PlayerFeature/Sources/Views/LikeButton.swift
- Projects/Features/PlayerFeature/Sources/Views/PlayerView.swift
- Projects/Features/StorageFeature/Sources/ViewControllers/FavoriteViewController.swift
- Projects/Features/StorageFeature/Sources/ViewControllers/MyPlayListViewController.swift
- 햅틱매니저로 변경
- 썸네일 가져오기 유틸리티 모듈에 있는 메소드로 변경
- 좋아요 수 연동
> 🔀 :: 플레이어 메소드 수정 및 좋아요 수 API 연동

- Projects/Features/CommonFeature/Resources/CommonUI.storyboard
- Projects/Features/CommonFeature/Sources/ViewControllers/PlayListDetailViewController.swift
- Projects/Features/CommonFeature/Sources/ViewModels/PlayListDetailViewModel.swift
- Projects/Features/CommonFeature/Sources/Views/PlayListTableViewCell.swift
- Projects/Features/MainTabFeature/Sources/ViewControllers/MainContainerViewController.swift
- Projects/Features/MainTabFeature/Sources/Views/TabItemView.swift
플레이리스트 상세 > 편집모드 드래그 앤 드랍 애니메이션 수정
브런치 네임이 이상한 점은 양해좀..
Closes #이슈번호
> 🔀 :: 플레이리스트 상세 > 편집모드 드래그 앤 드랍 애니메이션 수정

- Projects/Features/CommonFeature/Sources/ViewControllers/PlayListDetailViewController.swift
- Projects/Features/StorageFeature/Resources/Storage.storyboard
- Projects/Features/StorageFeature/Sources/ViewControllers/FavoriteViewController.swift
- Projects/Features/StorageFeature/Sources/ViewControllers/MyPlayListViewController.swift
- Projects/Features/StorageFeature/Sources/ViewModels/FavoriteViewModel.swift
- Projects/Features/StorageFeature/Sources/ViewModels/MyPlayListViewModel.swift
- Projects/Features/StorageFeature/Sources/Views/FavoriteTableViewCell.swift
- Projects/Features/StorageFeature/Sources/Views/MyPlayListTableViewCell.swift
- 적용된 드래그앤 드랍 , 에니메이션 및 효과가 우리 앱과 다르게 때문에 플로 형식을 이용
- 플레이어 플레이리스트쪽을 이용
- 플레이리스트 디테일 swipe 닫기 적용
Closes #112
> 🔀  드래그앤 드롭 에니메이션 변경

- Projects/App/Sources/Application/AppComponent+Playlist.swift
- Projects/App/Sources/Application/NeedleGenerated.swift
- Projects/Features/ArtistFeature/Sources/ViewModels/ArtistMusicContentViewModel.swift
- Projects/Features/CommonFeature/.swiftlint.yml
- Projects/Features/CommonFeature/Resources/CommonUI.storyboard
- Projects/Features/CommonFeature/Resources/SongList/SongListCell.xib
- Projects/Features/CommonFeature/Sources/Components/PlayListDetailComponent.swift
- Projects/Features/CommonFeature/Sources/ViewControllers/MultiPurposePopupViewController.swift
- Projects/Features/CommonFeature/Sources/ViewControllers/PlayListDetailViewController.swift
- Projects/Features/CommonFeature/Sources/ViewModels/MultiPurposePopupViewModel.swift
- Projects/Features/CommonFeature/Sources/ViewModels/PlayListDetailViewModel.swift
- Projects/Features/CommonFeature/Sources/Views/PlayListTableViewCell.swift
- Projects/Features/CommonFeature/Sources/Views/SongListCell.swift
- Projects/Modules/Utility/Sources/Protocols/PlayButtonDelegate.swift
- Projects/Services/APIKit/Sources/API/PlayListAPI.swift
- Projects/Services/DataModule/Sources/Playlist/Repositories/PlaylistRepositoryImpl.swift
- Projects/Services/DataModule/Sources/Playlist/UseCases/RemoveSongsUseCaseImpl.swift
- Projects/Services/DomainModule/Sources/Playlist/Repository/PlayListRepository.swift
- Projects/Services/DomainModule/Sources/Playlist/UseCases/RemoveSongsUseCase.swift
- Projects/Services/DomainModule/Sources/Songs/Entity/SongEntity.swift
- Projects/Services/NetworkModule/Sources/Playlist/Remote/RemotePlayListDataSource.swift
- Projects/Services/NetworkModule/Sources/Playlist/Remote/RemotePlayListDataSourceImpl.swift
- SongCart를 이용한 몇가지 처리를 완료 했습니다.
- 곡 삭제 및 재생목록 담기 제외 , 전체 선택 및 곡 담기 구현
- 마지막 연속된 선택된 셀 서로 교체 시  버그 
- MVVM 비지니스 모델 분리
- play 버튼 delgate
- 공유하기 확인 시 내려가기
- 왁뮤 추천플리 하단 앱바 오류(커스텀 플리 하단바 뜸)
https://user-images.githubusercontent.com/48616183/227093197-3b45855b-272b-45d0-bbd5-d65545c97b81.mp4
https://user-images.githubusercontent.com/48616183/227093213-d33103bb-fc2d-4e57-b579-0bae12c2a8a0.mp4
왁뮤 추천 리스트 
Closes #143
> 🔀 플레이 리스트 디테일 창 Selected 및 Moved 구현

- Projects/App/Sources/Application/NeedleGenerated.swift
- Projects/Features/PlayerFeature/Sources/Components/PlaylistComponent.swift
- Projects/Features/PlayerFeature/Sources/PlayState+Public.swift
- Projects/Features/PlayerFeature/Sources/ViewControllers/PlayerViewController.swift
- Projects/Features/PlayerFeature/Sources/ViewControllers/PlaylistViewController.swift
각종 화면에서 다양한 버튼을 통해 곡을 재생하도록 해야했습니다.
PlayState 에 곡을 재생하는 Public 메소드를 추가합니다.
> 현재 플레이어 구조 및 곡 재생 가이드
https://www.notion.so/waktaverse/3fb99225e7bb45de9f12d84afd0e3e66?pvs=4
> 🔀 :: 플레이어에서 곡을 재생하도록 하는 메소드를 추가합니다. 

- Projects/Features/PlayerFeature/Sources/PlayState+Public.swift
loadAndAppendUniqueSongs() forEach 문 내에 self.load(at: song) 삭제
> 🔀 :: loadAndAppendUniqueSongs 메소드에서 첫번째곡만 load되도록 변경

- Projects/App/Sources/Application/NeedleGenerated.swift
- Projects/Features/ChartFeature/Sources/Components/ChartComponent.swift
- Projects/Features/ChartFeature/Sources/Components/ChartContentComponent.swift
- Projects/Features/ChartFeature/Sources/ViewContrillers/ChartContentViewController.swift
- Projects/Features/ChartFeature/Sources/ViewContrillers/ChartViewController.swift
- Projects/Features/ChartFeature/Sources/ViewModels/ChartContentViewModel.swift
- Projects/Features/ChartFeature/Sources/ViewModels/ChartViewModel.swift
- Projects/Features/ChartFeature/Sources/Views/ChartContentTableViewCell.swift
- Projects/Features/HomeFeature/Sources/ViewModels/HomeViewModel.swift
- Projects/Features/HomeFeature/Sources/Views/HomeChartCell.swift
- Projects/Features/SearchFeature/Resources/EntireSectionHeader.xib
- Projects/Modules/Utility/Sources/Extensions/Extension+Notification.Name.swift
- Projects/Services/DataModule/Sources/Chart/Repositories/ChartRepositoryImpl.swift
- Projects/Services/DataModule/Sources/Chart/UseCases/FetchChartRankingUseCaseImpl.swift
- Projects/Services/DomainModule/Sources/Chart/Entity/ChartRankingEntity.swift
- Projects/Services/DomainModule/Sources/Chart/Repository/ChartRepository.swift
- Projects/Services/DomainModule/Sources/Chart/UseCases/FetchChartRankingUseCase.swift
- Projects/Services/NetworkModule/Sources/Chart/Remote/RemoteChartDataSource.swift
- Projects/Services/NetworkModule/Sources/Chart/Remote/RemoteChartDataSourceImpl.swift
> 🔀 :: 차트 각 탭마다 하단 뷰 적용 및 기능 구현

- Projects/Features/PlayerFeature/Sources/PlayState+Public.swift
- loadAndAppendUniqueSong, loadAndAppendUniqueSongs 메소드를 하나로 통합합니다.
```Swift
// 통합 전
func loadAndAppendUniqueSong(_ song: SongEntity)
func loadAndAppendUniqueSongs(_ songs: [SongEntity])
// 통합 후
func loadAndAppendSongsToPlaylist(_ songs: [SongEntity], duplicateAllowed: Bool = false)
```
- 재생목록에 추가 메소드를 추가합니다.
```Swift
func appendSongsToPlaylist(_ songs: [SongEntity], duplicateAllowed: Bool = false)
```
> 🔀 :: PlayState 퍼블릭 메소드 리팩토링

- Projects/Features/CommonFeature/Sources/ViewControllers/PlayListDetailViewController.swift
- Projects/Features/CommonFeature/Sources/ViewModels/PlayListDetailViewModel.swift
- Projects/Features/CommonFeature/Sources/Views/PlayListTableViewCell.swift
- Projects/Features/StorageFeature/Sources/ViewControllers/FavoriteViewController.swift
- Projects/Features/StorageFeature/Sources/ViewControllers/MyPlayListViewController.swift
- Projects/Features/StorageFeature/Sources/ViewModels/MyPlayListViewModel.swift
- Projects/Features/StorageFeature/Sources/Views/FavoriteTableViewCell.swift
- Projects/Features/StorageFeature/Sources/Views/MyPlayListTableViewCell.swift
-  플리 디테일 재생 버튼
-  나만의 플레이리스트 재생 버튼
-  좋아요곡 플레이리스트 버튼
-  플리 디테일 전체 재생 및 랜덤 재생 
Closes #172
> 🔀 :: 홈을 제외한 플레이버튼 모든 구현 적용

- Projects/Features/ArtistFeature/.swiftlint.yml
- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
- Projects/Features/ArtistFeature/Sources/ViewModels/ArtistMusicContentViewModel.swift
1. 아티스트 재생목록추가, 재생 구현 
2. 페이징 처리에 따른 전체선택 버튼 활성화 처리 
Closes #165
> 🔀 :: 아티스트 곡 편집 팝업 작업

- Projects/Features/ArtistFeature/Resources/Artist.storyboard
- Projects/Features/ArtistFeature/Resources/ArtistPlayButtonGroupView.xib
- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistDetailViewController.swift
- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicViewController.swift
- Projects/Features/ArtistFeature/Sources/Views/ArtistPlayButtonGroupView.swift
> 🔀 아티스트 상세 > 헤더 축소/확장 스크롤링 적용

- Projects/App/Sources/Application/AppComponent+User.swift
- Projects/App/Sources/Application/NeedleGenerated.swift
- Projects/Features/StorageFeature/Sources/Components/FavoriteComponent.swift
- Projects/Features/StorageFeature/Sources/ViewControllers/FavoriteViewController.swift
- Projects/Features/StorageFeature/Sources/ViewControllers/MyPlayListViewController.swift
- Projects/Features/StorageFeature/Sources/ViewModels/FavoriteViewModel.swift
- Projects/Features/StorageFeature/Sources/ViewModels/MyPlayListViewModel.swift
- Projects/Services/APIKit/Sources/API/UserAPI.swift
- Projects/Services/DataModule/Sources/User/Repositories/UserRepositoryImpl.swift
- Projects/Services/DataModule/Sources/User/UseCases/DeleteFavoriteListUseCaseImpl.swift
- Projects/Services/DomainModule/Sources/User/Repository/UserRepository.swift
- Projects/Services/DomainModule/Sources/User/UseCases/DeleteFavoriteListUseCase.swift
- Projects/Services/NetworkModule/Sources/User/Remote/RemoteUserDataSource.swift
- Projects/Services/NetworkModule/Sources/User/Remote/RemoteUserDataSourceImpl.swift
> 🔀 좋아요 리스트 삭제 기능 구현

- Projects/Features/PlayerFeature/Sources/ViewControllers/PlaylistViewController.swift
- Projects/Features/PlayerFeature/Sources/Views/MiniPlayerView.swift
- Projects/Features/PlayerFeature/Sources/Views/PlayerView.swift
- Projects/Features/PlayerFeature/Sources/Views/PlaylistView.swift
- Projects/Modules/Utility/Sources/Extensions/Extension+UIColor.swift
- 미니플레이어에 투명도 및 블러효과를 추가합니다.
Closes #188 
https://user-images.githubusercontent.com/60254939/229692935-6dbc0325-e5eb-40ac-b07a-b66d9bc35a77.mp4
> 🔀  :: 미니플레이어 투명도 및 블러 효과 추가

- Projects/Features/CommonFeature/Resources/CommonUI.storyboard
- Projects/Features/CommonFeature/Sources/ViewControllers/ContractViewController.swift
- Projects/Features/CommonFeature/Sources/ViewControllers/PlayListDetailViewController.swift
- Projects/Features/HomeFeature/Resources/Home.storyboard
- Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
- Projects/Features/StorageFeature/Resources/Storage.storyboard
- Projects/Features/StorageFeature/Sources/ViewControllers/FavoriteViewController.swift
- Projects/Features/StorageFeature/Sources/ViewControllers/MyPlayListViewController.swift
- Projects/Features/StorageFeature/Sources/ViewControllers/QnaViewController.swift
- Projects/Features/StorageFeature/Sources/ViewControllers/RequestViewController.swift
- Projects/Features/StorageFeature/Sources/ViewModels/QnaViewModel.swift
- Projects/Modules/Utility/Sources/Extensions/Extension+UIActivityIndicatorView.swift
> 🔀 :: 검색 제외한 모든 화면 로딩 인디케이터 적용

- Projects/Features/SearchFeature/Resources/Search.storyboard
- Projects/Features/SearchFeature/Sources/ViewControllers/AfterSearchContentViewController.swift
- Projects/Features/SearchFeature/Sources/ViewControllers/AfterSearchViewController.swift
- Projects/Features/SearchFeature/Sources/ViewControllers/BeforeSearchContentViewController.swift
- 데이토 로딩 처리 필요 (스켈레톤x) 
- 비포 서치
- 애프터 서치
https://user-images.githubusercontent.com/48616183/229697167-46e295e6-3fcf-46e2-9ebc-0904ab4952c6.mp4
https://user-images.githubusercontent.com/48616183/229697196-3654c96b-4437-4720-9478-b0343ee7ed82.mp4
Closes #189
> 🔀 서치 관련 인디케이터 적용

- Projects/Features/HomeFeature/Resources/Home.storyboard
- Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
- Projects/Features/SignInFeature/Sources/ViewModels/LoginViewModel.swift
- Projects/Features/StorageFeature/Resources/Storage.storyboard
- Projects/Features/StorageFeature/Sources/ViewControllers/NoticeDetailViewController.swift
- Projects/Features/StorageFeature/Sources/ViewControllers/NoticeViewController.swift
- Projects/Services/APIKit/Sources/API/SuggestAPI.swift
- Projects/Services/APIKit/Sources/API/WMAPI.swift
- Projects/Services/DataMappingModule/Sources/Base/SuggestType.swift
홈 블러, Suggest API, Provider Google로 박제된 것 수정
Closes #199
별로 차이는 없는것 같지만..일단 올림
> 🔀 :: 홈 블러, Suggest API, Provider Google로 박제된 것 수정

- Projects/Features/ChartFeature/Sources/Views/PlayButtonForChartView.swift
- Projects/Features/SignInFeature/Sources/ViewModels/LoginViewModel.swift
애플로그인시 구글로그인으로 가는 문제 수정했습니다
차트 뷰컨에서 전체재생 랜덤재생 아이콘 바뀌여 있는거 수정했습니다
> 🔀 :: 애플로그인시 구글로그인으로 가는 문제 수정 + 차트 버그 수정

- Plugin/UtilityPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
- Projects/Features/PlayerFeature/Sources/Views/MiniPlayerView.swift
- Projects/Features/PlayerFeature/Sources/Views/PlayerView.swift
- Projects/Modules/FeatureThirdPartyLib/Project.swift
- Projects/Modules/ThirdPartyLib/Project.swift
- Tuist/Dependencies.swift
> 🔀 :: 플레이어 > 흐르는 레이블 적용

- .package.resolved
- Plugin/UtilityPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
- Projects/App/Project.swift
- Projects/App/Resources/GoogleService-Info.plist
- Projects/App/Sources/Application/AppDelegate.swift
- Projects/App/Support/Info.plist
- Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
- Projects/Modules/FeatureThirdPartyLib/Project.swift
- Projects/Modules/ThirdPartyLib/Project.swift
- Projects/Services/DataMappingModule/Sources/Notice/Response/FetchNoticeResponseDTO.swift
- Scripts/FirebaseCrashlyticsScript.sh
- Tuist/Dependencies.swift
- Tuist/ProjectDescriptionHelpers/Action+Template.swift
- Tuist/ProjectDescriptionHelpers/Environment.swift
Firebase Analytics, Crashlytics 셋업
빌드에는 전혀 문제가 없으나 dsym 경로 설정에 문제가 있는건지, 디버그모드라 동작을 안하는건지 
테스트를 좀 더 해봐야 합니다.
> 🔀 Firebase Analytics, Crashlytics 셋업

- .gitignore
- Projects/App/Project.swift
- Projects/App/Sources/Application/AppDelegate.swift
- Projects/App/Sources/Application/SceneDelegate.swift
- Projects/App/Support/Info.plist
- Projects/Modules/Utility/Sources/GoogleOAuth/GoogleLoginManager.swift
- Projects/Modules/Utility/Sources/Utils/Secrets.swift
- Projects/Modules/Utility/Sources/Utils/Utils.swift
api 키 숨기기 with xcconfig
1. secrets.xcconfig 파일은 gitignore에 등록되었으므로, 수동으로 해당 경로에 넣어줍시다. 
2. Tuist 설정에 의해 해당 파일은 Configurations으로 돌아가게 됩니다. 
3. Configurations 활용으로 Info.plist에 환경변수로 적용합니다. 
4. Utility/Project/Sources/Utils.Secrets.swift 파일에 정의된 함수로 불러와 각 코드에 적용하게됩니다.
Closes #167
> 🔀 :: api 키 숨기기 with xcconfig

- Projects/App/Project.swift
- Projects/App/Sources/Application/AppDelegate.swift
- Projects/Features/ArtistFeature/Project.swift
- Projects/Features/BaseFeature/Project.swift
- Projects/Features/ChartFeature/Project.swift
- Projects/Features/CommonFeature/Project.swift
- Projects/Features/CommonFeature/Resources/SongList/SongListCell.xib
- Projects/Features/HomeFeature/Project.swift
- Projects/Features/MainTabFeature/Project.swift
- Projects/Features/PlayerFeature/Project.swift
- Projects/Features/RootFeature/Project.swift
- Projects/Features/SearchFeature/Project.swift
- Projects/Features/SignInFeature/Project.swift
- Projects/Features/StorageFeature/Project.swift
- Projects/Modules/Utility/Project.swift
- Projects/Modules/Utility/Sources/Realm/RealmManager.swift
- Projects/Modules/Utility/Sources/Realm/RealmModel.swift
- Projects/Services/APIKit/Project.swift
- Projects/Services/DataModule/Project.swift
- Projects/Services/DatabaseModule/Project.swift
- Projects/Services/DomainModule/Project.swift
- Projects/Services/NetworkModule/Project.swift
Realm Manager 구현
https://www.notion.so/waktaverse/Realm-DataBase-4db06122f4374fb486b4830d329d3cba
Closes #154
> 🔀 :: Realm Manager 구현

- Projects/Features/PlayerFeature/Sources/ViewControllers/PlaylistViewController.swift
> 🔀 :: 현재재생목록이 빈 경우 문구 추가

- Projects/Features/PlayerFeature/Sources/ViewControllers/PlayerViewController.swift
- Projects/Features/PlayerFeature/Sources/ViewControllers/PlaylistViewController.swift
- Projects/Features/PlayerFeature/Sources/ViewModels/PlayerViewModel+API.swift
- Projects/Features/PlayerFeature/Sources/ViewModels/PlayerViewModel.swift
- Projects/Features/PlayerFeature/Sources/ViewModels/PlaylistViewModel.swift
플레이어모듈에 남아있던 print() -> DEBUG_LOG()로 대체
Closes #216
> 🔀 :: 플레이어 모듈 print -> DEBUG_LOG 로 대체

- Projects/Features/CommonFeature/Sources/Views/NoticeCollectionViewCell.swift
- Projects/Features/StorageFeature/Resources/Storage.storyboard
- Projects/Features/StorageFeature/Sources/ViewControllers/NoticeDetailViewController.swift
- Projects/Features/StorageFeature/Sources/ViewModels/NoticeDetailViewModel.swift
공지사항 상세 > 원본 이미지 비율대로 나오게 하기 
Closes #221
> 🔀 :: 공지사항 상세 > 원본 이미지 비율대로 나오게 하기

- Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
추천 플레이리스트 갯수 변경되었을때 높이 값 반영이 안됨
이슈 픽스
Closes #230
> 🔀 :: Issue #230

- Projects/App/Sources/Application/SceneDelegate.swift
- Projects/Features/CommonFeature/Sources/PlayState/PlayState+Playlist.swift
- Projects/Features/CommonFeature/Sources/PlayState/PlayState.swift
- Projects/Features/PlayerFeature/Sources/ViewControllers/PlaylistViewController.swift
- Projects/Modules/Utility/Sources/Realm/RealmModel.swift
재생중인 곡이 변경되면, PlayListItem.isPlaying 까지 Realm 에 저장되도록 구현
현재재생목록이 비었을 경우, 편집버튼 hidden 처리
> 🔀 :: 마지막으로 재생했던 곡 기억 기능

- Projects/Features/PlayerFeature/Sources/ViewControllers/PlayerViewController.swift
- Projects/Features/PlayerFeature/Sources/ViewModels/PlayerViewModel+API.swift
- Projects/Features/PlayerFeature/Sources/Views/LyricsTabelViewCell.swift
- Projects/Features/PlayerFeature/Sources/Views/PlayerView.swift
- 글자 높이를 계산하여 24를 넘는 높이를 동적으로 변하게 처리하여 줄 수를 늘려줌
- 셀 오토레이아웃 변경
Closes #241
> 🔀 :: 가사 짤림 해결 

- Projects/Features/StorageFeature/Sources/ViewControllers/BugReportViewController.swift
- Projects/Features/StorageFeature/Sources/ViewControllers/QuestionViewController.swift
- Projects/Features/StorageFeature/Sources/Views/BugReportCollectionViewCell.swift
- Projects/Modules/Utility/Sources/Extensions/Extension+Data.swift
- Projects/Modules/Utility/Sources/Utils/TemporaryMediaFile.swift
동영상 썸네일 추출
버그제보 동영상 첨부 시 썸네일을 추출 할 수 없었던 문제를 해결하였습니다. 
Closes #이슈번호
> 🔀 :: 버그 제보 > 동영상 썸네일 추출

- Projects/Features/CommonFeature/Sources/ViewControllers/PlayListDetailViewController.swift
- Projects/Features/CommonFeature/Sources/ViewModels/PlayListDetailViewModel.swift
🔀 :: 왁뮤 추천 플리 클릭 시 송카트 안나옴 버그 해결
> 🔀 :: 왁뮤 추천 플리 클릭 시 송카트 안나옴 버그 해결

- Projects/Features/CommonFeature/Sources/ViewModels/PlayListDetailViewModel.swift
- Projects/Features/CommonFeature/Sources/Views/RecommendPlayListCell.swift
- Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
- Projects/Features/SearchFeature/Sources/ViewControllers/BeforeSearchContentViewController.swift
- Projects/Features/StorageFeature/Sources/ViewModels/MyPlayListViewModel.swift
- Projects/Services/DataMappingModule/Sources/Chart/Response/FetchChartRankingResponseDTO.swift
- Projects/Services/DataMappingModule/Sources/Like/Response/LikeResponseDTO.swift
- Projects/Services/DataMappingModule/Sources/Playlist/Response/AddSongResponseDTO.swift
- Projects/Services/DataMappingModule/Sources/Playlist/Response/PlayListDetailResponseDTO.swift
- Projects/Services/DataMappingModule/Sources/Playlist/Response/RecommendPlayListResponseDTO.swift
- Projects/Services/DataMappingModule/Sources/Songs/Response/SongResponseDTO.swift
- Projects/Services/DataMappingModule/Sources/User/Response/FavoriteSongsResponseDTO.swift
- Projects/Services/DataMappingModule/Sources/User/Response/PlayListResponseDTO.swift
- Projects/Services/DomainModule/Sources/Playlist/Entity/PlayListDetailEntity.swift
- Projects/Services/DomainModule/Sources/Playlist/Entity/RecommendPlayListEntity.swift
- Projects/Services/DomainModule/Sources/User/Entity/FavoriteSongEntity.swift
- Projects/Services/DomainModule/Sources/User/Entity/PlayListEntity.swift
- Projects/Services/NetworkModule/Sources/Chart/DataTransfer/FetchChartRankingTransfer.swift
- Projects/Services/NetworkModule/Sources/Like/DataTransfer/FetchLikeTransfer.swift
- Projects/Services/NetworkModule/Sources/Playlist/DataTransfer/AddSongTransfer.swift
- Projects/Services/NetworkModule/Sources/Playlist/DataTransfer/FetchPlayListDetailResponseDTO.swift
- Projects/Services/NetworkModule/Sources/Playlist/DataTransfer/FetchRecommendPlayListTransfer.swift
- Projects/Services/NetworkModule/Sources/Songs/DataTransfer/FetchSearchSongTransfer.swift
- Projects/Services/NetworkModule/Sources/User/DataTransfer/FetchFavoriteSongTransfer.swift
- Projects/Services/NetworkModule/Sources/User/DataTransfer/FetchPlayListTransfer.swift
> 🔀 :: 서버 이전으로 인한 Api response 변경

- Projects/Features/CommonFeature/Sources/PlayState/PlayState.swift
출력장치가 변경됨을 감지해 이어폰이 연결해제 되면 self.pause()를 요청합니다.
테스트 결과 실패확률이 높지만 없는 것보단 좋다고 판단해 해당 기능을 추가합니다.
Closes #248
> 🔀 :: 이어폰 빼면 일시정지되는 기능 추가

- Projects/Features/ChartFeature/Sources/ViewContrillers/ChartContentViewController.swift
- Projects/Features/ChartFeature/Sources/ViewModels/ChartContentViewModel.swift
- Projects/Features/ChartFeature/Sources/Views/ChartContentTableViewCell.swift
- Projects/Services/DataMappingModule/Sources/Chart/Response/FetchChartRankingResponseDTO.swift
- Projects/Services/DomainModule/Sources/Chart/Entity/ChartRankingEntity.swift
- Projects/Services/NetworkModule/Sources/Chart/DataTransfer/FetchChartRankingTransfer.swift
누적순이 아닐 때에도 조회수를 보여주는 부분 수정
Closes #이슈번호
> 🔀  :: 누적순이 아닐 때에도 조회수를 보여주는 부분 수정

- .github/DISCUSSION_TEMPLATE/bug-beta.yml
- .github/DISCUSSION_TEMPLATE/bug.yml
> 🔀 :: bug 탬플릿 추가

- .github/DISCUSSION_TEMPLATE/버그 제보 (Beta Only).yml
- .github/DISCUSSION_TEMPLATE/버그 제보.yml
> 🔀 :: bug 탬플릿 코드 오류 해결

- Projects/App/Sources/Application/AppComponent+App.swift
- Projects/App/Sources/Application/NeedleGenerated.swift
- Projects/App/Support/Info.plist
- Projects/Features/CommonFeature/Sources/ViewControllers/TextPopupViewController.swift
- Projects/Features/RootFeature/.swiftlint.yml
- Projects/Features/RootFeature/Sources/Components/RootComponent.swift
- Projects/Features/RootFeature/Sources/ViewControllers/IntroViewController.swift
- Projects/Features/RootFeature/Sources/ViewModels/IntroViewModel.swift
- Projects/Services/APIKit/Sources/API/AppAPI.swift
- Projects/Services/APIKit/Sources/API/WMAPI.swift
- Projects/Services/APIKit/Sources/Secrets/SecretURL.swift
- Projects/Services/DataMappingModule/Sources/App/Response/AppInfoDTO.swift
- Projects/Services/DataMappingModule/Sources/App/Response/CheckVersionResponseDTO.swift
- Projects/Services/DataModule/Sources/App/Repositories/AppRepositoryImpl.swift
- Projects/Services/DataModule/Sources/App/UseCases/FetchCheckVersionUseCaseImpl.swift
- Projects/Services/DomainModule/Sources/App/Entity/AppInfoEntity.swift
- Projects/Services/DomainModule/Sources/App/Entity/VersionCheckEntity.swift
- Projects/Services/DomainModule/Sources/App/Repository/AppRepository.swift
- Projects/Services/DomainModule/Sources/App/UseCases/FetchCheckAppUseCase.swift
- Projects/Services/DomainModule/Sources/App/UseCases/FetchCheckVersionUseCase.swift
- Projects/Services/NetworkModule/Sources/App/DataTransfer/FetchCheckVersionTransfer.swift
- Projects/Services/NetworkModule/Sources/App/Remote/RemoteAppDataSource.swift
- Projects/Services/NetworkModule/Sources/App/Remote/RemoteAppDataSourceImpl.swift
> 🔀 :: 버전체킹 및 강제 업데이트 기능 구현

- Projects/App/Sources/Application/NeedleGenerated.swift
- Projects/Features/CommonFeature/Sources/ViewControllers/NoticePopupViewController.swift
- Projects/Features/MainTabFeature/.swiftlint.yml
- Projects/Features/MainTabFeature/Sources/Components/MainTabBarComponent.swift
- Projects/Features/MainTabFeature/Sources/ViewControllers/MainTabBarViewController.swift
- Projects/Features/SignInFeature/Resources/SignIn.storyboard
- Projects/Features/SignInFeature/Sources/ViewControllers/LoginViewController.swift
- Projects/Features/SignInFeature/Sources/Views/LoginUIExtension.swift
- Projects/Features/StorageFeature/Sources/ViewControllers/NoticeDetailViewController.swift
✨ ::  QA 대응
1. 공지 팝업 클릭 > 공지 상세로 이동 
2. 로그인 전 화면 > 이용약관, 개인정보처리방침, 버전 정보 삭제 
3. 공지 상세 이미지 좌우 여백 제거
Closes #이슈번호
> 🔀 ::  QA 대응

- Projects/Features/CommonFeature/Sources/ViewControllers/ContainSongsViewController.swift
- Projects/Features/CommonFeature/Sources/ViewControllers/MultiPurposePopupViewController.swift
- Projects/Features/CommonFeature/Sources/ViewControllers/PlayListDetailViewController.swift
- Projects/Features/CommonFeature/Sources/ViewControllers/ProfilePopViewController.swift
- Projects/Features/CommonFeature/Sources/ViewModels/ContainSongsViewModel.swift
- Projects/Features/CommonFeature/Sources/ViewModels/MultiPurposePopupViewModel.swift
- Projects/Features/CommonFeature/Sources/ViewModels/PlayListDetailViewModel.swift
- Projects/Features/CommonFeature/Sources/ViewModels/ProfilePopViewModel.swift
- Projects/Features/PlayerFeature/Sources/ViewControllers/PlayerViewController.swift
- Projects/Features/PlayerFeature/Sources/ViewControllers/PlaylistViewController+Delegate.swift
- Projects/Features/PlayerFeature/Sources/ViewModels/PlayerViewModel+API.swift
- Projects/Features/PlayerFeature/Sources/ViewModels/PlayerViewModel.swift
- Projects/Features/StorageFeature/Sources/ViewControllers/FavoriteViewController.swift
- Projects/Features/StorageFeature/Sources/ViewControllers/MyPlayListViewController.swift
- Projects/Features/StorageFeature/Sources/ViewModels/FavoriteViewModel.swift
- Projects/Features/StorageFeature/Sources/ViewModels/MyPlayListViewModel.swift
- Projects/Modules/Utility/Sources/Utils/Utils.swift
- Projects/Services/DomainModule/Sources/Playlist/Entity/AddSongEntity.swift
- Projects/Services/NetworkModule/Sources/Playlist/DataTransfer/AddSongTransfer.swift
> :twisted_rightwards_arrows: 토큰 만료 처리

- Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
- Projects/Features/RootFeature/.swiftlint.yml
- Projects/Features/RootFeature/Sources/ViewControllers/IntroViewController.swift
- Projects/Features/RootFeature/Sources/ViewModels/IntroViewModel.swift
- Projects/Features/StorageFeature/Sources/ViewControllers/AfterLoginViewController.swift
- Projects/Features/StorageFeature/Sources/Views/AnswerTableViewCell.swift
- Projects/Features/StorageFeature/Sources/Views/QuestionTableViewCell.swift
- Projects/Services/APIKit/Sources/API/AppAPI.swift
인트로 토큰 만료 처리, 기타 버그 수정, 구라스모피즘은 아직 건드리는중..
Closes #303
> 🔀 :: 인트로 토큰 만료 처리, 기타 버그 수정

- Projects/Features/CommonFeature/Sources/PlayState/PlayState+Public.swift
변경 전
state == .unstarted 의 뜻을 파악하기 어려움
```Swift
if self.state == .unstarted {
self.switchPlayerMode(to: .mini)
self.currentSong = self.playList.currentPlaySong
if let currentSong = currentSong {
self.player.cue(source: .video(id: currentSong.id))
}
}
```
변경 후
플레이어가 닫혀있을 때 노래담기를 하면 일어나는 동작임을 바로 알 수 있음
```Swift
if self.playerMode == .close {
self.switchPlayerMode(to: .mini)
self.currentSong = self.playList.currentPlaySong
if let currentSong = currentSong {
self.player.cue(source: .video(id: currentSong.id))
}
}
```
> 🔀 :: 재생목록에 담기 조건문 명확하게 변경

- Projects/App/Sources/Application/SceneDelegate.swift
- Projects/Features/CommonFeature/Sources/PlayState/PlayState+Public.swift
- Projects/Features/CommonFeature/Sources/PlayState/PlayState.swift
- Projects/Features/MainTabFeature/Sources/ViewControllers/MainContainerViewController.swift
- Projects/Modules/ErrorModule/Sources/WMError.swift
- Scripts/FirebaseCrashlyticsScript.sh
- Tuist/ProjectDescriptionHelpers/Action+Template.swift
- Tuist/ProjectDescriptionHelpers/Environment.swift
1. 백그라운드 > 포그라운드 접근 시 플레이어 상태에 관한 로그를 무조건 띄우도록 변경하였습니다. 
2. 크래시 틱틱스 스크립트 설정을 변경합니다.
> 🔀 :: 플레이어 로그 출력 고도화 및 크래시틱스 셋팅 변경

- Projects/Features/CommonFeature/Sources/Views/GlassmorphismView.swift
- Projects/Features/HomeFeature/Resources/Home.storyboard
- Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
- Projects/Features/PlayerFeature/Sources/Views/PlaylistView.swift
1. 320 스크린에서 재생목록 컨트롤 버튼이 찌그러지는 문제 수정 
<Before>
<After>
2. 구 라 스 모 피 즘 
수정한다고 했는데 전혀 달라진게없군,,
> 🔀 Feature/UI fix

- Projects/Modules/Utility/Sources/GoogleOAuth/GoogleLoginManager.swift
구글로그인 Token으로 주는걸로 바뀌어서 코드 변경했습니다
사실 뭐 별거 없다는...
Closes #이슈번호
> 🔀 :: Google 로그인 변경 완료

- Projects/Features/ArtistFeature/Resources/Artist.storyboard
- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistDetailHeaderViewController.swift
- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistViewController.swift
- Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
- Projects/Features/SignInFeature/Sources/ViewModels/LoginViewModel.swift
- Projects/Features/StorageFeature/Sources/ViewControllers/RequestViewController.swift
> 🔀 :: 폭탄 제거 및 로그인 모델 통합

- Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
- Tuist/ProjectDescriptionHelpers/Environment.swift
🔀 :: 블러 조작단
구라스모피즘의 업그레이드 
Closes #이슈번호
> 🔀 :: 블러 조작단

- Projects/App/Support/Info.plist
- Projects/App/Support/WaktaverseMusic.entitlements
- 유니버셜 링크 적용
- .entitlements 파일에 속성 추가
- 유니버셜 링크 관련 권한 적용한 프로비저닝 교체
Closes #321
> 🔀 ::  유니버셜 링크 적용

- Projects/Features/HomeFeature/.swiftlint.yml
- Projects/Features/HomeFeature/Resources/Home.storyboard
- Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
- Projects/Services/DataMappingModule/Sources/Base/NewSongGroupType.swift
- Tuist/ProjectDescriptionHelpers/Environment.swift
🔀 :: 홈 > 최신음악 > 아카데미 추가
Closes #이슈번호
> 🔀 :: 홈 > 최신음악 > 아카데미 추가

- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistViewController.swift
- Projects/Features/BaseFeature/Sources/EqualHandleTappedType.swift
- Projects/Features/ChartFeature/Sources/ViewContrillers/ChartContentViewController.swift
- Projects/Features/ChartFeature/Sources/ViewContrillers/ChartViewController.swift
- Projects/Features/CommonFeature/Sources/ViewControllers/MultiPurposePopupViewController.swift
- Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
- Projects/Features/MainTabFeature/Sources/ViewControllers/BottomTabBarViewController.swift
- Projects/Features/MainTabFeature/Sources/ViewControllers/MainContainerViewController.swift
- Projects/Features/MainTabFeature/Sources/ViewControllers/MainTabBarViewController.swift
- Projects/Features/SearchFeature/Sources/ViewControllers/AfterSearchContentViewController.swift
- Projects/Features/SearchFeature/Sources/ViewControllers/AfterSearchViewController.swift
- Projects/Features/SearchFeature/Sources/ViewControllers/BeforeSearchContentViewController.swift
- Projects/Features/SearchFeature/Sources/ViewControllers/SearchViewController.swift
- Projects/Features/SignInFeature/Sources/ViewControllers/LoginViewController.swift
- Projects/Features/StorageFeature/Sources/ViewControllers/AfterLoginViewController.swift
- Projects/Features/StorageFeature/Sources/ViewControllers/FavoriteViewController.swift
- Projects/Features/StorageFeature/Sources/ViewControllers/MyPlayListViewController.swift
- Projects/Features/StorageFeature/Sources/ViewControllers/StorageViewController.swift
- Projects/Modules/Utility/Sources/Extensions/Extension+UIScrollView.swift
동일한 탭을 또 누른 경우 일반적인 iOS 앱과 같이 기능 추가 
네비게이션 상에 뷰컨이 2개 이상이면 루트로 팝, 그렇지 않으면 최상단 스크롤 이동 
Closes #345
> 🔀 :: 같은 탭 선택 시 기능 추가

- Projects/Features/StorageFeature/Sources/ViewControllers/BugReportViewController.swift
버그제보 > 첨부파일 용량 30메가까지로 하향
Closes #347
> 🔀 :: 버그제보 > 첨부파일 용량 30메가로 하향

- Projects/Services/APIKit/Sources/API/NoticeAPI.swift
공지 API > os, version 파람 추가
Closes #350
> 🔀 :: 공지 API > os, version 파람 추가

- Projects/App/Sources/Application/SceneDelegate.swift
> 🔀 :: 유니버셜 링크 핸들링 함수 추가

- Projects/App/Support/Info.plist
- Projects/Features/RootFeature/Sources/ViewModels/IntroViewModel.swift
- Projects/Services/APIKit/Sources/Secrets/SecretURL.swift
DEV, PROD 서버 구분
1. 디버그 모드에서는 dev 도메인으로 접속합니다. 나머지는 PROD.
2. 회원 DB가 달라서 회원가입 시 새로 가입됩니다.
3. (중요) 디버그 모드에서도 PROD서버로 접속하고 싶다면, 이그노어 처리로 구성원들간 영향이 없는 Secrets.xcconfig 파일을 수정하세요.
Closes #353
> 🔀 :: DEV, PROD 서버 구분

- Projects/Features/CommonFeature/Resources/CommonUI.storyboard
- Projects/Features/CommonFeature/Sources/ViewControllers/ContainSongsViewController.swift
- Projects/Features/CommonFeature/Sources/Views/RecommendPlayListCell.swift
-  담을곡 00곡 -> 00곡 선택
<br>
-  T6(14.24) -> T6-1(14.2)
<br><br>
Closes #360
Closes #361
> 곡담기 문구 변경 및 추천 플리 폰트 변경

- Projects/Features/ArtistFeature/Resources/Artist.storyboard
- Projects/Features/ArtistFeature/Sources/Views/ArtistMusicCell.swift
- Projects/Features/ChartFeature/Sources/Views/ChartContentTableViewCell.swift
- Projects/Features/CommonFeature/Resources/SongList/SongListCell.xib
- Projects/Features/CommonFeature/Sources/Views/SongListCell.swift
- Projects/Features/SearchFeature/Sources/View/EntireSectionHeader.swift
- Projects/Features/SearchFeature/Sources/ViewControllers/AfterSearchContentViewController.swift
- Projects/Features/SearchFeature/Sources/ViewModels/AfterSearchViewModel.swift
검색결과 UI, 음악재생 사용성 개선
Closes #362 #364
> 🔀 :: 검색결과 UI, 음악재생 사용성 개선

- Projects/Features/SignInFeature/Sources/ViewControllers/LoginViewController.swift
- Projects/Features/SignInFeature/Sources/ViewModels/LoginViewModel.swift
- Projects/Modules/Utility/Sources/GoogleOAuth/GoogleLoginManager.swift
- Tuist/ProjectDescriptionHelpers/Environment.swift
🔀 :: 구글 로그인 리젝 대응
외부 사파리 열기 > 내부 사파리 열기로 변경 
Closes #이슈번호
> 🔀 :: 구글 로그인 리젝 대응

- Projects/App/Sources/Application/AppComponent+Play.swift
- Projects/App/Sources/Application/NeedleGenerated.swift
- Projects/App/Support/Info.plist
- Projects/Features/CommonFeature/Sources/PlayState/PlayState+PlaybackLog.swift
- Projects/Features/CommonFeature/Sources/PlayState/PlayState+YoutubePlayer.swift
- Projects/Features/PlayerFeature/Sources/Components/PlayerComponent.swift
- Projects/Features/PlayerFeature/Sources/ViewModels/PlayerViewModel+API.swift
- Projects/Features/PlayerFeature/Sources/ViewModels/PlayerViewModel.swift
- Projects/Modules/Utility/Sources/Extensions/Extension+Notification.Name.swift
- Projects/Services/APIKit/Sources/API/PlayAPI.swift
- Projects/Services/APIKit/Sources/API/WMAPI.swift
- Projects/Services/APIKit/Sources/Secrets/SecretURL.swift
- Projects/Services/DataMappingModule/Sources/Play/Reponse/PlaybackLogResponseDTO.swift
- Projects/Services/DataModule/Sources/Play/Repositories/PlayRepositoryImpl.swift
- Projects/Services/DataModule/Sources/Play/UseCases/PostPlaybackLogUseCaseImpl.swift
- Projects/Services/DomainModule/Sources/Play/Entity/PostPlaybackLogEntity.swift
- Projects/Services/DomainModule/Sources/Play/Repository/PlayRepository.swift
- Projects/Services/DomainModule/Sources/Play/UseCases/PostPlaybackLogUseCase.swift
- Projects/Services/NetworkModule/Sources/Play/DataTransfer/PostPlaybackLogTransfer.swift
- Projects/Services/NetworkModule/Sources/Play/Remote/RemotePlayDataSource.swift
- Projects/Services/NetworkModule/Sources/Play/Remote/RemotePlayDataSourceImpl.swift
> 🔀 :: 재생 로그 남기기

- Projects/Features/StorageFeature/Sources/ViewControllers/NoticeDetailViewController.swift
- Projects/Features/StorageFeature/Sources/ViewModels/NoticeDetailViewModel.swift
🐛 :: 공지사항 상세 > 이미지가 없는 경우 무한로딩 걸리는 오류 수정
Closes #이슈번호
> 🔀 :: 공지사항 상세 > 이미지가 없는 경우 무한로딩 걸리는 오류 수정

- .github/workflows/SwiftLint.yml
- .swiftlint.yml
SwiftLInt workflow가 항상 실패하는 현상을 해결했어요.
- Root 디렉토리에 `.swiftlint.yml` 파일 추가
- SwiftLint 성공 여부 (에러 존재 여부) Comment로 전달
Closes #403
> 🔀 :: (#403) SwiftLint workflow가 항상 실패하는 현상 해결

- Plugin/TemplatePlugin/Plugin.swift
- Plugin/TemplatePlugin/Templates/Demo/Demo.swift
- Plugin/TemplatePlugin/Templates/Demo/DemoResources.stencil
- Plugin/TemplatePlugin/Templates/Demo/DemoSources.stencil
- Plugin/TemplatePlugin/Templates/Interface/Interface.stencil
- Plugin/TemplatePlugin/Templates/Interface/Interface.swift
- Plugin/TemplatePlugin/Templates/Sources/Sources.stencil
- Plugin/TemplatePlugin/Templates/Sources/Sources.swift
- Plugin/TemplatePlugin/Templates/Testing/Testing.stencil
- Plugin/TemplatePlugin/Templates/Testing/Testing.swift
- Plugin/TemplatePlugin/Templates/Tests/Tests.stencil
- Plugin/TemplatePlugin/Templates/Tests/Tests.swift
- Plugin/TemplatePlugin/Templates/UITests/UITests.stencil
- Plugin/TemplatePlugin/Templates/UITests/UITests.swift
- Tuist/Config.swift
MicroFeatures를 적용한 모듈을 사용할 수 있음에 따라 MicroFeatures용으로 사용 가능한 Scaffold 파일을 추가해요
Resolves: #424
- Template Plugin을 추가했어요
- Template Plugin안에 MicroFeatures용 Scaffold를 추가했어요
- Demo
- Interface
- Sources
- Testing
- UnitTests
- UITests
> 🔀 :: (#424) MicroFeatures Scaffold 추가

- .gitconfig
- Makefile
- Scripts/Setup.sh
SwiftLint, SwitFormat등의 프로젝트를 실행할 때 기본적으로 설치해야하는 앱들을 설치하는 등의 환경 세팅 스크립트를 작성해요
Resolves: #411 
- SwiftLint
- SwiftFormat
- Tuist (mise)
를 설치하는 세팅 스크립트를 작성했어요.
```bash
make setup
...
sh Scripts/Setup.sh
```
위의 두 명령어를 통해 스크립트를 실행할 수 있어요.
#417 의 작업 상 SwiftFormat을 커밋전에 돌려서 반영하게 되다보니 githook를 이용하게 될거같아서 githook을 사전에 세팅해놓았어요.
> 🔀 :: (#411) 개발 환경 세팅 스크립트화

- Projects/App/Sources/Application/AppComponent+Auth.swift
- Projects/App/Sources/Application/NeedleGenerated.swift
- Projects/Domains/AuthDomain/Interface/DataSource/LocalAuthDataSource.swift
- Projects/Domains/AuthDomain/Interface/Repository/AuthRepository.swift
- Projects/Domains/AuthDomain/Interface/UseCase/CheckIsExistAccessTokenUseCase.swift
- Projects/Domains/AuthDomain/Sources/DataSource/LocalAuthDataSourceImpl.swift
- Projects/Domains/AuthDomain/Sources/Repository/AuthRepositoryImpl.swift
- Projects/Domains/AuthDomain/Sources/UseCase/CheckIsExistAccessTokenUseCaseImpl.swift
- Projects/Features/RootFeature/Sources/Components/RootComponent.swift
- Projects/Features/RootFeature/Sources/ViewModels/IntroViewModel.swift
- Projects/Features/SignInFeature/Sources/ViewModels/LoginViewModel.swift
- Projects/Features/StorageFeature/Sources/Components/AfterLoginComponent.swift
- Projects/Features/StorageFeature/Sources/Components/RequestComponent.swift
- Projects/Features/StorageFeature/Sources/ViewModels/AfterLoginStorageViewModel.swift
- Projects/Features/StorageFeature/Sources/ViewModels/RequestViewModel.swift
키체인을 presentation에 해당하는 Feature에서 직접 사용하는 코드가 있었어요. 이 코드들을 제거하고 logout 로직을 도메인단으로 이동해요.
Resolves: #477 
> 🔀 :: (#477) Feature 레이어에서의 keychain 직접 사용 코드 리팩토링

- .package.resolved
- Plugin/ConfigurationPlugin/ProjectDescriptionHelpers/Configuration+Ext.swift
- Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
- Projects/Features/BaseFeature/Project.swift
- Projects/Modules/Utility/Sources/Utils/Utils.swift
- Tuist/Package.resolved
- Tuist/Package.swift
- Tuist/ProjectDescriptionHelpers/Project/Project+Template.swift
- Tuist/ProjectDescriptionHelpers/Target/Target+MicroFeatures.swift
UI 개발을 Hot Reload와 함께 할 수 있는 [Inject](https://github.com/krzysztofzablocki/Inject)를 적용해요
Resolves: #499 
- Inject 라이브러리 추가
- Demo 모듈의 빌드 세팅에 Inject를 위한 세팅 추가
- [설명서](https://www.notion.so/waktaverse/Inject-UI-bb7336508c484c0486097f41de7f4190?pvs=4) 이해되시는지 읽어봐주세요!
> 🔀 :: (#499) Inject 적용

- Projects/Domains/ArtistDomain/Sources/ResponseDTO/ArtistListResponseDTO.swift
🔀 :: (#546) Artist Domain 변경점 적용 2nd
Resolves: #546 
- artistListResponseDTO에 id값 추가.
- name.kr을 id로 사용하던 구문 제거
> 🔀 :: (#546) Artist Domain 변경점 적용 2nd

- .github/workflows/CI.yml
- Xcode 버전이 맞지않아 RealmSwift 관련 버그가 발생합니다.
Resolves: 563
-  RealmSwift 요구 사항인 Xcode15.4보다 낮은 15.3으로 ci 서버 셋팅을 변경합니다.
>
>
> 🔀 :: CI Failed 해결합니다.

- .package.resolved
- Projects/Features/BaseFeature/Project.swift
- Projects/UsertInterfaces/DesignSystem/Sources/WMNavigationBarView.swift
> 🔀 :: [#570] WMNavigationBarView / titleLabel에 text 및 색 지정

- Projects/Features/SignInFeature/Project.swift
SignInFeature를 작업하다가 KeyChainModule이 연결이 안되어있는걸 확인했어요.
Resolves: #577
> SignInFeature에 KeyChainModule 의존성을 추가합니다.
해야할 작업이 많아 빠르게 연결만 했습니다.🙇🏻‍♂️
> 🔀 :: (#577) SignInFeature에 KeyChainModule 의존성을 추가합니다.

- .github/workflows/CI.yml
- Projects/App/Support/Info.plist
- Projects/Domains/BaseDomain/Sources/WMAPI/SecretURL.swift
- Projects/Domains/BaseDomain/Sources/WMAPI/WMAPI.swift
- Projects/Domains/FaqDomain/Interface/Entity/FaqEntity.swift
- Projects/Domains/FaqDomain/Sources/API/FaqAPI.swift
- Projects/Domains/FaqDomain/Sources/ResponseDTO/FaqResponseDTO.swift
- Projects/Features/StorageFeature/Sources/Views/AnswerTableViewCell.swift
🔀 :: [#508] FAQ Domain API 수정사항 반영
Resolves: #508 
API 수정사항 반영
path 말고는 변경된게 딱히 없음. > 그런줄 알았으나 하나 있음 description > answer
xcconfig 수정되었음. (노션 업로드 완료)
> 🔀 :: [#508] FAQ Domain API 수정사항 반영

- Projects/Domains/UserDomain/Sources/API/UserAPI.swift
Resolves: #513
- UserDomain API 변경사항을 반영합니다.
- 따로 DTO가 바뀐게 없어 엔드포인트만 변경하고, 코드 가독성을 향상시켰습니다.
- 프로필 이미지 변경, 닉네임 변경, 회원탈퇴 엔드포인트는 추가예정이라고 하셔서 엔드포인트 부분에 빈문자열 넣어뒀습니다. (후추수정)
> 🔀 :: (#513) UserDomain api 변경사항 반영

- Projects/Domains/AuthDomain/Sources/API/AuthAPI.swift
AccessToken 재발급 api 호출 시 리프레쉬 토큰을 넘겨주는 부분이 없어 보완합니다.
Resolves: #500
- AccessToken 재발급 api 호출 시 리프레쉬 토큰을 넘겨주도록 합니다.
> 🔀 :: (#598) AuthDomain api 보완

- Projects/Features/MyInfoFeature/Sources/ViewControllers/MyInfo/MyInfoViewController.swift
사용성을 개선합니다.
- 스와이프로 뒤로가기 제스처 기능을 추가합니다.
- MyInfoVC 쪽에만 작성해줬는데, 세부 화면들 모두 스와이프 뒤로가기가 적용되더라구요. 원래 그런건가요?
> 🔀 :: 내 정보 화면에 스와이프로 뒤로가기 기능 추가

- Projects/Domains/SongsDomain/Interface/Entity/NewSongsEntity.swift
- Projects/Domains/SongsDomain/Sources/API/SongsAPI.swift
- Projects/Domains/SongsDomain/Sources/ResponseDTO/NewSongsResponseDTO.swift
- Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
- Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
- Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsViewController.swift
- Projects/Features/HomeFeature/Sources/ViewModels/HomeViewModel.swift
- Projects/Features/HomeFeature/Sources/ViewModels/NewSongsContentViewModel.swift
- Projects/Features/HomeFeature/Sources/Views/HomeChartCell.swift
- Projects/Features/HomeFeature/Sources/Views/HomeNewSongCell.swift
- Projects/Features/HomeFeature/Sources/Views/NewSongsCell.swift
- Projects/Features/MainTabFeature/Sources/Views/PlayListFloatingActionButton.swift
최신음악 api 변경 대응
Resolves: #635 
- DTO 수정
- api 요구 파라미터 수정
> 🔀 :: (#635) 최신음악 api 변경 대응

- Projects/Features/MainTabFeature/Resources/Main.storyboard
- Projects/Features/MainTabFeature/Sources/ViewControllers/MainContainerViewController.swift
재생기능이 사라짐에따라 미사용 UI, 제스쳐 제거
Resolves: #636 
- panelView 제거, 관련 UI 제거
- 제스쳐 제거 등
- 잡다한 코드 정리
> 🔀 :: (#636)  미사용 UI, 제스쳐 제거

- Plugin/EnvironmentPlugin/ProjectDescriptionHelpers/ProjectEnvironment.swift
- Projects/App/Sources/Application/AppDelegate.swift
- Projects/Features/BaseFeature/Sources/ViewControllers/BaseReactorViewController.swift
- Projects/Features/BaseFeature/Sources/ViewControllers/BaseStoryboardReactorViewController.swift
- Projects/Features/BaseFeature/Sources/ViewControllers/BaseViewController.swift
- Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
- Projects/Features/MyInfoFeature/Sources/Views/MyInfoNavigationButton.swift
- Projects/Modules/Utility/Sources/Utils/Utils.swift
- Projects/UsertInterfaces/DesignSystem/Sources/VerticalAlignButton.swift
iOS 최소 지원 버전 상향: 15.0
Resolves: #659 
- #available(iOS 15.0, *) 분기 제거
- deprecated 로직 제거
x
> 🔀 :: (#659) iOS 최소 지원 버전 상향

- Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
- Projects/Features/HomeFeature/Sources/ViewModels/NewSongsContentViewModel.swift
🔀 :: (#657) 최신음악: 업데이트 시간 제거
Resolves: #657 
- 업데이트 시간 제거
> 🔀 :: (#657) 최신음악: 업데이트 시간 제거

- Projects/Features/BaseFeature/Sources/ViewControllers/ContainSongsViewController.swift
- Projects/Features/BaseFeature/Sources/Views/BottomSheet/BottomSheetCalculator.swift
- Projects/Features/SearchFeature/Sources/ViewControllers/SearchViewController.swift
- Projects/Features/SignInFeature/Sources/ViewControllers/LoginViewController.swift
- Projects/Features/SignInFeature/Sources/ViewModels/LoginViewModel.swift
- Projects/Features/StorageFeature/Sources/ViewControllers/FavoriteViewController.swift
- Projects/Features/StorageFeature/Sources/ViewControllers/MyPlayListViewController.swift
- Projects/Modules/Utility/Sources/Extensions/Extension+UIViewController.swift
- Projects/Modules/Utility/Sources/GoogleOAuth/GoogleLoginManager.swift
deprecated.
Resolves: #679 
"UIApplication.shared.windows" 잔존 코드 제거
x
> 🔀 :: (#679) "UIApplication.shared.windows" 잔존 코드 제거

- Projects/App/Sources/Application/AppComponent+Playlist.swift
- Projects/Features/PlaylistFeature/Demo/Sources/AppDelegate.swift
- Projects/Features/PlaylistFeature/Interface/MyPlaylistFactory.swift
- Projects/Features/PlaylistFeature/Sources/Components/MyPlaylistDetailComponent.swift
- Projects/Features/PlaylistFeature/Sources/Reactors/MyPlaylistDetailReactor.swift
- Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
- Projects/Features/PlaylistFeature/Tests/MyPlaylistDetailSpec.swift
- Projects/Features/StorageFeature/Resources/Storage.storyboard
- Projects/Features/StorageFeature/Sources/Components/MyPlayListComponent.swift
- Projects/Features/StorageFeature/Sources/Components/PlaylistStorageComponent.swift
- Projects/Features/StorageFeature/Sources/Components/StorageComponent.swift
- Projects/Features/StorageFeature/Sources/Reactors/PlaylistStorageReactor.swift
- Projects/Features/StorageFeature/Sources/ViewControllers/PlaylistStorageViewController.swift
- Projects/Features/StorageFeature/Sources/ViewControllers/StorageViewController.swift
MyPlaylistVC UI작업이 마무리가 가까워 바로 주입할 수 있게  의존성 명시
Resolves: #677
- MyPlaylistVC UI작업이 마무리가 가까워 바로 주입할 수 있게  의존성 명시했습니다.
- Storage Feature에 있는 MyPlaylistVC를  PlaylistStorageVC로 변경
>
>
> 🔀 :: (#677) playlistDomain에 명시된 Usecase를 MyPlaylistVC에 미리 명시해둡니다.

- Projects/Features/BaseFeature/Resources/Base.storyboard
- Projects/Features/MyInfoFeature/Sources/ViewControllers/MyInfo/MyInfoViewController.swift
- Projects/Features/SignInFeature/Resources/SignIn.storyboard
- Projects/Features/SignInFeature/Sources/ViewControllers/LoginViewController.swift
- Projects/Features/SignInFeature/Sources/ViewModels/LoginViewModel.swift
- Projects/Features/StorageFeature/Sources/ViewControllers/StorageViewController.swift
- Projects/Modules/Utility/Sources/GoogleOAuth/GoogleLoginManager.swift
- 레거시 제거 목적
Resolves: #682 
- 로그인 화면 UI 변경사항 대응 (네비게이션 추가, 저작권 표기)
- fullScreen으로 변경
- 로그인 뷰모델 리팩토링
- 구글 로그인은 동작안하고 있었음.
> 🔀 :: (#682) SignInFeature 리팩토링

- Projects/Features/MyInfoFeature/Sources/ViewModels/OpenSourceLicenseViewModel.swift
추가/삭제 오픈소스 라이선스 정리
Resolves: #624
- 제거
PanModal
YoutubePlayerKit
- 추가 
FittedSheets
x
> 🔀 :: (#624) 오픈소스 라이선스 정리

- Projects/App/Sources/Application/AppDelegate.swift
- Projects/Features/ArtistFeature/Sources/Analytics/ArtistAnalyticsLog.swift
- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistDetailHeaderViewController.swift
- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistDetailViewController.swift
- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicViewController.swift
- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistViewController.swift
- Projects/Features/ArtistFeature/Sources/ViewModels/ArtistMusicContentViewModel.swift
- Projects/Features/ArtistFeature/Sources/Views/ArtistListCell.swift
- Projects/Features/ArtistFeature/Sources/Views/ArtistMusicCell.swift
- Projects/Features/ArtistFeature/Sources/Views/ArtistPlayButtonGroupView.swift
애널리틱스 로그 심기
Resolves: #694 
[🟡 ANALYTICS] > click_artist_item logged
parameters : ["artist": "gosegu", "timestamp": 1719504620.89399, "date": "2024-06-28 01:10:20"]
-> AnalyticsLogManager.swift | analytics:125
[🟡 ANALYTICS] > click_artist_tabbar_tab logged
parameters : ["artist": "gosegu", "timestamp": 1719504620.9170651, "tab": "new", "date": "2024-06-28 01:10:20"]
-> AnalyticsLogManager.swift | analytics:125
[🟡 ANALYTICS] > click_artist_description logged
parameters : ["page": "artist", "timestamp": 1719504637.568898, "artist": "gosegu", "date": "2024-06-28 01:10:37"]
-> AnalyticsLogManager.swift | analytics:125
[🟡 ANALYTICS] > click_artist_play_button logged
parameters : ["type": "all", "artist": "gosegu", "timestamp": 1719504643.8132272, "date": "2024-06-28 01:10:43"]
-> …
> 🔀 :: (#694) ArtistFeature 애널리틱스 로그 심기

- Projects/Features/ArtistFeature/Sources/Analytics/ArtistAnalyticsLog.swift
- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistDetailViewController.swift
- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistViewController.swift
ArtistFeature 애널리틱스 로그 심기 (view_page 누락)
Resolves: #700 
[🟡 ANALYTICS] > view_page logged
parameters : ["date": "2024-06-28 11:38:58", "page_name": "artist", "timestamp": 1719542338.036696]
-> AnalyticsLogManager.swift | analytics:125
[🟡 ANALYTICS] > view_page logged
parameters : ["page_name": "artist_detail", "timestamp": 1719542409.6140552, "date": "2024-06-28 11:40:09"]
-> AnalyticsLogManager.swift | analytics:125  
x
> 🔀 :: (#700) ArtistFeature 애널리틱스 로그 심기 (view_page 누락)

- Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricHighlightingViewController.swift
> 🔀 :: (#697) 가사 하이라이팅 > 흐르는 레이블 적용

- Projects/Features/BaseFeature/Sources/Protocols/WMBottomSheetViewType.swift
- Projects/Features/BaseFeature/Sources/Views/WMBottomSheetView.swift
- 바텀시트의 종류가 늘어나면서 관리가 힘들어짐.
- 필요한 버튼을 주입하는 형태로 변경.
Resolves: #716 
기존 코드와 유사함.
- WMBottomSheetView
- WMBottomSheetViewType
> 🔀 :: (#716) 바텀시트 일원화

- Projects/Features/SignInFeature/Sources/ViewControllers/LoginViewController.swift
메인스레드 익셉션 오류 해결
Resolves: #730 
observe(on:)
x
> 🔀 :: (#730) 로그인 화면:: 메인스레드 익셉션 오류 해결

- Projects/Features/FruitDrawFeature/Sources/ViewControllers/FruitDrawViewController.swift
- 추가 수정사항 반영
Resolves: #736 
- 로티 애니메이션 시작하면 네비바 숨김
x
> 🔀 :: (#736) 열매 뽑기:: 추가 수정사항 반영

- Projects/Features/FruitDrawFeature/Sources/Analytics/FruitDrawAnalyticsLog.swift
- Projects/Features/FruitDrawFeature/Sources/ViewControllers/FruitDrawViewController.swift
- Projects/Features/FruitDrawFeature/Sources/ViewControllers/FruitStorageViewController.swift
- Projects/Modules/LogManager/Sources/AnalyticsLogType.swift
- (열매뽑기, 열매함) 로그심기
Resolves: #744
- [🟡 ANALYTICS] > view_page logged
parameters : ["date": "2024-07-06 23:43:20", "page_name": "fruit_draw", "timestamp": 1720277000.455772]
- [🟡 ANALYTICS] > click_fruit_draw_button logged
parameters : ["date": "2024-07-06 23:41:07", "timestamp": 1720276867.559636]
- [🟡 ANALYTICS] > view_page logged
parameters : ["date": "2024-07-06 23:43:28", "page_name": "fruit_storage", "timestamp": 1720277008.342274]
- [🟡 ANALYTICS] > click_fruit_item logged
parameters : ["date": "2024-07-06 23:43:33", "timestamp": 1720277013.806551, "id": "1"]
- (PR 외) 로그에 파라미터가 없으면, 기본 파람(date, timestamp)도 넣지 않던 로직 수정
x
> 🔀 :: (#744) 열매뽑기:: 로그심기

- Projects/Features/LyricHighlightingFeature/Sources/Analytics/LyricHighlightingAnalyticsLog.swift
- Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricDecoratingViewController+Bind.swift
- Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricDecoratingViewController.swift
- Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricHighlightingViewController+Bind.swift
- Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricHighlightingViewController.swift
- Projects/Features/LyricHighlightingFeature/Sources/ViewModels/LyricDecoratingViewModel.swift
- Projects/Features/LyricHighlightingFeature/Sources/ViewModels/LyricHighlightingViewModel.swift
로그 심기
Resolves: #743 
- [🟡 ANALYTICS] > view_page logged
parameters : ["timestamp": 1720278099.643568, "date": "2024-07-07 00:01:39", "page_name": "lyric_highlighting"]
- [🟡 ANALYTICS] > view_page logged
parameters : ["date": "2024-07-07 00:01:46", "timestamp": 1720278106.099621, "page_name": "lyric_decorating"]
- [🟡 ANALYTICS] > click_lyric_decorating_complete_button logged
parameters : ["id": "fgSXAKsq-Vo", "type": "save", "date": "2024-07-07 00:01:54", "bg": "1", "timestamp": 1720278114.4316468]
- [🟡 ANALYTICS] > click_lyric_decorating_complete_button logged
parameters : ["timestamp": 1720278118.113072, "id": "fgSXAKsq-Vo", "bg": "1", "type": "share", "date": "2024-07-07 00:01:58"]
x
> 🔀 :: (#743) 가사 하이라이팅:: 로그 심기

- Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
- Projects/App/Project.swift
- Projects/App/Sources/Application/AppComponent+Notification.swift
- Projects/App/Support/Info.plist
- Projects/Domains/BaseDomain/Sources/WMAPI/SecretURL.swift
- Projects/Domains/BaseDomain/Sources/WMAPI/WMAPI.swift
- Projects/Domains/NotificationDomain/Interface/DataSource/RemoteNotificationDataSource.swift
- Projects/Domains/NotificationDomain/Interface/Enum/NotificationUpdateType.swift
- Projects/Domains/NotificationDomain/Interface/Repository/NotificationRepository.swift
- Projects/Domains/NotificationDomain/Interface/UseCase/UpdateNotificationTokenUseCase.swift
- Projects/Domains/NotificationDomain/Project.swift
- Projects/Domains/NotificationDomain/Sources/API/NotificationAPI.swift
- Projects/Domains/NotificationDomain/Sources/DataSource/RemoteNotificationDataSourceImpl.swift
- Projects/Domains/NotificationDomain/Sources/Repository/NotificationRepositoryImpl.swift
- Projects/Domains/NotificationDomain/Sources/UseCase/UpdateNotificationTokenUseCaseImpl.swift
- Projects/Features/MainTabFeature/Project.swift
- 신규 API 추가
Resolves: #739 
- Notification Domain 모듈 생성 및 부가 작업
x
> 🔀 :: (#739) Notification Domain

- Projects/Features/SearchFeature/Sources/CompositionalLayout/Layout/BeforeSearchCollectionViewLayout.swift
- Projects/Features/SearchFeature/Sources/CompositionalLayout/Layout/RecommendCollectionViewLayout.swift
잘못된 비율 수정
Resolves: #776
item 및 group height 비율 조절
>
>
> 🔀 :: (#776) 검색 전 화면 왁뮤 추천플리 레이아웃 조절

- Projects/Domains/BaseDomain/Sources/DataSource/BaseRemoteDataSource.swift
- 토큰 자동 리프레시를 하는 로직의 조건문이 비정상적이었어요.
Resolves: #431 
- 토큰 만료일자가 오늘보다 이전이라면 만료라고 판정해요.
> 🔀 :: (#431) 토큰 자동 리프레시 validation 로직 정상화

- Projects/App/Sources/Application/AppDelegate.swift
- Projects/Modules/LogManager/Sources/AnalyticsLogManager.swift
- Projects/Modules/LogManager/Sources/AnalyticsLogType.swift
- Projects/Modules/LogManager/Sources/LogHistory/LogHistoryCell.swift
애널리틱스의 기본 파라미터를 주입했던 로직을 제거해요
Resolves: #782 
> PR에서 한 작업을 자세히 작성해주세요!
> 🔀 :: (#782) Analytics 기본 파라미터 제거

- Projects/Domains/SongsDomain/Interface/Entity/SongEntity.swift
- Projects/Domains/SongsDomain/Sources/ResponseDTO/SingleSongResponseDTO.swift
- Projects/Domains/UserDomain/Sources/ResponseDTO/FavoriteSongsResponseDTO.swift
- Projects/Domains/UserDomain/Testing/FetchFavoriteSongsUseCaseStub.swift
- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
- Projects/Features/ArtistFeature/Sources/ViewModels/ArtistMusicContentViewModel.swift
- Projects/Features/ArtistFeature/Sources/Views/ArtistMusicCell.swift
- Projects/Features/ChartFeature/Sources/ViewModels/ChartContentViewModel.swift
- Projects/Features/ChartFeature/Sources/Views/ChartContentTableViewCell.swift
- Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
- Projects/Features/HomeFeature/Sources/ViewModels/HomeViewModel.swift
- Projects/Features/HomeFeature/Sources/ViewModels/NewSongsContentViewModel.swift
- Projects/Features/HomeFeature/Sources/Views/NewSongsCell.swift
- 미사용 프로퍼티 제거
Resolves: #805 
- remix, reaction, last (제거)
x
> 🔀 :: (#805) SongEntity:: 미사용 프로퍼티 제거

- Projects/Modules/Utility/Sources/Player/WakmusicPlayer.swift
- Projects/Modules/Utility/Sources/Player/WakmusicYoutubePlayer.swift
- Projects/Modules/Utility/Sources/Youtube/YoutubeURLGenerator.swift
- 대충 음악을 플레이하는 역할을 할 친구를 만들어놓았어요
Resolves: #793 
- WakmusicPlayer 프로토콜 하나 파서 나중에 갑자기 급발진으로 웹뷰에 올려야한다거나 인앱에서 다른 페이지로 옮겨야한다거나 같은 케이스에 알아서 잘 확장하라고 만들어놓았어용 
- 실제로 쓸때는 `WakmusicYoutubePlayer(id: id).play()` 이런식으로 그냥 구현체 참조해서 갖다쓰시면 돼요 유틸성이라 프로토콜은 그저 역할 정의용
> 🔀 :: (#793) WakmusicPlayer 추가

- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
- Projects/Features/ChartFeature/Sources/ViewContrillers/ChartContentViewController.swift
- Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
- 차트:: 50곡 초과 선택 토스트 안내
Resolves: #820 
- 차트:: 50곡 초과 선택 토스트 안내
x
> 🔀 :: (#820) 차트:: 50곡 초과 선택 토스트 안내

- Projects/Features/ArtistFeature/Resources/ArtistPlayButtonGroupView.xib
- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
- Projects/Features/ArtistFeature/Sources/ViewModels/ArtistMusicContentViewModel.swift
- Projects/Features/ArtistFeature/Sources/Views/ArtistPlayButtonGroupView.swift
- Projects/Features/ChartFeature/Sources/ViewContrillers/ChartContentViewController.swift
- Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
- 아티스트:: 50곡 초과 선택 토스트 안내
Resolves: #819 
- 50곡 초과 선택 토스트 안내
- 전체 재생 버튼 통일
x
> 🔀 :: (#819) 아티스트:: 50곡 초과 선택 토스트 안내

- Projects/Features/MusicDetailFeature/Project.swift
- Projects/Features/MusicDetailFeature/Sources/Component/MusicDetailComponent.swift
음악 상세 Testable import 제거
Resolves: #823 
- MusicDetailComponent가 testable import를 하고 있어서 제거했어요
> 🔀 :: (#823) Testable import 제거

- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
- Projects/Features/ChartFeature/Sources/ViewContrillers/ChartContentViewController.swift
- Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
- 최신음악, 아티스트, 차트에 하드코딩된 스트링을 LocalizationStrings로 변경합니다.
Resolves: #831 
- LocalizationStrings 적용
x
> 🔀 :: (#831) LocalizationStrings 적용

- Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
- Projects/App/Project.swift
- Projects/Domains/SongsDomain/Testing/UseCase/FetchSongCreditsUseCaseSpy.swift
- Projects/Features/MusicDetailFeature/Project.swift
- Projects/Features/SongCreditFeature/Demo/Resources/LaunchScreen.storyboard
- Projects/Features/SongCreditFeature/Demo/Sources/AppDelegate.swift
- Projects/Features/SongCreditFeature/Interface/Interface.swift
- Projects/Features/SongCreditFeature/Project.swift
- Projects/Features/SongCreditFeature/Sources/Model/CreditModel.swift
- Projects/Features/SongCreditFeature/Sources/SongCreditReactor.swift
- Projects/Features/SongCreditFeature/Sources/SongCreditViewController.swift
- Projects/Features/SongCreditFeature/Sources/Sources.swift
- Projects/Features/SongCreditFeature/Sources/View/CreditCollectionView/CreditCollectionViewCell.swift
- Projects/Features/SongCreditFeature/Sources/View/CreditCollectionView/CreditCollectionViewLayout.swift
- Projects/Features/SongCreditFeature/Sources/View/CreditCollectionView/CreditCollectionViewPositionHeaderView.swift
- Projects/Features/SongCreditFeature/Testing/Testing.swift
- Projects/Features/SongCreditFeature/Tests/SongCreditFeatureTest.swift
- Projects/Modules/Localization/Resources/en.lproj/Localizable.strings
- Projects/Modules/Localization/Resources/ko.lproj/Localizable.strings
크레딧 화면의 UI를 추가해요.
(스크린샷의 배경은 세구 팬섭일때 예시에요)
Resolves: #810 
- Credit 화면 UI를 추가했어요.
> 🔀 :: (#810) 크레딧 화면 UI 추가

- Projects/Features/SearchFeature/Sources/ViewControllers/SongSearchResultViewController.swift
Resolves: #830
Resolves: #8829
- 제한 메시지 설정
- 플레이어 연결
>
>
> 🔀 :: (#830)  검색화면에 50곡 제한 관련 메시지를 작성합니다.

- Projects/Features/BaseFeature/Sources/Views/WarningView.swift
- Projects/UsertInterfaces/DesignSystem/Sources/Views/WMWarningView.swift
- WarningView 폰트 변경
Resolves: #850 
- 폰트 변경 (Medium > Light)
x
> 🔀 :: (#850) WarningView 폰트 변경

- Projects/Features/PlaylistFeature/Sources/Components/CheckThumbnailComponent.swift
- Projects/Features/PlaylistFeature/Sources/Reactors/CheckThumbnailReactor.swift
- Projects/Features/PlaylistFeature/Sources/Reactors/DefaultPlaylistImageReactor.swift
- Projects/Features/PlaylistFeature/Sources/Reactors/MyPlaylistDetailReactor.swift
- Projects/Features/PlaylistFeature/Sources/ViewControllers/CheckThumbnailViewController.swift
- Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
- Projects/Features/PlaylistFeature/Sources/Views/MyPlaylistHeaderView.swift
이미지 압축 후 80%형태의 jpeg 형태로 데이터를 변환합니다.
Resolves: #849
https://github.com/user-attachments/assets/e3b3b34e-420b-49d5-a57c-c34efb782b38
- 이미지 데이터 압축
- 10MB 넘어갈 시 예외 화면 처리
>
>
> 🔀 :: (#849) 이미지 압축 80%를 진행합니다.

- Projects/App/Sources/Application/AppComponent.swift
- Projects/App/Sources/Application/SceneDelegate.swift
- Projects/App/Support/Info.plist
- Projects/App/Support/WaktaverseMusic.entitlements
- Projects/Features/MainTabFeature/Sources/AppEntryState/AppEntryState.swift
- Projects/Features/MainTabFeature/Sources/Components/MainTabBarComponent.swift
- Projects/Features/MainTabFeature/Sources/ViewControllers/MainContainerViewController.swift
- Projects/Features/MainTabFeature/Sources/ViewControllers/MainTabBarViewController.swift
- Projects/Modules/Utility/Sources/Extensions/Extension+URL.swift
- Projects/Modules/Utility/Sources/Utils/Secrets.swift
- 딥링크, 유니버셜링크 구현
Resolves: #863 
- 링크를 수신하여 해당 화면으로 진입하는 로직은 AppEntryStateHandleable으로 구현 (이미 있는 globalState와 비슷함)
- AppEntryStateHandleable는 푸시 알림에도 사용할 예정
- 딥링크와 유니버셜링크 형태는 디코 쓰레드 참고
> 🔀 :: (#863) 딥링크, 유니버셜링크 구현

- Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
- Projects/Modules/Utility/Sources/Extensions/Extension+UIImage.swift
- 리사이징 로직 보완
Resolves: #882 
**Case 1** 
[🔵 DEBUG] > 🖼️ 원본너비: 64.0, 🖼️ 원본높이: 64.0
[🔵 DEBUG] > 크롭 ❌
[🔵 DEBUG] > 리사이징 ❌
**Case2**
[🔵 DEBUG] > 🖼️ 원본너비: 501.0, 🖼️ 원본높이: 501.0
[🔵 DEBUG] > 크롭 ❌
[🔵 DEBUG] > ✅ 리사이징너비: 500.0, ✅ 리사이징높이: 500.0
**Case3**
[🔵 DEBUG] > 🖼️ 원본너비: 860.0, 🖼️ 원본높이: 8080.0
[🔵 DEBUG] > ✅ 크롭너비: 860, ✅ 크롭높이: 860
[🔵 DEBUG] > ✅ 리사이징너비: 500.0, ✅ 리사이징높이: 500.0
**Case4**
[🔵 DEBUG] > 🖼️ 원본너비: 4000.0, 🖼️ 원본높이: 2256.0
[🔵 DEBUG] > ✅ 크롭너비: 2256, ✅ 크롭높이: 2256
[🔵 DEBUG] > ✅ 리사이징너비: 500.0, ✅ 리사이징높이: 500.0
**Case5** 
[🔵 DEBUG] > 🖼️ 원본너비: 1600.0, 🖼️ 원본높이: 900.0
[🔵 DEBUG] > ✅ 크롭너비: 900, ✅ 크롭높이: 900
[🔵 DEBUG] > ✅ 리사이징너비: 500.0, ✅ 리사이징높이: 500.0 
**Case6**
[🔵 DEBUG] > 🖼️ 원본너비: 500.0, 🖼️ 원본높이: 500.0
[🔵 DEBUG] > 크롭 ❌
[🔵 DEBUG] > 리사이징 ❌
**Case7**
[🔵 DEBUG] > 🖼️ 원본너비: 64.0, 🖼️ 원본높이: 60.0
[🔵 DEBUG] > ✅ …
> 🔀 :: (#882) 리사이징 로직 보완

- Projects/App/Sources/Application/SceneDelegate.swift
- Projects/Features/HomeFeature/Sources/Components/NewSongsContentComponent.swift
- Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
- Projects/Features/HomeFeature/Sources/Views/NewSongsCell.swift
- #890 
Resolves: #903 
- 노래 상세 연결
- (PR 번외) 유니버셜링크 로직 수정
x
> 🔀 :: (#903) 최신음악:: 노래 상세 연결 외 1

- Projects/App/Sources/Application/SceneDelegate.swift
- Projects/Features/ChartFeature/Sources/Components/ChartContentComponent.swift
- Projects/Features/ChartFeature/Sources/ViewContrillers/ChartContentViewController.swift
- Projects/Features/ChartFeature/Sources/Views/ChartContentTableViewCell.swift
- Projects/Features/HomeFeature/Sources/Components/NewSongsContentComponent.swift
- Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
- Projects/Features/HomeFeature/Sources/Views/NewSongsCell.swift
- #890 
Resolves: #902 
- 노래 상세 연결
x
> 🔀 :: (#902) 차트:: 노래 상세 연결

- Projects/App/Sources/Application/AppComponent+Songs.swift
- Projects/App/Sources/Application/SceneDelegate.swift
- Projects/Features/ArtistFeature/Resources/Artist.storyboard
- Projects/Features/ArtistFeature/Sources/Components/ArtistMusicContentComponent.swift
- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
- Projects/Features/ArtistFeature/Sources/Views/ArtistMusicCell.swift
- Projects/Features/BaseFeature/Sources/SongDetailPresenter/SongDetailPresenter.swift
- Projects/Features/ChartFeature/Sources/Components/ChartContentComponent.swift
- Projects/Features/ChartFeature/Sources/ViewContrillers/ChartContentViewController.swift
- Projects/Features/ChartFeature/Sources/Views/ChartContentTableViewCell.swift
- Projects/Features/HomeFeature/Sources/Components/NewSongsContentComponent.swift
- Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
- Projects/Features/HomeFeature/Sources/Views/NewSongsCell.swift
- Projects/Features/MainTabFeature/Project.swift
- Projects/Features/MainTabFeature/Sources/Components/MainTabBarComponent.swift
- Projects/Features/MainTabFeature/Sources/ViewControllers/MainTabBarViewController.swift
- #890 
Resolves: #900 
- SongDetailPresenter 사용
x
> 🔀 :: (#900) 아티스트 상세:: 노래 상세 연결

- Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
- Projects/Features/HomeFeature/Sources/ViewModels/HomeViewModel.swift
- 홈 화면: 누락사항 반영
Resolves: #914 
- 전체듣기 > 전체보기 타이틀 변경
- 추천 플레이리스트 상세 연결
- deprecated 제거
x
> 🔀 :: (#914) 홈 화면: 누락사항 반영

- Projects/Domains/TeamDomain/Interface/Entity/TeamListEntity.swift
- Projects/Domains/TeamDomain/Sources/ResponseDTO/FetchTeamListResponseDTO.swift
- Projects/Features/TeamFeature/Sources/ViewControllers/TeamInfoContentViewController.swift
- Projects/Features/TeamFeature/Sources/ViewModels/TeamInfoContentViewModel.swift
- Projects/Features/TeamFeature/Sources/ViewModels/TeamInfoViewModel.swift
- Projects/Features/TeamFeature/Sources/Views/TeamInfoHeaderView.swift
- Projects/Features/TeamFeature/Sources/Views/TeamInfoListCell.swift
- 팀 소개 화면 최종
Resolves: #935 
- 총괄 파트 예외처리
- 프로필 임시코드 제거
- 더미 생성코드 제거
x
> 🔀 :: (#935) 팀 소개:: 최종

- Projects/Domains/ArtistDomain/Interface/Entity/ArtistListEntity.swift
- Projects/Domains/ArtistDomain/Sources/ResponseDTO/ArtistListResponseDTO.swift
- Projects/Features/ArtistFeature/Sources/Reactors/ArtistReactor.swift
- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
- Projects/Features/ArtistFeature/Sources/ViewModels/ArtistMusicContentViewModel.swift
- Projects/Features/ArtistFeature/Tests/ArtistReactorTests.swift
- 서버에서 플리 url이 도착
Resolves: #933 
- 아티스트 상세:: 전체재생 기능 (유튭 연결)
x
> 🔀 :: (#933) 아티스트 상세:: 전체재생 기능

- Projects/App/Sources/Application/AppComponent+Playlist.swift
- Projects/Domains/PlaylistDomain/Sources/API/PlaylistAPI.swift
- Projects/Domains/PlaylistDomain/Sources/DataSource/RemotePlaylistDataSourceImpl.swift
- Projects/Domains/PlaylistDomain/Sources/Repository/PlaylistRepositoryImpl.swift
- Projects/Domains/PlaylistDomain/Sources/ResponseDTO/PlaylistOwnerIdResponseDTO.swift
- Projects/Features/ArtistFeature/Sources/Components/ArtistMusicContentComponent.swift
- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
- Projects/Features/ArtistFeature/Sources/ViewModels/ArtistMusicContentViewModel.swift
- Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
- Projects/Features/PlaylistFeature/Interface/PlaylistDetailNavigator.swift
- Projects/Features/PlaylistFeature/Sources/Components/PlaylistDetailComponent.swift
- Projects/Features/PlaylistFeature/Sources/Components/UnkwonPlaylistDetailComponent.swift
- Projects/Features/PlaylistFeature/Sources/Reactors/PlaylistDetailContainerReactor.swift
- Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
- Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistDetailContainerViewController.swift
- Projects/Features/PlaylistFeature/Sources/ViewControllers/UnknownPlaylistDetailViewController.swift
- Projects/Features/PlaylistFeature/Testing/PlaylistDetailFactoryStub.swift
- Projects/Features/SearchFeature/Sources/After/ViewControllers/ListSearchResultViewController.swift
- Projects/Features/SearchFeature/Sources/After/ViewControllers/SongSearchResultViewController.swift
- Projects/Features/StorageFeature/Sources/Reactors/ListStorageReactor.swift
- 아티스트 상세:: 노래담기 비로그인 처리
Resolves: #940 
- 노래담기 비로그인 처리
x
> 🔀 :: (#940) 아티스트 상세:: 노래담기 비로그인 처리

- Projects/Features/BaseFeature/Sources/Etc/PlayState/PlayState.swift
PlayState의 외부에 노출된 인터페이스 구현 코드를 정리했어요
Resolves: #911
- append, insert에 중복 노래는 제거하는 로직을 추가했어요
- 인터페이스를 갈기에는 당장에는 적합하지도 않아서 좀 더 나중에 더 좋은 설계를 떠올렸을 때 혹은 갈아엎을 때 한 번 본격정리할 생각이에요. 현재 정리한 코드는 기능적 이슈 정리에 가깝게 진행됐네요.
> 🔀 :: (#911) PlayState 인터페이스 정리

- Projects/Features/SongCreditFeature/Sources/SongCreditViewController.swift
- Projects/Features/SongCreditFeature/Sources/View/CreditCollectionView/CreditCollectionViewLayout.swift
Credit 화면 UI 수정
Resolves: #925
Credit 화면 UI 수정
- 일부 보정값을 넣었어요.
> 🔀 :: (#925) Credit Page UI 정상화

- Projects/Features/ChartFeature/Project.swift
- Projects/Features/ChartFeature/Sources/Components/ChartContentComponent.swift
- Projects/Features/ChartFeature/Sources/ViewContrillers/ChartContentViewController.swift
- Projects/Features/ChartFeature/Sources/ViewModels/ChartContentViewModel.swift
- Projects/Features/HomeFeature/Project.swift
- Projects/Features/HomeFeature/Sources/Components/NewSongsContentComponent.swift
- Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
- Projects/Features/HomeFeature/Sources/ViewModels/NewSongsContentViewModel.swift
- 차트, 최신음악 > 비로그인 시 노래 담기 액션 처리
Resolves: #959 
- 차트, 최신음악 > 비로그인 시 노래 담기 액션 처리
x
> 🔀 :: (#959) 차트, 최신음악 > 비로그인 시 노래 담기 액션 처리

- Projects/Domains/SongsDomain/Interface/DataSource/RemoteSongsDataSource.swift
- Projects/Domains/SongsDomain/Interface/Entity/LyricsEntity.swift
- Projects/Domains/SongsDomain/Interface/Repository/SongsRepository.swift
- Projects/Domains/SongsDomain/Interface/UseCase/FetchLyricsUseCase.swift
- Projects/Domains/SongsDomain/Sources/DataSource/RemoteSongsDataSourceImpl.swift
- Projects/Domains/SongsDomain/Sources/Repository/SongsRepositoryImpl.swift
- Projects/Domains/SongsDomain/Sources/ResponseDTO/LyricsResponseDTO.swift
- Projects/Domains/SongsDomain/Sources/UseCase/FetchLyricsUseCaseImpl.swift
- Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricDecoratingViewController+Bind.swift
- Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricDecoratingViewController.swift
- Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricHighlightingViewController+Bind.swift
- Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricHighlightingViewController.swift
- Projects/Features/LyricHighlightingFeature/Sources/ViewModels/LyricHighlightingViewModel.swift
- Projects/Features/LyricHighlightingFeature/Sources/Views/LyricHighlightingCell.swift
- 자막 제공자를 추가
Resolves: #968 
- response DTO, entity 변경
- 자막 제공 추가
- 공유하기 버튼 삭제
- 기타 레이아웃 조정
x
> 🔀 :: (#968) 가사 하이라이팅 > 자막 제공 UI 추가

- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
- Projects/Features/ChartFeature/Sources/ViewContrillers/ChartContentViewController.swift
- Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabItemReactor.swift
- Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
- Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
- Projects/Features/PlaylistFeature/Sources/ViewControllers/UnknownPlaylistDetailViewController.swift
- Projects/Features/PlaylistFeature/Sources/ViewControllers/WakmusicPlaylistDetailViewController.swift
- Projects/Features/SearchFeature/Sources/After/ViewControllers/SongSearchResultViewController.swift
누락된 토스트를 명시합니다.
Resolves: #985
- 높이가 맞지 않은 토스트 메시지 높이 수정
- 차트, 크레딧 누락된 토스트 명시
>
>
> 🔀 :: (#985) 50곡 제한 토스트 누락 토스트 명시

- Projects/Features/StorageFeature/Sources/Components/LikeStorageComponent.swift
- Projects/Features/StorageFeature/Sources/ViewControllers/LikeStorageViewController.swift
- Projects/Features/StorageFeature/Sources/Views/LikeStorageTableViewCell.swift
Resolves: #890
https://github.com/user-attachments/assets/b104c19f-6b16-40bf-886d-1cb03203435d
- 좋아요 탭에서 썸네일 클릭 시 노래 상세로 이동
> 🔀 :: (#890) 좋아요 탭에서 썸네일 클릭 시 노래 상세로 이동

- Projects/App/Sources/Application/AppComponent+Price.swift
- Projects/Domains/PriceDomain/Interface/UseCase/FetchPlaylistCreationPriceUseCase.swift
- Projects/Domains/PriceDomain/Interface/UseCase/FetchPlaylistImagePriceUseCase.swift
- Projects/Domains/PriceDomain/Sources/UseCase/FetchPlaylistCreationPriceUseCaseImpl.swift
- Projects/Domains/PriceDomain/Sources/UseCase/FetchPlaylistImagePriceUseCaseImpl.swift
- Projects/Features/BaseFeature/Sources/Components/ContainSongsComponent.swift
- Projects/Features/BaseFeature/Sources/ViewModels/ContainSongsViewModel.swift
- Projects/Features/PlaylistFeature/Sources/Components/PlaylistCoverOptionPopupComponent.swift
- Projects/Features/PlaylistFeature/Sources/Reactors/PlaylistCoverOptionPopupReactor.swift
- Projects/Features/StorageFeature/Sources/Components/ListStorageComponent.swift
- Projects/Features/StorageFeature/Sources/Reactors/ListStorageReactor.swift
- Projects/Features/StorageFeature/Sources/ViewControllers/ListStorageViewController.swift
- Projects/Features/StorageFeature/Sources/ViewControllers/StorageViewController.swift
Resolves: #977
- 보관함 리스트 생성 시 음표 열매 소모
> 🔀 :: (#977) 보관함 리스트 생성 시 음표 열매 소모

- Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
- Projects/App/Sources/Application/AppDelegate.swift
- Projects/App/Sources/Application/SceneDelegate.swift
- Projects/App/Support/Info.plist
- Projects/App/Support/WaktaverseMusic.entitlements
- Projects/Domains/BaseDomain/Sources/BasePlugin/BasePlugin.swift
- Projects/Domains/NotificationDomain/Interface/UpdateNotificationTokenUseCaseSpy.swift
- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistDetailViewController.swift
- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistViewController.swift
- Projects/Features/ArtistFeature/Sources/ViewModels/ArtistDetailViewModel.swift
- Projects/Features/FruitDrawFeature/Sources/Components/FruitStorageComponent.swift
- Projects/Features/FruitDrawFeature/Sources/ViewModels/FruitStorageViewModel.swift
- Projects/Features/MainTabFeature/Sources/Components/MainTabBarComponent.swift
- Projects/Features/MainTabFeature/Sources/ViewControllers/MainTabBarViewController.swift
- Projects/Features/MainTabFeature/Sources/ViewModels/MainTabBarViewModel.swift
- Projects/Features/MyInfoFeature/Interface/Enum/SettingItemCategory.swift
- Projects/Features/MyInfoFeature/Project.swift
- Projects/Features/MyInfoFeature/Sources/Components/SettingComponent.swift
- Projects/Features/MyInfoFeature/Sources/DataSource/SettingItemDataSource.swift
- Projects/Features/MyInfoFeature/Sources/Reactors/SettingReactor.swift
- Projects/Features/MyInfoFeature/Sources/ViewControllers/Setting/SettingViewController.swift
- Projects/Features/MyInfoFeature/Sources/Views/SettingItemTableViewCell.swift
- Projects/Features/MyInfoFeature/Sources/Views/SettingView.swift
- Projects/Features/MyInfoFeature/Testing/SettingComponentStub.swift
- Projects/Modules/ThirdPartyLib/Project.swift
- Projects/Modules/Utility/Sources/Extensions/Extension+Dictionary.swift
- Projects/Modules/Utility/Sources/Extensions/Extension+Messaging.swift
- Projects/Modules/Utility/Sources/Extensions/Extension+URL.swift
- Projects/Modules/Utility/Sources/Manager/PreferenceManager.swift
- 푸시알림 기능 추가
Resolves: #532 
Resolves: #839  
- 푸시 알림 기능 구현
- 푸시 토큰 서버 동기화 (앱 접속 시, 기기알림 on/off, 로그인/아웃, 토큰 리프레쉬)
- 내 정보> 설정 > 기기알림 상태 표기, 레이아웃 리팩토링
x
> 🔀 :: [#532] 푸시 알림 기능 구현

- Projects/Features/StorageFeature/Sources/Reactors/ListStorageReactor.swift
Resolves: #1004
- 열매 부족 시 토스트 메시지
- 리스트 생성 성공 후 리프레쉬 노티 전송
- 리스트 생성 중 인디케이터 추가
> 🔀 :: [#1004] 리스트 생성 버그 수정

- Projects/Features/BaseFeature/Resources/Base.storyboard
- Projects/Features/BaseFeature/Sources/ViewControllers/MultiPurposePopupViewController.swift
- Projects/Features/BaseFeature/Sources/ViewModels/MultiPurposePopupViewModel.swift
- Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
- 글자 수 제한이 존재하는데, 입력은 무한대로 되는 문제 
- 복사 붙여넣기는 막을 수 없으나, 키보드 입력은 막는게 맞다고 판단
- 추가로 백엔드에서도 제한을 두기로 함
Resolves: #1018 
- 케이스별 글자 수 제한 (8 or 12)
- 불필요 프로퍼티 제거 등
- 마이 플레이리스트 상세: 키보드 화면 높이 값 오류 수정
x
> 🔀 :: (#1019) 키보드 입력화면 글자 수 제한

- Projects/Features/BaseFeature/Interface/Enum/PurposeType.swift
- Projects/Features/BaseFeature/Sources/ViewControllers/MultiPurposePopupViewController.swift
- PR 코멘트를 지나치고 머지해버려서 다시 함
Resolves: #1027 
- limitCount enum type 확장으로 변경
- 어지러운 삼항연산자 제거
- UI 코드는 다루지않음
> 🔀 :: (#1027) 키보드 입력화면의 enum 정리 및 개선

- Projects/Features/HomeFeature/Project.swift
- Projects/Features/HomeFeature/Sources/Components/HomeComponent.swift
- Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
- Projects/Features/MainTabFeature/Sources/ViewControllers/MainTabBarViewController.swift
- Projects/Features/PlaylistFeature/Project.swift
- Projects/Features/PlaylistFeature/Sources/Components/MyPlaylistDetailComponent.swift
- Projects/Features/PlaylistFeature/Sources/Components/UnkwonPlaylistDetailComponent.swift
- Projects/Features/PlaylistFeature/Sources/Components/WakmusicPlaylistDetailComponent.swift
- Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
- Projects/Features/PlaylistFeature/Sources/ViewControllers/UnknownPlaylistDetailViewController.swift
- Projects/Features/PlaylistFeature/Sources/ViewControllers/WakmusicPlaylistDetailViewController.swift
- Projects/Features/SearchFeature/Project.swift
- Projects/Features/SearchFeature/Sources/After/Components/SongSearchResultComponent.swift
- Projects/Features/SearchFeature/Sources/After/ViewControllers/SongSearchResultViewController.swift
musicDetail 팩토리를 제거하고 songDetailPresenter에게 위임
Resolves: #1028
- 의존성 제거
- 코드 교체
>
>
> 🔀 :: (#1024) 뮤직 디테일 present 방식 변경

- Projects/App/Sources/Application/AppComponent+Songs.swift
- Projects/Domains/SongsDomain/Interface/DataSource/RemoteSongsDataSource.swift
- Projects/Domains/SongsDomain/Interface/Entity/NewSongsPlaylistEntity.swift
- Projects/Domains/SongsDomain/Interface/Repository/SongsRepository.swift
- Projects/Domains/SongsDomain/Interface/UseCase/FetchNewSongsPlaylistUseCase.swift
- Projects/Domains/SongsDomain/Sources/API/SongsAPI.swift
- Projects/Domains/SongsDomain/Sources/DataSource/RemoteSongsDataSourceImpl.swift
- Projects/Domains/SongsDomain/Sources/Repository/SongsRepositoryImpl.swift
- Projects/Domains/SongsDomain/Sources/ResponseDTO/NewSongsPlaylistResponseDTO.swift
- Projects/Domains/SongsDomain/Sources/UseCase/FetchNewSongsPlaylistUseCaseImpl.swift
- Projects/Features/HomeFeature/Sources/Components/NewSongsContentComponent.swift
- Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
- Projects/Features/HomeFeature/Sources/ViewModels/NewSongsContentViewModel.swift
- Projects/Modules/Utility/Sources/Extensions/Extension+UIViewController.swift
- 누락된 기능 추가
Resolves: #1020
- 최신음악 플레이 리스트 불러오는 usecase 추가
- 전체재생 기능 추가 (유튜브 이동)
- "전체" 탭만 데이터가 있음
> 🔀 :: (#1020) 최신음악:: 전체재생 기능 추가

- Projects/Features/BaseFeature/Sources/ViewControllers/ContainSongsViewController.swift
- Projects/Features/PlaylistFeature/Interface/PlaylistCoverOptionPopupFactory.swift
- Projects/Features/PlaylistFeature/Sources/Model/PlaylistCoverOptionModel.swift
- Projects/Features/PlaylistFeature/Sources/Reactors/MyPlaylistDetailReactor.swift
- Projects/Features/PlaylistFeature/Sources/Reactors/PlaylistCoverOptionPopupReactor.swift
- Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
- Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistCoverOptionViewController.swift
- Projects/Features/PlaylistFeature/Sources/Views/ThumbnailOptionTableViewCell.swift
- Projects/Features/StorageFeature/Sources/Reactors/ListStorageReactor.swift
- Projects/Modules/Localization/Resources/en.lproj/Localizable.strings
- Projects/Modules/Localization/Resources/ko.lproj/Localizable.strings
삭제시 남겨진 갯수가 아닌 삭제된 갯수를 보여줘야하는데 거꾸로 넣음
Resolves: #1016
Resolves: #1017
토스트 문구 수정 및 높이 적용
>
>
> 🔀 :: (#1016, 1017) 재생목록 토스트 메시지 오류 수정

- Projects/Features/StorageFeature/Sources/ViewControllers/StorageViewController.swift
- 보관함만 스와이프 백 제스쳐 기능이 없음
Resolves: #1041 
- 스와이프 백 제스쳐 추가
- (누락) scrollToTop() 호출
- 없는 이유가 있었다면 제보바래요.
>  🔀 :: (#1041) 스와이프 백 제스쳐 추가

- Projects/UsertInterfaces/DesignSystem/Sources/WMNavigationBarView.swift
- 네비 우측 버튼에 2버튼이 나오는 경우 사이 간격이 없음
Resolves: #1043 
- 간격추가(10)
- 네비바에 버튼 2개가 올라오는 경우가 딱 하나라 WM네비바를 사용하는 곳에서 영향은 없을듯,,
> 🔀 :: (#1043) 네비 우측 버튼 내 간격 추가

- Projects/Domains/BaseDomain/Sources/DataSource/BaseRemoteDataSource.swift
토큰 만료기간이 넘었는지만 체크하고 있어서 토큰이 없는 상태로 토큰 필요한 API에 요청을 보내면 리프레시 시도를 3번을 해요.
Resolves: #1001 
- 토큰 validation에 토큰 만료시간만이 아닌 액세스 토큰, 리프레시 토큰 여부도 확인해요
> 🔀 :: (#1001) 비로그인 상태에서 토큰이 필요한 api를 요청하면, 토큰을 재발급하려고 시도하는 문제

- Projects/Features/TeamFeature/Sources/Views/TeamInfoSectionView.swift
- 테이블이 갱신되면서 UI가 초기화 됨
Resolves: #1009 
- UI 초기화 문제 수정
x
> 🔀 :: (#1009) 팀 정보:: UI 초기화 되는 문제 수정

- Projects/Features/MyInfoFeature/Resources/Question.storyboard
- Projects/Features/MyInfoFeature/Sources/ViewControllers/Question/QuestionViewController.swift
- Projects/Features/MyInfoFeature/Sources/ViewModels/QuestionViewModel.swift
문의사항에 크레딧 정보 요청 추가
Resolves: #1061
뷰 추가
>
>
> 🔀 :: (#1061)  건의 사항 참여정보 항목 추가

- Projects/Domains/SongsDomain/Interface/Entity/SongCreditsEntity.swift
- Projects/Domains/SongsDomain/Sources/ResponseDTO/SongCreditsResponseDTO.swift
- Projects/Features/SongCreditFeature/Sources/Model/CreditModel.swift
- Projects/Features/SongCreditFeature/Sources/SongCreditReactor.swift
- Projects/Features/SongCreditFeature/Sources/SongCreditViewController.swift
아티스트 화면 진입을 위한 Credit API 변경사항 반영
Resolves: #1064
- 아티스트 화면 진입을 위한 Credit API 변경사항 반영
- 아티스트 선택될 때 아티스트로 화면 전환 시키는건 @KangTaeHoon 님이 이서서 해주실 예정이에요.
> 🔀 :: (#1064) Credit -> 아티스트 화면 진입을 위한 Credit API 변경사항 반영

- Projects/Features/FruitDrawFeature/Sources/ViewControllers/FruitDrawViewController.swift
- Projects/Features/FruitDrawFeature/Sources/ViewModels/FruitDrawViewModel.swift
- 열매뽑기:: 오늘 뽑기 완료 상태로 뽑기버튼을 누르면 토스트 추가
Resolves: #1072 
- 토스트 추가
x
> 🔀 :: (#1072) 열매뽑기:: 오늘 뽑기 완료 상태로 뽑기버튼을 누르면 토스트 추가

- Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricDecoratingViewController+Bind.swift
- 네트워크 실패 오류가 노출되는 현상
Resolves: #1076 
- 이미지 네트워크 오류 노출 제거
x
> 🔀 :: (#1076) 가사꾸미기:: 네트워크 실패 오류가 노출되는 현상

- Projects/Domains/FaqDomain/Sources/DataSource/RemoteFaqDataSourceImpl.swift
- Projects/Features/MyInfoFeature/Sources/ViewControllers/FAQ/FaqContentViewController.swift
- 자주묻는질문:: 카테고리가 전체만 노출되는 오류 수정
Resolves: #1074 
- responseDTO 변경
x
> 🔀 :: (#1074) 자주묻는질문:: 카테고리가 전체만 노출되는 오류 수정

- .github/workflows/CI.yml
- CI workflow 트리거 조건 변경
Resolves: #1087
- CI workflow 트리거 조건 변경
- .swift 파일이 변경될 시 CI 트리거
> 🔀 :: (#1087) CI workflow 트리거 조건 변경

- Projects/Features/CreditSongListFeature/Sources/CreditSongList/CreditSongListViewController.swift
Credit 노래 리스트 상단 Gradient 영역 조정
Resolves: #1083 
- Credit 노래 리스트 상단 Gradient 영역 조정
- 간단하게 view 계층 위치만 바꿔주었어요
> 🔀 :: (#1083) Credit 노래 리스트 상단 Gradient 영역 조정

- Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabItemReactor.swift
- 크레딧 로딩 인디케이터 동작 오류 이슈 해결
Resolves: #1082 
- 크레딧 로딩 인디케이터 동작 오류 이슈 해결
- 마지막 페이지에 도달했다는 flag를 정해주었어요.
> 🔀 :: (#1082) 크레딧 로딩 인디케이터 동작 오류 이슈 해결

- Projects/Features/MyInfoFeature/Sources/ViewModels/QuestionViewModel.swift
- 문의하기 참여정보 -> 참여 정보 텍스트 변경
Resolves: #1089
- 문의하기 참여정보 -> 참여 정보 텍스트 변경
> 🔀 :: (#1089) 문의하기 참여정보 -> 참여 정보 텍스트 변경

- Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricHighlightingViewController+Bind.swift
- Projects/Features/LyricHighlightingFeature/Sources/ViewModels/LyricHighlightingViewModel.swift
- Projects/Modules/Utility/Sources/Extensions/Extension+UIViewController.swift
- 토스트 테마가 다크, 라이트로 확장 됨
Resolves: #1095 
- 토스트 테마 확장(backgroundThema 파라미터 추가, 디폴트는 다크)
- 가사하이라이팅에 적용
x
> 🔀 :: (#1095) 토스트 테마 확장 

- Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
홈화면 Translucent 효과 추가
Resolves: #1085 
- 홈화면 Translucent 효과 추가
> 🔀 :: (#1085) 홈화면 Translucent 적용

- Projects/Features/PlaylistFeature/Sources/Reactors/MyPlaylistDetailReactor.swift
- Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
- 노티 송신 누락 
- 스로틀 미적용
Resolves: #1103
- 노티 송신
- 스로틀 적용
>
>
> 🔀 :: (#1103)  디폴트 이미지 변경 반영 및 플리 변경사항 저장 스로틀 적용

- Projects/Features/MusicDetailFeature/Sources/MusicDetail/Views/MusicControlView/MusicControlView.swift
- 노래 상세 페이지 제목 <-> 아티스트 간 텍스트 공백 추가
Resolves: #1110 
- 노래 상세 페이지 제목 <-> 아티스트 간 텍스트 공백 추가
> 🔀 :: (#1110) 노래 상세 페이지 제목 <-> 아티스트 간 텍스트 공백 추가

- .github/workflows/AutoCloseIssueByPullRequest.yml
…지 않는 이슈
AutoCloseIssueByPullRequest workflow가 실행되지 않음
Resolves: #1125
- [ x 이 작업으로 인해 변경이 필요한 문서가 변경되었나요? (e.g. `XCConfig`, `노션`, `README`)
> 🔀 :: (#1125) AutoCloseIssueByPullRequest workflow가 실행되지 않음

- README.md
-사람 하나 추가했어요
아 하고보니 이걸 릴리즈 브랜치에 하는게;
Resolves: #1127
> 🔀 :: (#1127) 리드미 수정

- Projects/Features/MyInfoFeature/Sources/Views/FruitDrawButtonView.swift
마이페이지 열매 버튼 배경색 변경
- white -> white.alpha(0.4)
Resolves: #1131
마이페이지 열매 버튼 배경색 변경
- white -> white.alpha(0.4)
> 🔀 :: (#1131) 마이페이지 열매 버튼 배경색 변경

- Projects/App/Sources/Application/AppComponent+Credit.swift
- Projects/Domains/CreditDomain/Interface/DataSource/RemoteCreditDataSource.swift
- Projects/Domains/CreditDomain/Interface/Repository/CreditRepository.swift
- Projects/Domains/CreditDomain/Interface/UseCase/FetchCreditProfileImageURLUseCase.swift
- Projects/Domains/CreditDomain/Sources/API/CreditAPI.swift
- Projects/Domains/CreditDomain/Sources/DataSource/RemoteCreditDataSourceImpl.swift
- Projects/Domains/CreditDomain/Sources/Repository/CreditRepositoryImpl.swift
- Projects/Domains/CreditDomain/Sources/ResponseDTO/FetchCreditProfileImageURLResponseDTO.swift
- Projects/Domains/CreditDomain/Sources/UseCase/FetchCreditProfileImageURLUseCaseImpl.swift
- Projects/Domains/CreditDomain/Testing/UseCase/FetchCreditProfileImageURLUseCaseSpy.swift
- Projects/Features/CreditSongListFeature/Demo/Sources/AppDelegate.swift
- Projects/Features/CreditSongListFeature/Sources/CreditSongList/Component/CreditSongListComponent.swift
- Projects/Features/CreditSongListFeature/Sources/CreditSongList/CreditSongListReactor.swift
- Projects/Features/CreditSongListFeature/Sources/CreditSongList/CreditSongListViewController.swift
- Projects/Features/CreditSongListFeature/Sources/CreditSongList/View/CreditProfileView.swift
- 크레딧 작업자의 프로필 이미지를 지원해요.
Resolves: #1135
> 🔀 :: (#1135) 크레딧 작업자 프로필 이미지 지원

- Projects/Features/MyInfoFeature/Sources/Views/FruitDrawButtonView.swift
- 마이페이지 내 열매 버튼 border color 변경
Resolves: #1137
- 마이페이지 내 열매 버튼 border color 변경
> 🔀 :: (#1137) 마이페이지 내 열매 버튼 border color 변경

- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
- Projects/Features/ChartFeature/Sources/Analytics/ChartAnalyticsLog.swift
- Projects/Features/ChartFeature/Sources/ViewContrillers/ChartContentViewController.swift
- Projects/Features/ChartFeature/Sources/ViewContrillers/ChartViewController.swift
- Projects/Features/CreditSongListFeature/Sources/CreditSongList/CreditSongListViewController.swift
- Projects/Features/HomeFeature/Sources/Analytics/HomeAnalyticsLog.swift
- Projects/Features/HomeFeature/Sources/Analytics/NewSongsAnalyticsLog.swift
- Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
- Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
- Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsViewController.swift
- Projects/Features/MainTabFeature/Sources/Analytics/MainTabAnalyticsLog.swift
- Projects/Features/MainTabFeature/Sources/ViewControllers/BottomTabBarViewController.swift
- Projects/Features/MainTabFeature/Sources/ViewControllers/MainContainerViewController.swift
- Projects/Features/MainTabFeature/Sources/Views/TabItemView.swift
- Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailReactor.swift
- Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
- Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistViewController+Delegate.swift
- Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistViewController.swift
- Projects/Features/PlaylistFeature/Sources/ViewControllers/UnknownPlaylistDetailViewController.swift
- Projects/Features/PlaylistFeature/Sources/ViewControllers/WakmusicPlaylistDetailViewController.swift
- Projects/Features/SearchFeature/Sources/After/ViewControllers/AfterSearchViewController.swift
- Projects/Features/SearchFeature/Sources/After/ViewControllers/ListSearchResultViewController.swift
- Projects/Features/SearchFeature/Sources/After/ViewControllers/SongSearchResultViewController.swift
- Projects/Features/SearchFeature/Sources/Before/ViewControllers/BeforeSearchContentViewController.swift
- Projects/Features/SearchFeature/Sources/Root/ViewControllers/SearchViewController.swift
- Projects/Features/SongCreditFeature/Sources/Analytics/SongCreditAnalyticsLog.swift
- Projects/Features/SongCreditFeature/Sources/SongCreditReactor.swift
- Projects/Features/SongCreditFeature/Sources/SongCreditViewController.swift
- Projects/Modules/LogManager/Sources/CommonAnalyticsLog.swift
- 홈, 검색, 아티스트 탭 로그 수집
Resolves: #1140
- 홈, 검색, 아티스트 탭 로그 수집
> 🔀 :: (#1140) 홈, 검색, 아티스트 탭 로그 수집

- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistViewController.swift
- 아티스트 선택이 안되는 이슈
Resolves: #1156
- 아티스트 선택이 안되는 이슈
- delegate를 사용하지 않고 didScroll 이친구도 같이 controlEvent를 옵저빙해요
> 🔀 :: (#1156) 아티스트 선택이 안됨

- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistViewController.swift
- 아티스트 선택이 안됨 2t
Resolves: #1158 
- 델리게이트 채택 제거
x
> 🔀 :: (#1158) 아티스트 선택이 안됨 2t

- Projects/Domains/ChartDomain/Sources/ResponseDTO/FetchChartRankingResponseDTO.swift
- 차트 업데이트 시간 오류
Resolves: #1160 
- 밀리세컨즈 단위 반영
x
> 🔀 :: (#1160) 차트 업데이트 시간 오류 수정

- Projects/Features/ArtistFeature/Resources/Artist.storyboard
- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistViewController.swift
- QA 혼란
Resolves: #1168 
- 이스터에그 위치 변경
x
> 🔀 :: (#1168) 푸시발송 이스터에그 위치 변경

- Package.swift
- Plugin/ConfigurationPlugin/ProjectDescriptionHelpers/Configuration+Ext.swift
- Projects/App/Project.swift
- Projects/App/Sources/Application/AppDelegate.swift
- Projects/Domains/BaseDomain/Sources/DataSource/BaseRemoteDataSource.swift
- Projects/Domains/BaseDomain/Sources/Logging/CustomLoggingPlugin.swift
- Projects/Domains/BaseDomain/Sources/WMAPI/SecretURL.swift
- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistViewController.swift
- Projects/Features/MyInfoFeature/Sources/ViewControllers/Request/RequestViewController.swift
- Projects/Modules/LogManager/Sources/AnalyticsLogManager.swift
- Projects/Modules/LogManager/Sources/LogHistory/LogHistoryCell.swift
- Projects/Modules/LogManager/Sources/LogHistory/LogHistorySectionItem.swift
- Projects/Modules/LogManager/Sources/LogHistory/LogHistoryStorage.swift
- Projects/Modules/LogManager/Sources/LogHistory/LogHistoryViewController.swift
- Projects/Modules/Utility/Sources/Extensions/Extension+UIViewController.swift
- Projects/Modules/Utility/Sources/Utils/Utils.swift
QA Configuration 추가
- Log 찍을때 QA 환경에서는 찍히고 DEBUG환경에서는 안찍히는정도의 별거 없는 차이에요
Resolves: #1171
QA Configuration 추가
> 🔀 :: (#1171) QA Configuration 추가

- Projects/Features/MainTabFeature/Resources/Main.storyboard
- Projects/Features/MainTabFeature/Sources/ViewControllers/MainTabBarViewController.swift
- Projects/Features/MainTabFeature/Sources/ViewControllers/NoticePopupViewController.swift
- 공지팝업이 다이어트를 함
Resolves: #1176 
- size(fit:)으로 변경
- 폰트 수정
- 레이아웃 살짝 수정
- 이게 정답은 아닌데... 해답임..
> 🔀 :: (#1176) 공지팝업 홀쭉해진 오류 수정

- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
- Projects/Features/ChartFeature/Sources/ViewContrillers/ChartContentViewController.swift
- Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
- Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
- Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
- Projects/Features/PlaylistFeature/Sources/ViewControllers/UnknownPlaylistDetailViewController.swift
- Projects/Features/PlaylistFeature/Sources/ViewControllers/WakmusicPlaylistDetailViewController.swift
- Projects/Features/SearchFeature/Sources/After/ViewControllers/SongSearchResultViewController.swift
- Projects/Features/StorageFeature/Sources/ViewControllers/LikeStorageViewController.swift
- https://discord.com/channels/979764222424657930/1273530647251521537
- 노래 상세로 진입 시 재생목록에 추가
Resolves: #1172
- 노래 상세로 진입 시 재생목록에 추가
> 🔀 :: (#1172) 노래 상세로 진입 시 재생목록에 추가

- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
- Projects/Features/BaseFeature/Sources/Etc/PlayState/PlayState+Playlist.swift
- Projects/Features/BaseFeature/Sources/Etc/PlayState/PlayState.swift
- Projects/Features/ChartFeature/Sources/ViewContrillers/ChartContentViewController.swift
- Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabItemReactor.swift
- Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
- Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistViewController+Delegate.swift
- Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistViewController.swift
- Projects/Features/PlaylistFeature/Sources/Views/RandomPlayButton.swift
- Projects/Features/PlaylistFeature/Sources/Views/RandomPlayButtonGroupView.swift
- Projects/Features/PlaylistFeature/Sources/Views/RandomPlayButtonHeaderView.swift
- Projects/Features/StorageFeature/Sources/Reactors/LikeStorageReactor.swift
- Projects/Features/StorageFeature/Sources/Reactors/ListStorageReactor.swift
- https://discord.com/channels/979764222424657930/1273530647251521537
- 재생목록 최대 제한 해제
Resolves: #1173 
- 재생목록 최대 제한 해제
> 🔀 :: (#1173) 재생목록 최대 제한 해제

- Projects/Features/HomeFeature/Sources/Analytics/HomeAnalyticsLog.swift
- Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
- 홈화면 로그 수정 반영
Resolves: #1166
- 홈화면 로그 수정 반영
> 🔀 :: (#1166) 홈화면 로그 수정 반영

- Projects/Features/MyInfoFeature/Sources/Analytics/MyInfoAnalyticsLog.swift
- Projects/Features/MyInfoFeature/Sources/Analytics/SettingAnalyticsLog.swift
- Projects/Features/MyInfoFeature/Sources/ViewControllers/MyInfo/MyInfoViewController.swift
- Projects/Features/MyInfoFeature/Sources/ViewControllers/Setting/SettingViewController.swift
- Projects/Modules/LogManager/Sources/CommonAnalyticsLog.swift
로그를 심어요
Resolves: #1149
로그를 심었어요
로그 목록들은 노션 애널리틱스 페이지 맨 아래에 있습니다
> 🔀 :: (#1149) 내 정보, 설정화면 애널리틱스 로그 심기

- Projects/Features/SearchFeature/Sources/After/View/ListResultCell.swift
- Projects/Modules/Utility/Sources/Extensions/Extension+Int.swift
- Projects/Modules/Utility/Sources/Extensions/Extension+String.swift
디자인 변경 요청
Resolves: #1180
- , 익스텐션
- unit 변경
> 🔀 :: (#1180) 리스트 검색결과 단위 회 -> 구독 변경

- Projects/Domains/SearchDomain/Interface/Enum/Option.swift
- Projects/Features/SearchFeature/Sources/After/Reactors/SongSearchResultReactor.swift
- Projects/Features/SearchFeature/Sources/After/ViewControllers/SearchSortOptionViewController.swift
> 🔀 :: (#1118) 정렬 옵션 변경 , 가나다순 -> 관련도순

- Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
- 앱 시작과 동시에 홈 탭을 광클하면 크래쉬
Resolves: #1146 
- 옵셔널 바인딩 처리
x
> 🔀 :: (#1146) 홈 탭 광클시 크래쉬 현상 수정

- Projects/Features/BaseFeature/Interface/Enum/PurposeType.swift
- Projects/Features/BaseFeature/Sources/ViewControllers/MultiPurposePopupViewController.swift
- 이름 제한 12자 + 영문자는 2글자당 1문자로 판정
Resolves: #1185
- 이름 제한 12자 + 영문자는 2글자당 1문자로 판정
https://github.com/user-attachments/assets/c3f945c8-6d5a-4b37-b833-c3938e588b6b
> 🔀 :: (#1185) 이름 제한 12자 + 영문자는 2글자당 1문자로 판정

- Projects/App/Sources/Application/AppComponent+Playlist.swift
- Projects/Domains/PlaylistDomain/Interface/DataSource/RemotePlaylistDataSource.swift
- Projects/Domains/PlaylistDomain/Interface/Entity/WMPlaylistDetailEntity.swift
- Projects/Domains/PlaylistDomain/Interface/Repository/PlaylistRepository.swift
- Projects/Domains/PlaylistDomain/Interface/UseCase/FetchWMPlaylistDetailUseCase.swift
- Projects/Domains/PlaylistDomain/Interface/UseCase/FetchWmPlaylistDetailUseCase.swift
- Projects/Domains/PlaylistDomain/Sources/API/PlaylistAPI.swift
- Projects/Domains/PlaylistDomain/Sources/DataSource/RemotePlaylistDataSourceImpl.swift
- Projects/Domains/PlaylistDomain/Sources/Repository/PlaylistRepositoryImpl.swift
- Projects/Domains/PlaylistDomain/Sources/ResponseDTO/WmPlaylistDetailResponseDTO.swift
- Projects/Domains/PlaylistDomain/Sources/UseCase/FetchWMPlaylistDetailUseCaseImpl.swift
- Projects/Features/PlaylistFeature/Interface/PlaylistDetailNavigator.swift
- Projects/Features/PlaylistFeature/Sources/Components/WakmusicPlaylistDetailComponent.swift
- Projects/Features/PlaylistFeature/Sources/Reactors/WakmusicPlaylistDetailReactor.swift
- Projects/Features/SearchFeature/Sources/Before/ViewControllers/BeforeSearchContentViewController.swift
급하게 작업하느라 가이드라인을 깜빡해서 재 작업 합니다.
Resolves: #1207
Wm prefix -> WM로 변경
> 🔀 :: (#1207)  Wm 네이밍 -> WM로 변경

- Projects/Features/CreditSongListFeature/Demo/Sources/AppDelegate.swift
- Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/Component/CreditSongListTabItemComponent.swift
- Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabItemReactor.swift
- Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabItemViewController.swift
- Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabViewController.swift
- Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/View/CreditSongCollectionViewCell.swift
- Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/View/RandomPlayButton.swift
Credit 작업자 노래 리스트 구현 중 누락, 잘못되었던 스펙을 반영했어요.
Resolves: #1204
Credit 작업자 노래 리스트 구현 중 누락, 잘못되었던 스펙을 반영했어요.
- 랜덤 재생 아이콘 크기 증가
- 탭바의 바가 구분선을 덮게 변경
- 노래의 썸네일 클릭 시 해당 노래 상세 노출
> 🔀:: (#1204) Credit 작업자 노래 리스트 누락 스펙 반영

- Projects/Features/LyricHighlightingFeature/Sources/ViewModels/LyricHighlightingViewModel.swift
- 가사 하이라이팅 총 라인 계산 기준 수정
Resolves: #1216 
- 가사 하이라이팅 총 라인 계산 기준 수정
> 🔀:: (#1216) 가사 하이라이팅 총 라인 계산 기준 수정 

- .github/actions/Auto_close_associate_issue/main.js
- .github/workflows/AutoCloseIssueByPullRequest.yml
Auto Issue Closer가 트리거되지 않는 현상 해결
https://github.com/baekteun/github-action-workflow-test/actions
레포에서 실험했을 땐 설마 여기서는 안되지는 않겠죠?
Resolves: #1218
Auto Issue Closer가 트리거되지 않는 현상 해결
> 🔀 :: (#1218) Issue Auto Closer trigger가 안되는 현상 해결

- Projects/Domains/ArtistDomain/Sources/ResponseDTO/ArtistDetailResponseDTO.swift
- Projects/Domains/ArtistDomain/Sources/ResponseDTO/ArtistListResponseDTO.swift
- Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistDetailHeaderViewController.swift
- 숏네임을 사용해서 변경함.
Resolves: #1225 
- 숏네임 > 풀네임 
- 변수명 살짝 수정
x
> 🔀 :: (#1225) 아티스트 숏네임 사용 오류 수정

- Projects/Features/SongCreditFeature/Sources/View/CreditCollectionView/CreditCollectionViewCell.swift
작업자 이름이 길어질 때를 위한 최대 width 지정
collectionView width의 대충 2/3 만큼을 최대 width로 지정
Resolves: #1223
작업자 이름이 길어질 때를 위한 최대 width 지정
> 🔀 :: (#1223) 작업자 이름이 길어질 때를 위한 최대 width

- Projects/Features/BaseFeature/Sources/Etc/PlayState/PlayState+Playlist.swift
- Projects/Features/BaseFeature/Sources/Etc/PlayState/PlayState.swift
- Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabItemReactor.swift
- Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabItemViewController.swift
- Projects/Features/MainTabFeature/Sources/Components/MainTabBarComponent.swift
- Projects/Features/MainTabFeature/Sources/ViewControllers/MainTabBarViewController.swift
- Projects/Features/MainTabFeature/Sources/ViewModels/MainTabBarViewModel.swift
- Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailView.swift
- Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailViewController.swift
- Projects/Features/MusicDetailFeature/Sources/MusicDetail/Views/ThumbnailCollectionView/ThumbnailCell.swift
크레딧 작업자 노래 리스트에서 썸네일 클릭 시 재생목록의 첫 곡으로 이동되는 이슈 해결
Resolves: #1231
- 크레딧 작업자 노래 리스트에서 썸네일 클릭 시 재생목록의 첫 곡으로 이동되는 이슈 해결
- 푸시알림에서 노래 상세 진입 시 재생목록의 첫 곡으로 이동되는 이슈 해결
- 노래 상세가 노출되는 중에 재생목록 첫번째 곡 이미지가 보였다가 로드되면 바뀌는 이슈 해결
> 🔀 :: (#1231) 크레딧 작업자 노래 리스트에서 썸네일 클릭 시 재생목록의 첫 곡으로 이동되는 이슈 해결

- Projects/Modules/Utility/Sources/Player/WakmusicYoutubePlayer.swift
- Projects/Modules/Utility/Sources/Youtube/YoutubeURLGenerator.swift
재생 플랫폼에 유튜브 뮤직 지원
- 재생 플랫폼에 유튜브 뮤직 지원
Resolves: #1200
- 재생 플랫폼에 유튜브 뮤직 지원
PreferenseManager를 Player가 참조하는게 살짝 좀 마음에 걸리지만 큰 문제는 없다고 판단해서 우선 진행했어요.
> 🔀 :: (#1200) 재생 플랫폼에 유튜브 뮤직 지원

- Projects/UsertInterfaces/DesignSystem/Sources/SingleActionButtonView.swift
- 최신음악 , 왁뮤 추천 플리 헤더 버튼 블러 적용 요청
Resolves: #1245 
visual Effect View regular로 적용
> 🔀 :: (#1245) SingleAction 버튼 Blur 적용

- Projects/App/Sources/Application/SceneDelegate.swift
- Projects/Modules/Utility/Sources/DeepLink/DeepLinkGenerator.swift
- Projects/Modules/Utility/Sources/Utils/Secrets.swift
- 딥링크 도메인 분기처리
Resolves: #1263 
- DEBUG | QA 는 테스트 도메인, 릴리즈는 실 도메인
x
> 🔀 :: (#1263) 딥링크 도메인 분기처리

- Projects/Features/PlaylistFeature/Sources/Views/MyPlaylistHeaderView.swift
- Projects/Features/PlaylistFeature/Sources/Views/UnknownPlaylistHeaderView.swift
- Projects/Features/PlaylistFeature/Sources/Views/WakmusicPlaylistHeaderView.swift
닉네임이 또는 플리 이름이 길어 짤리는 현상 발생
Resolves: #1257
스크롤 뷰 도입
> 🔀 :: (#1257)  플레이리스트 상세 글자 넘침 버그 해결

- Projects/Features/MyInfoFeature/Sources/ViewControllers/PlayTypeTogglePopup/PlayTypeTogglePopupViewController.swift
- Projects/Features/MyInfoFeature/Sources/Views/PlayTypeTogglePopupItemButton.swift
UI가 변경되었어요!
Resolves: #1268
- 그림자 추가
- 디스크립션 간격 수정
- 강조 색상 변경
- 체크박스 이미지로 변경
| 화면 | gif |
|--------|--------|
| ![Simulator Screenshot - iPhone 15 Pro - 2024-08-31 at 18 12 12](https://github.com/user-attachments/assets/91ceb77a-fadb-48f9-9220-21310f4fb9e5) | <img src="https://github.com/user-attachments/assets/161c883d-5775-43a4-8db4-5be0001ac316" width="100%"> |
> 🔀 :: (#1268) 재생 방식 토글 버튼 UI 수정

- Projects/Modules/Utility/Sources/API/WMImageAPI.swift
- WMImageAPI 미사용 코드 제거
Resolves: #1269 
- 유튜브 제외하고 모두 제거
x
> 🔀 :: (#1269) WMImageAPI 미사용 코드 제거

- Projects/Features/PlaylistFeature/Sources/Views/RandomPlayButtonGroupView.swift
- Projects/Features/PlaylistFeature/Sources/Views/RandomPlayButtonHeaderView.swift
- 재생목록 화면에 랜덤 아이콘 크기가 작음
Resolves: #1275 
- 크기 변경 (24 > 32)
x
> 🔀 :: (#1275) 재생목록 > 랜덤 아이콘 크기 변경

- Projects/Domains/BaseDomain/Sources/DataSource/BaseRemoteDataSource.swift
- 커스텀 플러그인이 DEBUG, QA 전처리라 릴리즈 타겟에서 빌드 에러가 발생함
Resolves: #1279 
- 커스텀 플러그인 사용하는 부분 분기처리
x
> 🔀 :: (#1279) Release 타겟 빌드 에러 수정

- README.md
> README 깨짐현상 해결

- Projects/Modules/LogManager/Sources/AnalyticsLogManager.swift
- 로그 누락
Resolves: #1297
- 타겟 조건문 수정
x
> 🔀 :: (#1297) 애널리틱스 로그 누락

- Projects/Features/BaseFeature/Sources/Etc/PlayState/PlayState.swift
- Projects/Features/BaseFeature/Sources/Etc/PlayState/PlaylistItem.swift
- Projects/Features/PlaylistFeature/Sources/Reactors/MyPlaylistDetailReactor.swift
- Projects/Features/PlaylistFeature/Sources/Reactors/UnknownPlaylistDetailReactor.swift
- Projects/Features/SearchFeature/Sources/After/ViewControllers/ListSearchResultViewController.swift
- Projects/Features/SearchFeature/Sources/Before/ViewControllers/BeforeSearchContentViewController.swift
- Projects/Modules/Utility/Sources/Extensions/Extension+Sequence.swift
- Projects/Modules/Utility/Sources/Utils/UniquedSequence.swift
플레이리스트의 중복곡 처리
Resolves: 1296
플레이리스트의 중복곡 처리
> 🔀 :: (#1296) 플레이리스트의 중복곡 처리

- Projects/Features/BaseFeature/Sources/Etc/PlayState/PlayState+Playlist.swift
중복된 곡을 삭제할 때 Crash나는 이슈 해결
Resolves: #1296
중복된 곡을 삭제할 때(중복된 곡이 선택된 채로 재생할때) Crash나는 이슈 해결
> 🔀 :: (#1296) 중복된 곡을 삭제할 때 Crash나는 이슈 해결

- Projects/Domains/BaseDomain/Sources/BasePlugin/BasePlugin.swift
따로 처리하기 어려운 상태라 그냥 아예 통신할때 예외 처리도록 유도했어요
Resolves: #1299
> 🔀 :: (#1299) 빈토큰 미전송

- Plugin/EnvironmentPlugin/ProjectDescriptionHelpers/ProjectEnvironment.swift
> 🔀 ::  버전업 3.0.2

- Projects/Modules/Utility/Sources/Utils/Devices.swift
iPhone 16 model 추가
Resolves: #1303
iPhone 16 model 추가
> 🔀 :: (#1303) iPhone 16 model 추가

- .github/workflows/CI.yml
GitHub Action runner Xcode 버전 업그레이드
Resolves: #1312
GitHub Action runner Xcode 버전 업그레이드
> 🔀 :: (#1312) GitHub Action runner Xcode 버전 업그레이드

- Projects/Features/MyInfoFeature/Sources/ViewControllers/OpenSourceLicense/OpenSourceLicenseViewController.swift
- Projects/Features/MyInfoFeature/Sources/ViewModels/OpenSourceLicenseViewModel.swift
오픈 소스 라이센스 ViewModel에서 binding을 하지 않았음
Resolves: #1328
오픈 소스 라이센스 ViewModel binding
> 🔀 :: (#1328) 오픈소스 라이센스 페이지 데이터가 노출되지 않음

- Cartfile
- Cartfile.resolved
Xcode 16.2 호환 Realm 버전 업
Resolves: #1333 
- cartfile 변경 (20.0.0 > 20.0.1)
x
> 🔀 :: (#1333) Xcode 16.2 호환 Realm 버전 업

- .github/workflows/CI.yml
CI runner 버전 업그레이드
Resolves: #1337
CI runner 버전 업그레이드
> 🔀 :: (#1337) CI runner 버전 업그레이드

- Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailReactor.swift
MusicDetailView crash 이슈 해결
Resolves: #1335
- MusicDetailView crash 이슈 해결
- songIDs가 중복으로 들어와버려서 중복 제거 전 index와 후의 index가 달라서 생긴 문제
> 🔀 :: (#1335) MusicDetailView crash 이슈 해결
