Projects/App/Sources/Application/AppComponent+Auth.swift
Projects/App/Sources/Application/NeedleGenerated.swift
Projects/Features/MainTabFeature/Sources/Components/MainTabBarComponent.swift
Projects/Features/MainTabFeature/Sources/ViewControllers/MainTabBarViewController.swift
Projects/Features/SignInFeature/Sources/Components/SignInComponent.swift
Projects/Features/SignInFeature/Sources/ViewControllers/LoginViewController.swift
Projects/Features/SignInFeature/Sources/ViewModels/LoginViewModel.swift
Projects/Features/StorageFeature/Sources/Components/StorageComponent.swift
Projects/Features/StorageFeature/Sources/ViewControllers/StorageViewController.swift
Projects/Services/APIKit/Sources/API/AuthAPI.swift
Projects/Services/APIKit/Sources/API/WMAPI.swift
Projects/Services/DataMappingModule/Sources/Auth/Response/AuthLoginResponseDTO.swift
Projects/Services/DataMappingModule/Sources/Auth/Response/NaverUserInfoResponseDTO.swift
Projects/Services/DataMappingModule/Sources/Base/ProviderType.swift
Projects/Services/DataModule/Sources/Auth/Repositories/AuthRepositoryImpl.swift
Projects/Services/DataModule/Sources/Auth/UseCases/FetchNaverUserInfoUseCaseImpl.swift
Projects/Services/DataModule/Sources/Auth/UseCases/FetchTokenUseCaseImpl.swift
Projects/Services/DomainModule/Sources/Auth/Entitiy/AuthLoginEntity.swift
Projects/Services/DomainModule/Sources/Auth/Entitiy/NaverUserInfoEntity.swift
Projects/Services/DomainModule/Sources/Auth/Repository/AuthRepository.swift
Projects/Services/DomainModule/Sources/Auth/UseCases/FetchNaverUserInfoUseCase.swift
Projects/Services/DomainModule/Sources/Auth/UseCases/FetchTokenUseCase.swift
Projects/Services/NetworkModule/Sources/Auth/DataTransfer/FetchNaverUserInfoTransfer.swift
Projects/Services/NetworkModule/Sources/Auth/DataTransfer/FetchTokenTransfer.swift
Projects/Services/NetworkModule/Sources/Auth/Remote/RemoteAuthDataSource.swift
Projects/Services/NetworkModule/Sources/Auth/Remote/RemoteAuthDataSourceImpl.swift

- LoginVC에 있던 로그인 코드를 뷰모델로 옮겨 MVVM 패턴을 구체적으로 적용
- 각 로그인을통한 id를 왁뮤서버로 보내 토큰을 받아옴

:twisted_rightwards_arrows: 네이버 로그인 및 애플로그인을 통한 왁뮤 서버 토큰 받아오기

---

Projects/Features/PlayerFeature/Resources/YoutubePlayer.html
Projects/Features/PlayerFeature/Resources/YoutubePlayerHTML.swift
Projects/Features/PlayerFeature/Sources/PlayState.swift
Projects/Features/PlayerFeature/Sources/ViewControllers/PlayerViewController.swift
Projects/Features/PlayerFeature/Sources/ViewModels/PlayerViewModel.swift

라이브러리 변경 및 combine 임포트 문제로 팀원들이 주석처리하여 사용중이었습니다.
코드수정을 통해 불필요한 주석처리를 피하고자 했습니다.
PlayState 싱글톤 객체를 만듭니다.
PlayState 는 public 으로 앱 전체에서 접근이 가능하도록 하며, 멤버 변수마다 접근제어자를 다르게 두어 몇몇 멤버에 한해선 접근이 불가능하도록 합니다.
(앱 전체 <-> PlayState <-> Player  와 같은 형태로 구상중입니다.)
재생/일시정지, 이전곡, 다음곡 기능을 추가합니다.
Closes #15

🔀 PlayState 를 만들어 Player 와 PlayerVC 를 분리합니다.

---

Projects/App/Support/Info.plist
Projects/Features/BaseFeature/Sources/RequestPermissionable.swift

(카메라/앨범) 권한 승인 프로토콜 정의
현재는 버그제보에서 밖에 쓸 일이 없지만, 매번 해당 화면에서 권한을 요청하는 코드가 들어가지 않게
프로토콜로 정의하여 사용하도록합니다.
Closes #이슈번호

🔀 :: (카메라/앨범) 권한 승인 프로토콜 정의

---

Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistViewController.swift
Projects/Features/CommonFeature/Sources/PlayState/PlayState+Playlist.swift
Projects/Features/CommonFeature/Sources/PlayState/PlayState+Public.swift
Projects/Features/CommonFeature/Sources/PlayState/PlayState+YoutubePlayer.swift
Projects/Features/CommonFeature/Sources/PlayState/PlayState.swift
Projects/Features/CommonFeature/Sources/ViewControllers/PlayListDetailViewController.swift
Projects/Features/CommonFeature/Tests/TargetTests.swift
Projects/Features/PlayerFeature/Sources/ViewControllers/PlaylistViewController+Delegate.swift
Projects/Features/PlayerFeature/Sources/ViewControllers/PlaylistViewController.swift
Projects/Features/PlayerFeature/Sources/ViewModels/PlayerViewModel+API.swift
Projects/Features/PlayerFeature/Sources/ViewModels/PlayerViewModel.swift
Projects/Features/PlayerFeature/Sources/ViewModels/PlaylistViewModel.swift
Projects/Features/PlayerFeature/Sources/Views/PlaylistTableViewCell.swift
Projects/Features/PlayerFeature/Sources/Views/PlaylistView.swift
Projects/Modules/Utility/Sources/Extensions/Extension+Collection.swift
Projects/Modules/Utility/Sources/Extensions/Extension+UILabel.swift

기존에 설계한 방식은 DataSource가 최초 생성될 때 원본 PlayList 에서 pull 해오고, 사용자 동작에 따라 DataSource를 변경시키고 DataSource에 변경사항이 생길때마다 원본 PlayList로 push 하는 구조로 설계했었습니다. 
하지만 forward, backward, 선택, 순서변경 등등 모든 메소드가 PlayList에 구현되어있던 상태이고 저 구조를 적용하려면 PlayList에 있는 메소드들을 전부 뷰모델로 끌어내려야 하는 상황이었습니다. 
그래서 구조에 대한 고민끝에 뷰모델은 PlayList를 변경시키고, DataSource는 원본 PlayList의 변경사항을 구독하는 방식으로 수정하기로했습니다.
DataSource는 PlayList를 관찰하고 변경사항이 생기면 계속 pull 하는 구조로 변경하였습니다.
CurrentPlayIndex를 수동으로 관리하는게 위험하다고 생각되어 PlayListItem의 isPlaying 변수를 두고 isPlaying을 추적하는 구조로 변경하였습니다.
Closes #195, #202, #207

🔀  :: PlayList 리팩토링 및 DataSource, PlayList 간의 구조 변경, 각종 버그 수정

---

Projects/App/Sources/Application/NeedleGenerated.swift
Projects/Features/CommonFeature/Sources/PlayState/PlayState+Public.swift
Projects/Features/CommonFeature/Sources/PlayState/PlayState+YoutubePlayer.swift
Projects/Features/PlayerFeature/Sources/Components/PlayerComponent.swift
Projects/Features/PlayerFeature/Sources/ViewControllers/PlayerViewController.swift
Projects/Features/PlayerFeature/Sources/ViewControllers/PlaylistViewController.swift
Projects/Features/PlayerFeature/Sources/ViewModels/PlayerViewModel.swift

- 플레이어 화면에서 곡담기 기능 연결
- 재생중인 곡 변경되면 "가사를 불러오는 중입니다." 문구 추가
```Swift
YoutubePlayer.stop() // playbackState 가 .cued로 들어가서 play()를 했을때 cue에 들어있던 source가 재생됨
YoutubePlayer.cue(source: .video(id: "")) // 이 코드 추가로 큐에 빈 source를 추가시키고 playbackState를 .unstarted 로 변경시킴
```
재생중인 곡이 변경되면, 플레이어가 새로 load 되면서 재생시간을 불러오는 작업과 가사를 요청하는 두개의 네트워크 작업이 있음
플레이어는 플레이어의 재생시간 변화를 구독해 하이라이팅과 센터스크롤을 하는데,
가사가 도착하기 전에 플레이어가 먼저 load 되고 재생시간이 불러와지면 아래 코드에서 에러가 나는 문제였음
가사가 존재할때만 sink문을 타도록 compactMap에서 가사존재여부 검사
```Swift
playerView.lyricsTableView.scrollToRow(at: IndexPath(row: index, section: 0), at: .middle, animated: true)
```
closes #174, #208

🔀 :: 플레이어관련 각종 오류 해결

---

Projects/Features/CommonFeature/Sources/PlayState/PlayState+Playlist.swift
Projects/Features/CommonFeature/Sources/PlayState/PlayState.swift
Projects/Features/PlayerFeature/Sources/ViewModels/PlaylistViewModel.swift

**미니플레이어가 안올라오는 문제** #236
```Swift
player = YouTubePlayer(configuration: .init(autoPlay: false, showControls: false, showRelatedVideos: false))
```
PlayState init 에서 YoutubePlayer를 위 코드처럼 초기화해주고있는데 언뜻보면 source가 nil이니까 .unstarted 일 것같지만 .cued로 변경되고 있었습니다.
```Swift
player.cue(source: .video(id: ""))
```
그래서 source에 빈 문자열을 id로 넘겨주면 .unstarted로 변경된다는 점을 이용해 PlayState init시 .unstarted 상태가 유지되도록 했습니다.
**재생이 안되던 문제**
확인해보니 realmDB에서 플레이리스트는 불러왔지만 YoutubePlayer에 cue가 되지않아 재생버튼을 눌러도 동작하지 않는 문제였습니다.
```Swift
player.cue(source: .video(id: currentSong?.id ?? ""))
```
realmDB에서 불러온 곡이 있으면 cue에 넣고, 없으면 id로 빈문자열을 넘겨 .unstarted 상태를 유지하도록 했습니다. 
Closes #236

🔀 :: 미니플레이어가 안올라오는 문제 및 재생이 안되던 문제 수정

---

Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistViewController.swift
Projects/Features/CommonFeature/Resources/CommonUI.storyboard
Projects/Features/CommonFeature/Sources/PlayState/PlayState+Playlist.swift
Projects/Features/CommonFeature/Sources/PlayState/PlayState.swift
Projects/Features/CommonFeature/Sources/ViewControllers/ContainSongsViewController.swift
Projects/Features/CommonFeature/Sources/ViewControllers/PlayListDetailViewController.swift
Projects/Features/CommonFeature/Sources/ViewModels/ContainSongsViewModel.swift
Projects/Features/CommonFeature/Sources/Views/ContainPlayListHeaderView.swift
Projects/Features/CommonFeature/Sources/Views/CurrentPlayListTableViewCell.swift
Projects/Features/PlayerFeature/Sources/ViewControllers/PlayerViewController.swift
Projects/Features/PlayerFeature/Sources/ViewControllers/PlaylistViewController+Delegate.swift
Projects/Features/PlayerFeature/Sources/ViewControllers/PlaylistViewController.swift
Projects/Features/PlayerFeature/Sources/ViewModels/PlaylistViewModel.swift
Projects/Features/PlayerFeature/Sources/Views/LyricsTabelViewCell.swift
Projects/Features/PlayerFeature/Sources/Views/PlayerView.swift

재생 목록 > 편집 완료 시점에서 DB 업데이트 하도록 변경
@youn9k 
//Comment  << 로 검색하여 프로젝트 내 주석 확인해주세요.
1. 리스트에서 순서를 변경하면 reorderPlaylist()가 호출되고, 그 안에서 listReordered.send(list) 로직이 호출되고 DB 업데이트가 이뤄졌는데 이 로직은 일단 제거합니다.
단, DB 업데이트가 안들어갈뿐 PlayState 싱글톤이 가지고 있는 list는 변경됩니다. 그래서 재생목록 화면에 머무르는 동안은 리스트 자체는 변경이 된 것 처럼 보입니다.
2. 이러면 PlayState.shared.playList.list와 DB에 저장된 리스트가 일치하지 않습니다. 
그래서 재생목록 화면에 진입하는 시점에서 DB 재생목록 리스트를 가져와서 PlayState.shared.playList.list와 동기화 시킵니다. 
3. 편집모드가 완료 된 시점에서 list를 가져와서 listReordered.send > DB 업데이트 하도록 변경합니다.
4. 그러면 순번을 변경하고 편집 완료를 누르지않고 나가 버린다음에, 재생 화면(풀 스크린)에서 다음곡을 누르면 순번이 꼬이지 않을까?
Publishers.Merge4(
playList.listAppended.dropFirst(),
playList.listRemoved.dropFirst(),
playList.listReordered.dropFirst(),
playList.currentSongChanged.dropFirst()
)
여기 Merge4에 currentSongChanged에 걸리게되어, DB가 …

🔀 :: 재생 목록 > 편집 완료 시점에서 DB 업데이트 하도록 변경

---

Projects/App/Sources/Application/SceneDelegate.swift

백그라운드 재생 로직을 개선하기 위해 기존 코드가 왜 동작했는지부터 분석을 시작했습니다.
분석 결과 재생, 일시정지는 웹뷰에게 자바스크립트 이벤트를 보내는 코드인 evaluate()로 동작한다는걸 알게 되었습니다.
```Swift
self.webView.evaluate(
javaScript: .player("playVideo()")
self.webView.evaluate(
javaScript: .player("pauseVideo()")
```
그리고 print를 찍어 상태 변화를  확인한 결과 
백그라운드에 진입 후, async하게 일시정지되는 것을 확인했습니다.
여기서 알 수 있는 점은 기존 코드에서 0.2 ~ 0.5초 후 play()를 호출하도록 했기때문에, paused 보다 play 의 결과가 늦게 도착하도록 임의로 조정하고 있었음을 알 수 있었습니다. 
```Swift
DispatchQueue.main.asyncAfter(deadline: .now() + 0.2)
```
그러면 임의의 시간만큼 play 를 늦게 호출 하지말고 paused되자마자 play를 호출하면 되겠다 생각해
백그라운드 진입 시 재생상태를 구독하고 재생상태가 paused가 되면 play를 호출하도록 로직을 변경했습니다.
Closes #191

🔀 :: 백그라운드 재생 로직 개선

---

Projects/Features/PlayerFeature/Sources/ViewModels/PlayerViewModel.swift
Projects/Features/StorageFeature/Sources/ViewModels/FavoriteViewModel.swift

좋아요 삭제 목록에 현재 재생 곡 포함 시 노티피케이션 발송
플레이어에서 수신 및 좋아요 상태, 좋아요 수 업데이트
Closes #246

🔀 :: 좋아요 삭제 목록에 현재 재생 곡 포함 시 좋아요 상태 업데이트

---

Projects/Features/PlayerFeature/Sources/Views/PlayerView.swift

11프로와 12미니의 스크린 사이즈는 375 × 812 px로 같지만 11프로에선 정상적으로 출력되고 12미니에선 다르게 나오는 문제가 있었습니다.
확인 결과 11프로와 12미니의 스크린 사이즈는 같지만 11프로의 스테이터스바의 높이는 44, 12미니의 스테이터스바의 높이는 50이라서 safeArea Height가 달랐고 아래 코드에서 12미니의 경우 else로 빠지는 문제였습니다.
```Swift
if Utility.SAFEAREA_BOTTOM_HEIGHT() > 0 {
x = ((safeAreaheight - (safeAreaWidth - 50) / (16/9) - 334 - 18) / 20)
} else {
x = ((height - (width - 50) / (16/9) - 286 - 18) / 20)
x = ((safeAreaheight - (safeAreaWidth - 50) / (16/9) - 286 - 18) / 20)
}
```
수정전
수정후
Closes #이슈번호

🔀 :: 12미니에서 레이아웃이 틀어지는 문제 수정

---

Projects/Features/CommonFeature/Sources/PlayState/PlayState+Public.swift

#282 
재생목록 추가 시에 재생목록의 currentPlaySong을 currentSong에 넣어 플레이어가 준비되도록 변경했습니다.

🔀 ::재생목록에 추가 시에도 currentSong 업데이트

---

Projects/Features/CommonFeature/Sources/PlayState/PlayState+YoutubePlayer.swift
Projects/Features/PlayerFeature/Sources/Views/PlayerView.swift

#283 
셔플재생이 켜져있으면 forward가 아니라 shufflePlay()가 호출되는데 changeCurrentPlayIndex 가 누락되어있었습니다.
Closes #283

🔀 :: 셔플 재생 시 currentPlayIndex가 변경되지 않는 문제 수정

---

Projects/Features/CommonFeature/Resources/CommonUI.storyboard
Projects/Features/CommonFeature/Sources/Components/MultiPurposePopComponent.swift
Projects/Features/CommonFeature/Sources/ViewControllers/ContainSongsViewController.swift
Projects/Features/CommonFeature/Sources/ViewControllers/MultiPurposePopupViewController.swift
Projects/Features/CommonFeature/Sources/ViewControllers/PlayListDetailViewController.swift
Projects/Features/StorageFeature/Sources/ViewControllers/AfterLoginViewController.swift
Projects/Features/StorageFeature/Sources/ViewControllers/MyPlayListViewController.swift
Projects/Modules/Utility/Sources/Extensions/Extension+UIViewController.swift

PanModal 라이브러리를 통해 구현한 키보드 포함 모달 화면이 
릴리즈 모드 한정으로 런타임에서 동적으로 뷰 높이 변경이 불가한 문제로 인해 
SwiftEntryKit을 통해 구현합니다.
MultiPurposePopupViewController는 SwiftEntryKit을 통해 모달화면으로 등장하도록 변경
ㄴ 릴리즈 모드 시뮬레이터 동작 확인. 
Closes #258

🔀 :: Feature/fix keyboard modal

---

Projects/Features/CommonFeature/Sources/PlayState/PlayState+PlayProgress.swift
Projects/Features/CommonFeature/Sources/PlayState/PlayState+YoutubePlayer.swift

#280
플레이어가 닫힐 때 총 길이를 0으로 초기화하는 부분을 제거했습니다.
Closes #280

🔀 :: 플레이어가 닫힐때 duration이 초기화 되지 않도록 수정

---

Projects/Features/CommonFeature/Sources/PlayState/PlayState+Playlist.swift

#290
현재 재생중인 곡의 이전 곡을 포함한 삭제 형태가 되면 현재 재생중인 곡이 다시 처음부터 재생되는 문제
1번째 인덱스의 곡이 재생 중일 때, 0번째 인덱스의 곡을 삭제하면 1번째 곡이 0번째로 변경되고 다시 재생되는 문제가 있었습니다.

🔀 :: 재생목록 내 곡 삭제 로직 수정

---

Projects/Features/PlayerFeature/Sources/ViewControllers/PlayerViewController.swift
Projects/Features/PlayerFeature/Sources/ViewModels/PlayerViewModel.swift
Projects/Modules/Utility/Sources/API/WMImageAPI.swift

#306
기존 이미지에 상하 레터박스가 존재해 화면 크기에 맞게 16:9 비율로 변환 시 썸네일 상하에 검은 줄이 보이는 문제였습니다.  
고화질 이미지(1280*720)를 먼저 불러오고 실패 시, 저화질 이미지(320*180)를 불러오도록 변경

🔀 :: 썸네일 검은 줄 해결 및 이미지 품질 향상

---

Projects/Features/CommonFeature/Sources/PlayState/PlayState+Public.swift

#293 
수정 전
self.currentSong = self.playList.currentPlaySong 부터의 코드는 플레이어가 닫혀있는 상태에서 재생목록 담기 시, 
빈 미니플레이어가 올라오는 것을 막기 위해 추가한 코드였지만(#282) 플레이어의 상태에 따른 분기처리가 안되어있었습니다.
```Swift
/// 주어진 곡들을 재생목록에 추가합니다.
/// - Parameter duplicateAllowed: 재생목록 추가 시 중복 허용 여부 (기본값: false)
func appendSongsToPlaylist(_ songs: [SongEntity], duplicateAllowed: Bool = false) {
let notDuplicatedSongs = songs.compactMap { song in
return self.playList.uniqueIndex(of:PlayListItem(item: song)) == nil ? PlayListItem(item: song) : nil
}
self.playList.append(notDuplicatedSongs)
if self.state == .unstarted {
self.switchPlayerMode(to: .mini)
}
self.currentSong = self.playList.currentPlaySong
if let currentSong = currentSong {
self.player.cue(source: .video(id: currentSong.id))
}
}
```
수정 후
if self.state == .unstarted 대신 if …

🔀 :: 재생목록 담기 시 재생중이던 곡이 멈추는 문제 수정

---

Projects/Features/PlayerFeature/Sources/ViewControllers/PlaylistViewController.swift
Tuist/ProjectDescriptionHelpers/Environment.swift

[wakmusic-iOS] New discussion #318: 재생목록 포커싱 기능
1. 테이블 뷰의 리로드 이벤트를 수신하는 Rx 문법 바인딩. 
2. 테이블뷰 리로드가 여러번 들어가는것 같습니다. 3번이나 꽂혀서 1초 내의 이벤트는 스킵하도록 합니다.
3. 재생목록에서 다른 곡을 선택할때도 리로드가 들어와서 이벤트는 1회만 수신하도록 합니다.
4. 재생목록이 없거나, 현재 포커스 하려는 인덱스가 데이터의 범위에 있는지 확인합니다.
5. 테이블뷰의 센터위치로 스크롤을 이동합니다. 애니메이션은 false입니다. + 딜레이 0.1초를 안주면 UI 갱신이 충돌나서 제대로 포커싱이 되지않아서 넣었습니다.
Closes #318

🔀 :: 플레이어 > 재생목록 > 현재 재생 곡으로 포커싱

---

Projects/App/Support/Info.plist
Projects/Features/CommonFeature/Sources/ViewControllers/MultiPurposePopupViewController.swift
Projects/Features/CommonFeature/Sources/ViewControllers/NoticePopupViewController.swift
Projects/Features/MainTabFeature/Sources/ViewModels/MainTabBarViewModel.swift
Projects/Features/RootFeature/Sources/ViewControllers/IntroViewController.swift
Projects/Features/StorageFeature/Sources/ViewControllers/BugReportViewController.swift
Projects/Features/StorageFeature/Sources/ViewModels/NoticeViewModel.swift
Tuist/ProjectDescriptionHelpers/Environment.swift

버그는 아니지만, 짜잘하게 반영할 사항이 보여서 수정하였습니다.
1. 공지 리스트 내림차순 정렬 로직 제거 (백엔드 단의 정렬을 그대로 따라감)
2. 공지 팝업 '확인' 버튼의 문구를 '닫기'로 , collectionView.bounds 설정을 false로 변경
3. 앱 스토어 검색 시 앱 기본 언어가 '영어'로 설정된 것을 '한국어'로 변경
4. 플레이 리스트 가져오기 성공 시에도 토스트 팝업을 추가 (기존에 아무런 메세지가 안나와서 플레이 리스트가 많을 경우 피드백이 없는 것 처럼 보임)
5. Tuist 환경 설정에서 앱 버전 2.0.1, 빌드 번호 0으로 변경
Closes #343

🔀 :: 마이너 수정

---

Projects/App/Sources/Application/NeedleGenerated.swift
Projects/Features/CommonFeature/Sources/ViewControllers/PlayListDetailViewController.swift
Projects/Features/CommonFeature/Sources/ViewModels/PlayListDetailViewModel.swift
Projects/Features/StorageFeature/Sources/Components/MyPlayListComponent.swift
Projects/Features/StorageFeature/Sources/ViewControllers/MyPlayListViewController.swift
Projects/Features/StorageFeature/Sources/ViewModels/FavoriteViewModel.swift
Projects/Features/StorageFeature/Sources/ViewModels/MyPlayListViewModel.swift
Projects/Features/StorageFeature/Sources/Views/MyPlayListTableViewCell.swift

곡 리스트 순서 변경이 가능한 화면 성능 개선(내 플리상세, 내 리스트, 좋아요)
1. 편집 완료 시, 순서가 변경되지 않았음에도 api 요청이 들어가는 부분 개선
2. 보관함 > '내 리스트' 에서 재생 버튼 누를 때, 플레이 리스트 상세 api를 요청하여 재생 리스트를 받아오는 부분 제거.
Closes #이슈번호

🔀 :: 곡 리스트 순서 변경이 가능한 화면의 성능 개선

---

Projects/Features/CommonFeature/Sources/PlayState/PlayState+Public.swift
Projects/Features/CommonFeature/Sources/PlayState/PlayState.swift
Projects/Features/CommonFeature/Tests/TargetTests.swift
Projects/Features/PlayerFeature/Sources/ViewControllers/PlayerViewController.swift

기존엔 재생목록에 a-b-c-d-e 라는 곡이 있을 때 a, c, e, f 를 선택 재생 하면
재생목록에 이미 있는 곡은 변화가 일어나지 않고 a-b-c-d-e-**f** 가 됨
사용자가 선택한 곡을 순서대로 들을 수 있도록 
b-d-**a-c-e-f** 가 되도록 변경
Closes #373

🔀 :: 재생목록 추가 기능 개선

---

Projects/Features/PlayerFeature/Sources/ViewControllers/PlaylistViewController.swift
Projects/Features/PlayerFeature/Sources/Views/PlaylistView.swift

크게 중요한 기능은 아닌데 닫을 수 있는 방법이 only 버튼에서 버튼 or 제스처 두개로 늘어났다고 보면 됩니다.
dismiss되는 트리거는 유튜브 영상 느낌을 참고했습니다.
- 현재재생목록 드래그해서 닫기 기능
~~https://github.com/wakmusic/wakmusic-iOS/assets/60254939/7dbe365a-b6b2-4fc1-bcdf-b9a59ff13124~~
https://github.com/wakmusic/wakmusic-iOS/assets/60254939/6a5767d7-9683-4da4-aead-84f5c03e273f

🔀 :: 현재재생목록 드래그 제스처로 닫기 기능 추가

---

Projects/Features/CommonFeature/Sources/PlayState/PlayState+PlayProgress.swift
Projects/Features/CommonFeature/Sources/PlayState/PlayState+Playlist.swift
Projects/Features/CommonFeature/Sources/PlayState/PlayState+Public.swift
Projects/Features/CommonFeature/Sources/PlayState/PlayState+YoutubePlayer.swift
Projects/Features/CommonFeature/Sources/PlayState/PlayState.swift
Projects/Features/CommonFeature/Tests/PlaylistTests.swift
Projects/Features/CommonFeature/Tests/TargetTests.swift
Projects/Features/PlayerFeature/Sources/ViewControllers/PlayerViewController.swift
Projects/Features/PlayerFeature/Sources/ViewModels/PlayerViewModel.swift
Projects/Modules/Utility/Sources/Utils/Secrets.swift
Projects/Services/APIKit/Sources/Secrets/SecretURL.swift

유지보수를 하며 플레이어 로직 관련 코드를 수정하는 경우가 생겼고, 수정한 코드가 이전 코드와 같게 동작할거란 보장이 없었습니다. 
이를 위해서 콘솔에 직접 찍어가며 디버깅 했으나 놓치는 부분이 생길 수 있기에 테스트코드를 통해 검증할 수 있도록 했습니다.
그러나 초기 PlayState를 설계할때 테스트를 고려하지 않았고, PlayState와 PlayList 간의 상호 의존성이 생겼습니다.
따라서 PlayState와 PlayList 간의 의존성을 분리하고 테스트 코드를 추가하기로 했습니다.
PlayList에서 PlayState를 참조하던 메소드들을 퍼블리셔로 방출하도록 수정하고, PlayState에서 이를 구독하는 방식으로 PlayList에서 PlayState를 참조하지 않도록 변경했습니다.
예시
``` Swift
private func remove(at index: Int) {
// PlayList에서 PlayState 싱글톤에 직접 접근 (테스트 어려움)
PlayState.shared.currentSong = list[safe: currentPlayIndex]?.item
PlayState.shared.loadInPlaylist(at: currentPlayIndex)
}
```
``` Swift
public var currentPlaySongChanged = PassthroughSubject<SongEntity, Never>()
// PlayList에서 변경사항 방출
private func remove(at index: Int) {
currentPlaySongChanged.send(song)
}
// …
```

🔀 :: PlayState와 PlayList 간의 의존성 분리 및 테스트 코드 수정

---

Projects/Features/PlayerFeature/Sources/ViewControllers/PlayerViewController.swift
Projects/Features/PlayerFeature/Sources/ViewControllers/PlaylistViewController.swift
Projects/Features/PlayerFeature/Sources/ViewModels/PlayerViewModel.swift
Projects/Features/PlayerFeature/Sources/ViewModels/PlaylistViewModel.swift
Projects/Features/PlayerFeature/Sources/Views/MiniPlayerView.swift

- **미니플레이어 UI 변경**
- 썸네일 삭제 ❌
- 닫기버튼 삭제 ❌
- 다음버튼 추가 ✅
- 재생목록 바로가기 버튼 추가 ✅
- **재생목록에 곡 수 표기**

🔀 :: 미니 플레이어 UI 변경 및 재생목록에 곡 수 표기

---

Projects/Features/CommonFeature/Resources/RecommendPlayList/RecommendPlayListCell.xib
Projects/Features/CommonFeature/Sources/Views/RecommendPlayListCell.swift
Projects/Features/PlayerFeature/Sources/Views/MiniPlayerView.swift
Projects/Features/PlayerFeature/Sources/Views/PlaylistView.swift

🔀 :: 미니플레이어 간격조정

---

Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistDetailHeaderViewController.swift
Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
Projects/Features/ChartFeature/Sources/ViewContrillers/ChartContentViewController.swift
Projects/Features/CommonFeature/Sources/ViewControllers/NewSongsContentViewController.swift
Projects/Features/CommonFeature/Sources/ViewControllers/OpenSourceLicenseViewController.swift
Projects/Features/CommonFeature/Sources/ViewControllers/PlayListDetailViewController.swift
Projects/Features/CommonFeature/Sources/ViewControllers/ServiceInfoViewController.swift
Projects/Features/PlayerFeature/Sources/Views/PlaylistView.swift
Projects/Features/SearchFeature/Sources/ViewControllers/AfterSearchContentViewController.swift
Projects/Features/SearchFeature/Sources/ViewControllers/BeforeSearchContentViewController.swift
Projects/Features/SignInFeature/Sources/Views/LoginUIExtension.swift
Projects/Features/StorageFeature/Sources/ViewControllers/FaqContentViewController.swift
Projects/Features/StorageFeature/Sources/ViewControllers/FavoriteViewController.swift
Projects/Features/StorageFeature/Sources/ViewControllers/MyPlayListViewController.swift
Projects/Features/StorageFeature/Sources/ViewControllers/NoticeViewController.swift

🔀 :: deprecated 대체
scrollIndicatorInsets > verticalScrollIndicatorInsets
Closes #398

🔀 :: deprecated 대체

---

Projects/Features/ArtistFeature/Sources/ViewModels/ArtistMusicContentViewModel.swift
Projects/Features/CommonFeature/Sources/ViewModels/NewSongsContentViewModel.swift

리스트의 페이징 처리가 들어간 화면의 효율 개선 (최신음악, 아티스트 상세)
[기존]
page: 1 called, count: 30, nextPage exist: true
page: 2 called, count: 30, nextPage exist: true
page: 3 called, count: 30, nextPage exist: true
page: 4 called, count: 30, nextPage exist: true
page: 5 called, count: 30, nextPage exist: true
page: 6 called, count: 30, nextPage exist: true
page: 7 called, count: 30, nextPage exist: true
page: 8 called, count: 30, nextPage exist: true
page: 9 called, count: 5, nextPage exist: true
page: 10 called, count: 0, nextPage exist: false (쓸데 없이 호출되던 api)
[개선]
page: 1 called, count: 30, nextPage exist: true
page: 2 called, count: 30, nextPage exist: true
page: 3 called, count: 30, nextPage exist: true
page: 4 called, count: 30, nextPage exist: true
page: 5 called, count: 30, nextPage exist: true
page: 6 …

🔀 :: 페이징 처리 효율 개선

---

.github/CODEOWNERS

baekteun을 추가하고 CoCoE1203님을 제외해요
Closes #408

🔀 :: (#408) 인원 변동으로 인한 CODEOWNER 수정

---

Makefile
Scripts/GenerateModule.swift

https://github.com/wakmusic/wakmusic-iOS/issues/419
해당 작업을 진행하며 Project를 정의하는 슈가 메서드가 기존의 메서드는 deprecated되고 새로운 메서드를 사용하도록 변경되었어요.
새롭게 사용하는 메서드를 기준으로 Project.swift를 정의하여 모듈을 만들 수 있는 스크립트를 만들어요.
더해서 기존의 feature 생성 스크립트는 feature 레이어에만 한정하여 사용할 수 있지만, 다른 레이어에서도 추가로 만들 수 있도록 기능을 확장했어요.
Resolves: #424
- 모듈 생성 스크립트 작성 (Swift)
- 모듈 레이어 입력
- 모듈 이름 입력
- 모듈이 가진 Target 입력 (Interface, Source{Implementation}, Testing, UnitTests, UITests, Demo)
- 위 입력을 한 후 새로운 모듈을 만들어요
- ModulePaths에 새 모듈 case 추가
- 실제 경로에 해당하는 곳에 모듈 기본 파일 및 Project.swift 정의
- `make feature` 명령어 deprecate
- `make module` 명령어 지원
새 모듈을 추가할 때, 입력을 하라는 문구를 한국어로 할까요? 굳이 영어로 할 필요성을 못느껴서 어떻게 생각하시는지 궁금해요 :)

🔀 :: (#424) 모듈 생성 스크립트 최신 코드 동기화

---

Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
Plugin/DependencyPlugin/ProjectDescriptionHelpers/PathExtension.swift
Plugin/DependencyPlugin/ProjectDescriptionHelpers/TargetDependency+MicroFeatureTarget.swift
Projects/App/Project.swift
Projects/Domains/BaseDomain/Interface/t.swift
Projects/Domains/BaseDomain/Project.swift
Projects/Domains/BaseDomain/Sources/t.swift
Projects/Domains/BaseDomain/Tests/t.swift
Tuist/ProjectDescriptionHelpers/Project/Project+Template.swift

#425 
현재 왁뮤 iOS 모듈 구조에 도메인 레이어를 추가적으로 도입합니다.
1. 시간이 지날수록 비대해지는 Data, Domain, Network, Database, APIKit, DataMapping 모듈
2. UseCase 추가 시 작업 영역이 비효율적
3. 도메인 로직을 위해서는 모두가 Domain 모듈에 의존
위와 같은 이유로 EndPoint에 기준하여 도메인 모듈을 분리합니다.
Resolves: #425 
- ModulePaths(enum)에 domain 케이스 추가
- ModulePaths의 extension으로 Domain(enum)추가 
- Domain(enum)에 BaseDomain, AppDomain 케이스 추가
- Domain 레이어 추가 및 BaseDomain 프로젝트 모듈 생성
작업 내용 외에 불필요한 개행, 들여쓰기 정리하였습니다.

🔀 :: (#425) Domain 레이어 & BaseDomain 추가

---

Scripts/GenerateModule.swift

모듈 생성을 할 때, 생성할 모듈 경로에 디렉토리나 파일이 있으면 아래와 같은 에러가 떠요.
```bash
...
Register ArtistDomain to ModulePaths.swift
GenerateModule/GenerateModule.swift:92: Fatal error: ❌ failed to create directory: ./Projects/Domains/ArtistDomain
```
Resolves: #443 
모듈 생성 스크립트를 실행하고 디렉토리를 생성할 때, 해당 경로에 디렉토리나 파일이 있으면 사용자에게 덮어쓰기를 진행할것인지 질의를 해요.

🔀 :: (#443) 모듈 생성 스크립트 예외처리

---

.github/workflows/AutoAssign.yml
.github/workflows/IssueToPRLabelSync.yml
.github/workflows/IssueToPRLabelSync/ExtractIssueNumber.sh

PR 올릴떄마다 Assign이랑 Labels 지정하기가 너무 귀찮아서 이를 자동화하는 workflow를 추가해요
Resolves: #433 
- PR이 Open, Reopen될 때 Assign을 자신으로 두는 github action workflows 추가
- PR이 Open, Reopen될 때 제목에 있는 (#{숫자}) 로부터 이슈넘버를 가져와서 이슈로부터 Labels를 가져와 PR에 지정하는 github action workflows 추가

🔀 :: (#433) PR Assign, Labels 지정 자동화 workflow 추가

---

.github/workflows/CI.yml

현재 구축되어있는 CI에는 의존성 캐싱이 구현되어있어요. 이때 의존성이 바뀌었는지 확인하는 값의 기준이 `Tuist/Dependencies.swift` 의 파일이 변경되었는지를 기준으로 판단하는데, 이전에 Tuist의 버전을 업그레이드하면서 ( #402 ) 의존성 정의를 `Tuist/Package.swift`에 하도록 변경하였어요.
그렇기에 추후 새로운 의존성을 추가할 때 Dependencies.swift의 내용은 안바뀌기에 이전 의존성을 써서 에러가 날 수 있기에 hashFile의 입력 파일을 `Tuist/Package.swift`로 바꿨어요.
Resolves: #435 
- hashFile의 argument에 `Tuist/Package.swift`를 넘김

🔀 :: (#453) 의존성 캐시의 flag인 hashFile의 입력 파일 변경

---

Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
Projects/Features/BaseFeature/Project.swift
Tuist/Package.resolved
Tuist/Package.swift

ReactorKit 도입이 되기에 ReactorKit 의존성을 추가해요.
Resolves: #457 
- Package.swift에 ReactorKit 추가
- SPM Namespace에 ReactorKit 추가

🔀 :: (#457) Reactor 의존성 추가

---

Scripts/Setup.sh

`make setup`을 실행해서 mise를 통해 tuist를 설치하고나니 tuist command를 못찾았어요.
Resolves: #455 
- Setup.sh 스크립트에 zshrc에 mise를 activate하는 스크립트를 추가했어요
- 설치를 homebrew가 아닌 mise의 스크립트를 사용하여 로컬로 다운바도록 변경했어요. brew로 할경우 사람마다 경로가 달라지는 경우가 있다더라구요.

🔀 :: (#455) make setup 후 tuist command를 못찾는 버그 해결

---

Projects/App/Sources/Application/NeedleGenerated.swift
Projects/Features/ArtistFeature/Sources/Components/ArtistComponent.swift
Projects/Features/ArtistFeature/Sources/Reactors/ArtistReactor.swift
Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistViewController.swift
Projects/Features/ArtistFeature/Sources/ViewModels/ArtistViewModel.swift

Artist 화면의 상태를 관리하는 객체를 viewModel에서 Reactor로 전환했어요.
Resolves: #458 
- ArtistReactor 추가
- ArtistViewModel deprecate
이 PR에서는 ArtistViewModel을 제거하지 않고, deprecated처리만 해요.

🔀 :: (#458) Artist화면의 상태관리 객체 viewModel -> Reactor 전환

---

.swiftformat

format 자동화 기능이 있는데 이 친구가 돌아갈때마다 NeedleGenerated.swift (자동생성 파일) 도 포매팅이 되다보니 불필요하게 변경되는 코드가 많아져요!
Resolves: #474 
.swiftformat 파일 exclude 대상에 '**/NeedleGenerated.swift' 추가

🔀 :: (#474) SwiftFormat 대상에 NeedleGenerated 파일 제외

---

Projects/Features/BaseFeature/Sources/BaseReactorViewController.swift
Projects/Features/BaseFeature/Sources/BaseStoryboardReactorViewController.swift

ReactorKit이 본격적으로 도입됨에 따라 더 간결하고 쉽게 사용할 수 있는 BaseViewController를 추가해ㅛㅇ
Resolves: #478 
- BaseReactorViewController 작업
- BaseStoryboardReactorViewController 작업
override용 메서드를 추가로 만들까요?

🔀 :: (#478) Reactor전용 BaseViewController 추가

---

Projects/Domains/BaseDomain/Sources/Jwt/JwtAuthorizable.swift
Projects/Domains/BaseDomain/Sources/Jwt/JwtPlugin.swift
Projects/Domains/BaseDomain/Sources/ResponseDTO/TokenDTO.swift
Projects/Modules/KeychainModule/Sources/Keychain.swift

> PR을 하게 된 문제상황, 배경 등 개요에 대해서 작성해주세요!
>
> 퍼블리싱의 경우 스크린샷/동영상도 추가해주면 좋아요!
API 스펙이 변경되면서 기존에 액세스토큰만 사용하는 구조에서 리프레시토큰도 사용하게 변경되었어요.
Resolves: #477 
> PR에서 한 작업을 자세히 작성해주세요!
- API에서 Refresh토큰을 적재할 수 있는 옵션을 추가해요
- JwtPlugin에서 refresh token을 대응해요 (송신, 수신)
>
>

🔀 :: (#477) 리프레시 토큰 대응

---

Projects/App/Sources/Application/AppComponent+Auth.swift
Projects/Domains/AuthDomain/Interface/DataSource/LocalAuthDataSource.swift
Projects/Domains/AuthDomain/Interface/Repository/AuthRepository.swift
Projects/Domains/AuthDomain/Interface/UseCase/LogoutUseCase.swift
Projects/Domains/AuthDomain/Sources/DataSource/LocalAuthDataSourceImpl.swift
Projects/Domains/AuthDomain/Sources/Repository/AuthRepositoryImpl.swift
Projects/Domains/AuthDomain/Sources/UseCase/LogoutUseCaseImpl.swift

- 로그아웃을 하는 로직을 처리하기 위한 UseCase를 추가해요
Resolves: #477 
- Logout용 UseCase을 추가했어요
- Repository, DataSource에 Logout을 하는 어플리케이션 로직을 추가했어요
- UseCase라는 개념의 약간 미약해질 수 있지만.. Logout로직을 처리하는 UseCase를 따로 하나 만들었어요
- LogoutUseCase가 동기적으로 처리됨에도 Completable인 이유는 이후 로그아웃 행동에 비동기적 처리가 추가될 수 있어서예요 (e.g. Logout API 추가)

🔀 :: (#477) Logout UseCase 추가

---

Projects/App/Sources/Application/NeedleGenerated.swift
Projects/Features/CommonFeature/Sources/Components/ContainSongsComponent.swift
Projects/Features/CommonFeature/Sources/Components/MultiPurposePopComponent.swift
Projects/Features/CommonFeature/Sources/Components/PlayListDetailComponent.swift
Projects/Features/CommonFeature/Sources/Components/ProfilePopComponent.swift
Projects/Features/CommonFeature/Sources/ViewControllers/ContainSongsViewController.swift
Projects/Features/CommonFeature/Sources/ViewControllers/MultiPurposePopupViewController.swift
Projects/Features/CommonFeature/Sources/ViewControllers/PlayListDetailViewController.swift
Projects/Features/CommonFeature/Sources/ViewControllers/ProfilePopViewController.swift
Projects/Features/CommonFeature/Sources/ViewModels/ContainSongsViewModel.swift
Projects/Features/CommonFeature/Sources/ViewModels/MultiPurposePopupViewModel.swift
Projects/Features/CommonFeature/Sources/ViewModels/PlayListDetailViewModel.swift
Projects/Features/CommonFeature/Sources/ViewModels/ProfilePopViewModel.swift
Projects/Features/PlayerFeature/Sources/Components/PlayerComponent.swift
Projects/Features/PlayerFeature/Sources/ViewControllers/PlayerViewController.swift
Projects/Features/PlayerFeature/Sources/ViewModels/PlayerViewModel.swift
Projects/Features/StorageFeature/Sources/Components/FavoriteComponent.swift
Projects/Features/StorageFeature/Sources/Components/MyPlayListComponent.swift
Projects/Features/StorageFeature/Sources/ViewControllers/FavoriteViewController.swift
Projects/Features/StorageFeature/Sources/ViewControllers/MyPlayListViewController.swift
Projects/Features/StorageFeature/Sources/ViewModels/FavoriteViewModel.swift
Projects/Features/StorageFeature/Sources/ViewModels/MyPlayListViewModel.swift
Projects/Modules/Utility/Sources/Utils/Utils.swift

로그아웃을 처리하는 로직이 Presentation 영역에서 진행되었어요.
Resolves: #477 
- ContainSongs, MultiPurposePopup, PlayListDetail, ProfilePop, Player, Favorite, MyPlayList 페이지의 Logout 로직을 리팩토링했어요.
- 도메인 로직에 해당하는 영역을 ViewModel이 하도록 옮겼어요.

🔀 :: (#477) Feature 레이어의 로그아웃 로직 리팩토링

---

Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistDetailHeaderViewController.swift
Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
Projects/Features/ArtistFeature/Sources/Views/ArtistPlayButtonGroupView.swift
Projects/Features/BaseFeature/Sources/ViewControllers/BaseStoryboardReactorViewController.swift
Projects/Features/BaseFeature/Sources/Views/PlayButtonGroupView.swift
Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
Projects/Features/PlaylistFeature/Resources/Playlist.storyboard
Projects/Features/PlaylistFeature/Sources/Components/PlayListDetailComponent.swift
Projects/Features/PlaylistFeature/Sources/Model/PlayListHeader.swift
Projects/Features/PlaylistFeature/Sources/Model/PlaylistMetaData.swift
Projects/Features/PlaylistFeature/Sources/PlayListDetailViewModel.swift
Projects/Features/PlaylistFeature/Sources/Reactors/PlaylistDetailReactor.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/PlayListDetailViewController.swift

> PR을 하게 된 문제상황, 배경 등 개요에 대해서 작성해주세요!
>
> 퍼블리싱의 경우 스크린샷/동영상도 추가해주면 좋아요!
Resolves: #492
- 플레이리스트 디테일 화면을 reactorKit으로 리팩했습니다.
>
>
남은 작업
-  songCart 관련 작업 
- 저장후 업데이트 (노티)
- 로그인이 필요한 커스텀 플리로 테스트

🔀 :: (#492) PlaylistDetail을 ReactorKit으로 리팩합니다.

---

Projects/App/Support/Info.plist
Projects/Modules/Utility/Sources/GoogleOAuth/GoogleLoginManager.swift
Projects/Modules/Utility/Sources/Utils/Secrets.swift

사용하지 않는, 노출되어도 좋을게 없는 Google Secret을 제거합니다
Resolves: #542 
- file changes에서는 없지만 xcconfig의 내용이 변경되었어요
- Info plist에서 secret에 대한 참조를 제거했어요
- [] 이 작업으로 인해 변경이 필요한 문서가 변경되었나요? (e.g. `XCConfig`, `노션`, `README`)
당장 이 작업으로 xcconfig가 바뀌지 않고 domain 영역의 api도 동시에 변경할 예정이에요
- [] 이 작업으로 인해 변경이 필요한 문서가 변경되었나요? (e.g. `XCConfig`, `노션`, `README`)

🔀  :: (#542) 사용하지 않는 Google Secret 제거

---

.githooks/pre-push
Cartfile

기존에 pre-commit (커밋 전) 시점에 SwiftFormat을 돌리고 개발자가 직접 commit을 하게 했습니다.
단, 이러면서 대두된 문제점이 개발자가 꽤나 번거로움을 느끼게 되고 코드상에 Format을 진행한 커밋이 거의 절반을 먹게 될 수도 있다는 등의 문제점을 야기했습니다.
개발자가 직접 commit을 하게 된 이유는 수동으로 커밋한다면 개발자의 의지대로 커밋을 분리하기가 어려워지기 때문입니다 (pre-commit 시점에 git add . git commit -m "Formatt" 이런식으로 진행했다면 무조건 모든 작업이 하나의 커밋에 이루어져야함
이를 해결하기 위해 SwiftFormat을 자동으로 돌리는 시점을 pre-commit에서 pre-push로 시점 이동을 시킵니다
Resolves: #554 
- pre-commit 트리거 제거
- pre-push 파일 추가
- RealmSwift의 10.50.1버전에서 Xcode 버전과의 오류가 뜨기에 10.50.0으로 아예 exact합니다.
1. 지금 pre-push 직전에 무조건 git add . git commit -m "" 를 하게 되는데 유저에게 SwiftFormat을 돌리겠습니까? 혹은 Formatting한 결과물을 commit까지 하겠습니까?를 물어볼까요?

🔀  :: (#554) pre-push 시점에 SwiftFormat 적용

---

Projects/Features/MyInfoFeature/Sources/Views/SettingItemButton.swift
Projects/Features/MyInfoFeature/Sources/Views/SettingItemView.swift
Projects/Features/MyInfoFeature/Sources/Views/SettingView.swift

좀더 예쁘게 만들고 싶었어요
https://github.com/wakmusic/wakmusic-iOS/assets/60254939/e4a3d605-ad64-46ec-b3d9-f4278ee1a618
- 상속을 UIView -> UIButton 로 변경
- 하이라이팅 효과 추가
https://github.com/wakmusic/wakmusic-iOS/assets/60254939/891ad877-3362-4617-85b6-3d11304f95c1
글자에도 opacity 줄 수 있는데 어떤게 더 예쁜가요?

🔀 :: (#550) 설정 네비게이션 버튼 하이라이팅 효과 추가

---

Projects/Features/MyInfoFeature/Sources/Views/SettingView.swift
Projects/Features/MyInfoFeature/Sources/Views/WithDrawLabel.swift

디자인이 변경되었어요
-`여기` 이 부분에만 터치 이벤트를 적용하고싶긴 한데, 중요한 기능은 아니라 간단하게 label 전체에 대해 터치 이벤트를 받도록 두었습니다.

🔀 :: (#550) 회원탈퇴 버튼 디자인 및 위치 변경

---

Projects/Features/MyInfoFeature/Interface/Interface.swift
Projects/Features/MyInfoFeature/Project.swift
Projects/Features/MyInfoFeature/Sources/Components/AppPushSettingComponent.swift
Projects/Features/MyInfoFeature/Sources/Components/OpenSourceLicenseComponent.swift
Projects/Features/MyInfoFeature/Sources/Components/SettingComponent.swift
Projects/Features/MyInfoFeature/Sources/ViewControllers/Setting/SettingViewController.swift
Projects/Features/MyInfoFeature/Testing/AppPushSettingComponentStub.swift
Projects/Features/MyInfoFeature/Testing/OpenSourceLicenseComponentStub.swift
Projects/Features/MyInfoFeature/Testing/SettingComponentStub.swift
Projects/Features/MyInfoFeature/Testing/testing.swift

설정화면의 Stub을 만들기 위한 내부 모듈들의 Stub 객체를 생성해야 했습니다.
Resolves: #569
- MyInfoFeature 내부 컴포넌트들에 대한 Stub 객체를 생성했습니다.
- 설정화면 컴포넌트에 대한 Stub 객체를 생성했습니다.
SettingComponentStub 은 Testing 모듈에 있고,
Testing모듈은 Feature를 모르기 때문에 SettingViewController 에 Cannot find 'SettingViewController' in scope 에러가 발생했습니다. 이에 대한 해결법으로 
1. Testing 모듈에 Feature 의존성을 추가한다.
2. 모든 ViewController, Reactor 를 각 ~ViewControllerType, ~ReactorType 프로토콜을 인터페이스 모듈에 만들어 채택하도록 한다.
둘 중 코스트가 더 적은 1번 방법을 사용했습니다.
위는 정석적인 TMA 모듈 의존 구조

🔀 :: (#569) 설정 화면 컴포넌트를 Stub 하기 위한 내부 모듈 Stub

---

Projects/Features/BaseFeature/Sources/Views/NoticeCollectionViewCell.swift
Projects/Features/MainTabFeature/Sources/Components/NoticePopupComponent.swift
Projects/Features/MainTabFeature/Sources/ViewControllers/MainTabBarViewController.swift
Projects/Features/MainTabFeature/Sources/ViewControllers/NoticePopupViewController.swift
Projects/Features/MainTabFeature/Sources/ViewModels/MainTabBarViewModel.swift
Projects/Features/MainTabFeature/Sources/ViewModels/NoticePopupViewModel.swift
Projects/Features/StorageFeature/Resources/Storage.storyboard
Projects/Features/StorageFeature/Sources/ViewControllers/NoticeDetailViewController.swift
Projects/Features/StorageFeature/Sources/ViewControllers/NoticeViewController.swift
Projects/Features/StorageFeature/Sources/ViewModels/NoticeDetailViewModel.swift
Projects/Features/StorageFeature/Sources/ViewModels/NoticeViewModel.swift

NoticeDomain 변경사항 반영하다보니 이건 뭐지 싶어서 리팩.
Resolves: #596 
대상: 공지팝업, 공지리스트, 공지상세 
- 뷰모델의 역할을 명확히 해보려 노력함.
- UI코드는 건드리지 않음. (닫기버튼 좌측으로 옮긴것 제외)
공지상세(컬렉션 뷰)의 셀은 이미지로만(여러개 가능) 이루어지고, 현재는 다운로드가 완료된 다음 사이즈를 알아내 컬렉션 뷰를 셋팅하는 형태인데,
이거 셀프사이징 가능한가요? 아는분?

🔀 :: (#596) 공지 화면 리팩토링

---

Projects/App/Sources/Application/AppComponent+Auth.swift
Projects/Domains/AuthDomain/Interface/DataSource/RemoteAuthDataSource.swift
Projects/Domains/AuthDomain/Interface/Entity/AuthLoginEntity.swift
Projects/Domains/AuthDomain/Interface/Repository/AuthRepository.swift
Projects/Domains/AuthDomain/Interface/UseCase/FetchNaverUserInfoUseCase.swift
Projects/Domains/AuthDomain/Interface/UseCase/FetchTokenUseCase.swift
Projects/Domains/AuthDomain/Interface/UseCase/ReGenerateAccessTokenUseCase.swift
Projects/Domains/AuthDomain/Sources/API/AuthAPI.swift
Projects/Domains/AuthDomain/Sources/DataSource/RemoteAuthDataSourceImpl.swift
Projects/Domains/AuthDomain/Sources/Repository/AuthRepositoryImpl.swift
Projects/Domains/AuthDomain/Sources/ResponseDTO/AuthLoginResponseDTO.swift
Projects/Domains/AuthDomain/Sources/UseCase/FetchTokenUseCaseImpl.swift
Projects/Domains/AuthDomain/Sources/UseCase/ReGenerateAccessTokenUseCaseImpl.swift
Projects/Domains/AuthDomain/Testing/FetchTokenUseCaseSpy.swift
Projects/Features/SignInFeature/Sources/ViewModels/LoginViewModel.swift

AuthDomain API 변경사항을 처리했어요
Resolves: #500
- 앱 로그인 API 변경사항 반영
- 액세스토큰 재발급 API 추가
- 노션 xcconfig 업데이트
- AuthAPI에 `fetchNaverUserInfo(tokenType: String, accessToken: String)` 라는 메소드가 있는데, 현재 사용중인 곳도 없고 앞으로 사용될 것 같지 않아 삭제 예정입니다.

🔀 :: (#500) AuthDomain api 변경사항 반영

---

Projects/Features/StorageFeature/Sources/ViewControllers/StorageViewController.swift

내 정보 화면에서 좋아요 바로가기 버튼을 누르면 생기는 버그를 조사하다가 발견해 수정합니다. 
Resolves: #566
- Tabman 라이브러리에서 제공하는 페이지 변경 감지 메소드를 이용. 
- 메소드가 호출되면 reactor로 액션을 보내 Reactor.State 의 상단 탭 인덱스를 변경하도록 합니다.

🔀 :: (#566) 보관함의 상단탭을 변경해도 Reactor.State에 반영되지 않던 문제를 수정합니다.

---

Projects/Features/SearchFeature/Sources/ViewControllers/ListSearchResultViewController.swift
Projects/Features/SearchFeature/Sources/ViewControllers/SongSearchResultViewController.swift

- 같은 필터또는 정렬을 적용해도 데이터를 불러오는 버그가 있었습니다.
Resolves: #641
- 필터 및 정렬 중복 방지 코드를 적용했습니다.
>
>

🔀 :: (#641) 필터 및 정렬 중복 방지 코드를 적용했습니다.

---

Projects/Features/RootFeature/Sources/ViewControllers/IntroViewController.swift
Projects/Modules/Utility/Sources/Extensions/Extension+Notification.Name.swift

v3 라우터 이전으로 인한 임시 로직 제거
Resolves: #637 
- 임시로직 제거

🔀 :: (#637) 스플래쉬(인트로) 임시 로직 제거

---

Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistViewController.swift

🔀 :: (#655) 아티스트 상세 빈 데이터 UI 처리
Resolves: #655 
x

🔀 :: (#655) 아티스트 상세 빈 데이터 UI 처리

---

Projects/Domains/AuthDomain/Sources/API/AuthAPI.swift
Projects/Domains/UserDomain/Sources/ResponseDTO/FetchUserResponseDTO.swift
Projects/Features/SignInFeature/Sources/ViewControllers/LoginViewController.swift
Projects/Features/SignInFeature/Sources/ViewModels/LoginViewModel.swift

로그인이 필요한 작업들이 많이 남아서 급히 픽스했습니다.
Resolves: #666
- ~로그인 api request body 에 오탈자가 있어 대응해뒀습니다. 바뀌면 다시 대응해야함.~ 오탈자 수정되었습니다.
- 유저정보 DTO가 바뀌어 맞게 수정했습니다.
- #663 
- 위 이슈랑 연관되는 문제인데, **itemCount, createdAt 등 신규 생성 필드에 대해선 Entity에 대응이 안되어있어** PreferenceManager.userInfo 에도 저장이 안됩니다. Entity 수정 시 건드려야 할 곳이 많아 해당 PR에선 다루지 않았습니다.
```Swift
// 서버 리스폰스
{
"loginType": "string",
"handle": "string",
"name": "string",
"itemCount": 0,
"profileUrl": "string",
"createdAt": 0
}
// DTO
public struct FetchUserResponseDTO: Decodable, Equatable {
public let itemCount, createdAt: Int
public let id, name, profile, platform: String
enum CodingKeys: String, CodingKey {
case platform = "loginType"
case id = "handle"
case name, itemCount
case profile = "profileUrl"
case createdAt
}
}
public extension FetchUserResponseDTO { …
```

🔀 :: (666) 로그인이 안되던 문제 해결

---

Projects/App/Sources/Application/AppComponent+Base.swift
Projects/Features/BaseFeature/Interface/MultipurposePopUp/MultiPurposePopupFactory.swift
Projects/Features/BaseFeature/Sources/Components/ContainSongsComponent.swift
Projects/Features/BaseFeature/Sources/Components/MultiPurposePopUpComponent.swift
Projects/Features/BaseFeature/Sources/Components/MultiPurposePopupComponent.swift
Projects/Features/BaseFeature/Sources/ViewControllers/ContainSongsViewController.swift
Projects/Features/BaseFeature/Sources/ViewControllers/MultiPurposePopupViewController.swift
Projects/Features/BaseFeature/Sources/ViewModels/MultiPurposePopupViewModel.swift
Projects/Features/MyInfoFeature/Sources/Components/MyInfoComponent.swift
Projects/Features/MyInfoFeature/Sources/ViewControllers/MyInfo/MyInfoViewController.swift
Projects/Features/PlaylistFeature/Sources/Components/MyPlaylistDetailComponent.swift
Projects/Features/PlaylistFeature/Sources/Components/PlayListDetailComponent.swift
Projects/Features/StorageFeature/Sources/Components/PlaylistStorageComponent.swift
Projects/Features/StorageFeature/Sources/Components/StorageComponent.swift
Projects/Features/StorageFeature/Sources/ViewControllers/PlaylistStorageViewController.swift
Projects/Features/StorageFeature/Sources/ViewControllers/StorageViewController.swift
Projects/Modules/Utility/Sources/Extensions/Extension+UIViewController.swift

많은 Usecase가 모여 있어 유지보수가 어려웠습니다.
Resolves: #685
유즈 케이스를 제거 하고 컴플리션으로 입력된 문자열을 넘겨줍니다.
SwiftEntryKIt 자체 Dismiss가 호출되지 않아 동작의 버그가 있어 #690 브랜치 해결 후
디스미스 과정을 추후 반영합니다.

🔀 :: (#685)  Multipurpose VC에서 Usecase를 제거합니다.

---

Projects/Features/MyInfoFeature/Sources/ViewControllers/MyInfo/MyInfoViewController.swift
Projects/Features/MyInfoFeature/Sources/Views/MyInfoView.swift

Resolves: #693 
https://github.com/wakmusic/wakmusic-iOS/assets/60254939/502ee782-00f2-4797-8c55-58ad09370403
내정보 화면의 빈 공간을 터치하거나 탭이 변경되면(viewDidDisappear) 내려갑니다.
- 플로팅버튼의 알파값 애니메이션이 있어 viewDidDisappear 와 viewWillDisappear 를 전부 테스트 해봤는데 육안으로 식별할 수 있는 수준이 아니라서 DidDisappear로 결정했습니다.

🔀 :: (#693) 에딧 시트 숨기기 기능

---

Projects/App/Sources/Application/AppComponent+User.swift
Projects/Domains/UserDomain/Interface/DataSource/RemoteUserDataSource.swift
Projects/Domains/UserDomain/Interface/Entity/FruitDrawStatusEntity.swift
Projects/Domains/UserDomain/Interface/Entity/FruitEntity.swift
Projects/Domains/UserDomain/Interface/Repository/UserRepository.swift
Projects/Domains/UserDomain/Interface/UseCase/DrawFruitUseCase.swift
Projects/Domains/UserDomain/Interface/UseCase/FetchFruitDrawStatusUseCase.swift
Projects/Domains/UserDomain/Interface/UseCase/FetchFruitListUseCase.swift
Projects/Domains/UserDomain/Sources/API/UserAPI.swift
Projects/Domains/UserDomain/Sources/DataSource/RemoteUserDataSourceImpl.swift
Projects/Domains/UserDomain/Sources/Repository/UserRepositoryImpl.swift
Projects/Domains/UserDomain/Sources/ResponseDTO/FruitDrawStatusResponseDTO.swift
Projects/Domains/UserDomain/Sources/ResponseDTO/FruitListResponseDTO.swift
Projects/Domains/UserDomain/Sources/UseCase/DrawFruitUseCaseImpl.swift
Projects/Domains/UserDomain/Sources/UseCase/FetchFruitDrawStatusUseCaseImpl.swift
Projects/Domains/UserDomain/Sources/UseCase/FetchFruitListUseCaseImpl.swift
Projects/Features/FruitDrawFeature/Demo/Sources/AppDelegate.swift
Projects/Features/FruitDrawFeature/Interface/FruitDrawFactory.swift
Projects/Features/FruitDrawFeature/Project.swift
Projects/Features/FruitDrawFeature/Sources/Components/FruitDrawComponent.swift
Projects/Features/FruitDrawFeature/Sources/ViewControllers/FruitDrawViewController.swift
Projects/Features/FruitDrawFeature/Sources/ViewModels/FruitDrawViewModel.swift
Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricDecoratingViewController.swift
Projects/Features/LyricHighlightingFeature/Sources/ViewModels/LyricHighlightingViewModel.swift
Projects/Features/MyInfoFeature/Sources/ViewControllers/MyInfo/MyInfoViewController.swift
Projects/Features/RootFeature/Project.swift
Projects/Features/RootFeature/Sources/ViewControllers/IntroViewController.swift
Projects/Features/SignInFeature/Sources/ViewControllers/LoginViewController.swift
Projects/Features/SignInFeature/Sources/ViewModels/LoginViewModel.swift
Projects/Modules/Utility/Sources/Extensions/Extension+UIViewController.swift

열매 뽑기 화면 구현
Resolves: #699 
- userDomain api 추가 (뽑기 가능 상태 체크, 뽑기, 열매함 리스트)
- usecase 주입 및 구현 (뽑기 가능 상태 체크, 뽑기)
- 뽑기 후 아이템 카운트 반영은 MyInfo에서 구현
- (PR 외) IntroVC > BaseFeature 의존 제거
- (PR 외) 토스트 인터렉션 변경
- (PR 외) 가사 하이라이팅 > 임시로직 제거
- (PR 외) 로그인 > 로딩 인디케이터 추가
- 로티 파일(현재 임시) 받으면 작업예정
https://github.com/wakmusic/wakmusic-iOS/assets/37323252/866e584d-6464-4026-9ad8-5c2835204a7a

🔀 :: (#699) connect usecase fruit draw  외 4

---

Projects/Domains/ImageDomain/Interface/Entity/ProfileListEntity.swift
Projects/Domains/ImageDomain/Sources/ResponseDTO/FetchProfileListResponseDTO.swift
Projects/Features/MyInfoFeature/Resources/ProfilePopUp.storyboard
Projects/Features/MyInfoFeature/Sources/ViewControllers/ProfilePopup/ProfilePopViewController.swift
Projects/Features/MyInfoFeature/Sources/ViewModels/ProfilePopViewModel.swift
Projects/Features/MyInfoFeature/Sources/Views/ProfileCollectionViewCell.swift
Projects/Features/MyInfoFeature/Sources/Views/ProfileView.swift
Projects/Modules/Utility/Sources/API/WMImageAPI.swift

DTO가 변경되었습니다.
Resolves: #670 
DTO와 Entity, 기존에 WMImageAPI로 이미지를 불러오는 로직을 개선했습니다.
기존 DTO
```
type: String? // panchi
version: Int
```
변경된 DTO
```
type: String
name: String // panchi
url: String // ~~/panchi.png
```

🔀 :: (#670) 프로필 이미지 불러오기 DTO 변경사항 반영

---

Projects/Domains/UserDomain/Interface/Entity/UserInfoEntity.swift
Projects/Domains/UserDomain/Sources/ResponseDTO/FetchUserResponseDTO.swift
Projects/Domains/UserDomain/Testing/FetchUserInfoUserCaseSpy.swift
Projects/Features/SignInFeature/Sources/ViewModels/LoginViewModel.swift
Projects/Features/StorageFeature/Sources/ViewModels/AfterLoginStorageViewModel.swift
Projects/Modules/Utility/Sources/Extensions/Extension+PreferenceManager.swift
Projects/Modules/Utility/Sources/Manager/PreferenceManager.swift
Projects/Modules/Utility/Sources/Manager/UserInfoManager.swift

유저 프로필 DTO 변경에 따른 대응
Resolves: #663 
- version 제거, itemCount 추가
- 연관 Entity, Preference 수정
- createAt은 사용처가 없어서 넣지 않음

🔀 :: (#663) 유저 프로필 DTO 변경에 따른 대응

---

Projects/App/Sources/Application/AppDelegate.swift
Projects/Features/MyInfoFeature/Sources/Reactors/MyInfoReactor.swift
Projects/Features/MyInfoFeature/Sources/ViewModels/QuestionViewModel.swift
Projects/Features/SignInFeature/Sources/ViewModels/LoginViewModel.swift
Projects/Features/StorageFeature/Sources/ViewModels/AfterLoginStorageViewModel.swift
Projects/Modules/Utility/Sources/Extensions/Extension+PreferenceManager.swift
Projects/Modules/Utility/Sources/Manager/UserInfoManager.swift
Projects/Modules/Utility/Sources/Utils/AES256.swift

- UserInfo에 값을 저장할때 ID, name은 암호화를 해서 저장하고, 복호화를 하여 사용하는 방식이었음.
Resolves: #751 
- UserInfo entity를 직접 암호화 시켜 저장하던 방식에서 setUserInfo 함수 내로 밀어넣음
- 복호화된 ID, name을 가져오는 프로퍼티 추가
`as-is
AES256.decrypt(encoded: PrefernceManager.userInfo?.ID ?? ""
to-be
PrefernceManager.userInfo.decryptID ?? ""
`
- 결론: AES관련 메소드가 뷰컨이나 뷰모델에서 더 이상 사용되지않음.
- 더 좋은 방법이? 일단 이렇게 밖에 생각안나요. 어디부터 고쳐야할지,

🔀 :: (#751) 프리퍼런스 접근 개선

---

Projects/App/Sources/Application/AppComponent+Playlist.swift
Projects/Features/PlaylistFeature/Demo/Sources/AppDelegate.swift
Projects/Features/PlaylistFeature/Interface/DefaultPlaylistImageFactory.swift
Projects/Features/PlaylistFeature/Sources/Components/DefaultPlaylistImageComponent.swift
Projects/Features/PlaylistFeature/Sources/Components/MyPlaylistDetailComponent.swift
Projects/Features/PlaylistFeature/Sources/Reactors/DefaultPlaylistImageReactor.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/DefaultPlaylistImageViewController.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
Projects/Features/PlaylistFeature/Sources/Views/DefaultThumbnailCell.swift
Projects/Features/PlaylistFeature/Sources/Views/MyPlaylistHeaderView.swift

플레이리스트 썸네일 중 왁뮤에서 제공해주는 이미지를 선택해주는 팝업을 구현 합니다.
https://github.com/wakmusic/wakmusic-iOS/assets/48616183/a4c8b54a-5309-4754-b067-0a362642d92b
Resolves: #735
- 디폴트 이미지를 고를 수 있는 팝업 화면을 구현했습니다.
- 클릭 이벤트를 통해 선택 이미지를 트래킹 합니다.
- 확인 후 창이 닫히며 델리게이트로 선택한 정보를 전다라하고 카메라 딤 화면을 업데이트 합니다.
>
>

🔀 :: (#735)  기본 플레이리스트 이미지 팝업을 만들고 연결합니다. 

---

Projects/App/Sources/Application/AppComponent+Playlist.swift
Projects/Domains/ImageDomain/Interface/DataSource/RemoteImageDataSource.swift
Projects/Domains/ImageDomain/Interface/Entity/DefaultImageEntity.swift
Projects/Domains/ImageDomain/Interface/Repository/ImageRepository.swift
Projects/Domains/ImageDomain/Interface/UseCase/FetchDefaultPlaylistImageUseCase.swift
Projects/Domains/ImageDomain/Sources/API/ImageAPI.swift
Projects/Domains/ImageDomain/Sources/DataSource/RemoteImageDataSourceImpl.swift
Projects/Domains/ImageDomain/Sources/Repository/ImageRepositoryImpl.swift
Projects/Domains/ImageDomain/Sources/ResponseDTO/FetchDefaultImageResponseDTO.swift
Projects/Domains/ImageDomain/Sources/ResponseDTO/FetchProfileListResponseDTO.swift
Projects/Domains/ImageDomain/Sources/UseCase/FetchDefaultPlaylistImageUseCaseImpl.swift
Projects/Features/PlaylistFeature/Project.swift
Projects/Features/PlaylistFeature/Sources/Components/DefaultPlaylistImageComponent.swift
Projects/Features/PlaylistFeature/Sources/Reactors/DefaultPlaylistImageReactor.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/DefaultPlaylistImageViewController.swift
Projects/Features/PlaylistFeature/Sources/Views/DefaultThumbnailCell.swift

실제 서버에 있는 이미지를 불러옵니다.
Resolves: #742
- imageDomain에  기본 playlist 이미지 불러오는 api 경로를 추가 합니다.
- usecase를 구현 후 연결합니다.
>
>

🔀 :: (#742)  플레이리스트 기본 이미지를 불러오는 UseCase를 연결합니다.

---

Projects/Features/MyInfoFeature/Sources/Reactors/MyInfoReactor.swift
Projects/Features/MyInfoFeature/Sources/ViewControllers/MyInfo/MyInfoViewController.swift

- 로그인 필수 화면에 비로그인으로 접근하여 앱 종료 됨
Resolves: #758 
- 로그인 체크 조건 추가
- 로그인 코드 중복으로 인해 reactor action으로 보냄
x

🔀 :: (#758) 비로그인 상태로 열매 뽑기 화면 진입 시 크래쉬

---

Projects/Features/SearchFeature/Sources/CompositionalLayout/Enum/DataSource/BeforeVcDataSoruce.swift
Projects/Features/SearchFeature/Sources/Reactors/BeforeSearchReactor.swift
Projects/Features/SearchFeature/Sources/Reactors/ListSearchResultReactor.swift
Projects/Features/SearchFeature/Sources/Reactors/SongSearchResultReactor.swift
Projects/Features/SearchFeature/Sources/Reactors/WakmusicRecommendReactor.swift
Projects/Features/SearchFeature/Sources/View/PopularPlayListCell.swift
Projects/Features/SearchFeature/Sources/ViewControllers/BeforeSearchContentViewController.swift
Projects/Features/SearchFeature/Sources/ViewControllers/ListSearchResultViewController.swift
Projects/Features/SearchFeature/Sources/ViewControllers/SongSearchResultViewController.swift
Projects/Features/SearchFeature/Sources/ViewControllers/WakmusicRecommendViewController.swift

같은 데이터 소스의 스냅샷을 중복으로 추가하여 발생된느 버그를 해결합니다.
Resolves: #661
- 스냅샷을 데이터소스 올 때 마다 생성합니다.
- 추후 업데이트 내용인 인기 리스트를 주석 및 warning처리 
- 에러 처리 및 토스트 작업
>
>

🔀 :: (#661) 검색 전 화면 로딩 중에 써치바 포커싱 시 앱 종료 버그를 해결합니다.

---

Projects/Domains/SearchDomain/Interface/Enum/Option.swift
Projects/Domains/SongsDomain/Sources/ResponseDTO/SingleSongResponseDTO.swift
Projects/Features/SearchFeature/Sources/Components/SongSearchResultComponent.swift
Projects/Features/SearchFeature/Sources/CompositionalLayout/Layout/ListSearchResultCollectionViewLayout.swift
Projects/Features/SearchFeature/Sources/CompositionalLayout/Layout/SongSearchResultCollectionViewLayout.swift
Projects/Features/SearchFeature/Sources/Reactors/SongSearchResultReactor.swift
Projects/Features/SearchFeature/Sources/View/ListResultCell.swift
Projects/Features/SearchFeature/Sources/View/SearchOptionHeaderView.swift
Projects/Features/SearchFeature/Sources/View/SearchSortOptionCell.swift
Projects/Features/SearchFeature/Sources/View/SongResultCell.swift
Projects/Features/SearchFeature/Sources/ViewControllers/BeforeSearchContentViewController.swift
Projects/Features/SearchFeature/Sources/ViewControllers/ListSearchResultViewController.swift
Projects/Features/SearchFeature/Sources/ViewControllers/SearchSortOptionViewController.swift
Projects/Features/SearchFeature/Sources/ViewControllers/SongSearchResultViewController.swift

곡 검색 결과 화면 songCart를 연결합니다.
Resolves: #755 
- songCart 연결하고 동작을 확인합니다.
- 검색 결과 화면 클릭 범위가 양쪽 20씩 빠져있는걸 해결했습니다.
>
>

🔀 :: (#775) 검샐 결과 화면에 songCart를 연결합니다. 

---

Projects/App/Sources/Application/AppComponent+Search.swift
Projects/Features/SearchFeature/Resources/Search.storyboard
Projects/Features/SearchFeature/Sources/Components/AfterSearchComponent.swift
Projects/Features/SearchFeature/Sources/Components/ListSearchResultComponent.swift
Projects/Features/SearchFeature/Sources/Components/SearchComponent.swift
Projects/Features/SearchFeature/Sources/Components/SongSearchResultComponent.swift
Projects/Features/SearchFeature/Sources/Service/SearchGlobalScrollState.swift
Projects/Features/SearchFeature/Sources/View/ListResultCell.swift
Projects/Features/SearchFeature/Sources/View/SongResultCell.swift
Projects/Features/SearchFeature/Sources/ViewControllers/AfterSearchViewController.swift
Projects/Features/SearchFeature/Sources/ViewControllers/ListSearchResultViewController.swift
Projects/Features/SearchFeature/Sources/ViewControllers/SearchViewController.swift
Projects/Features/SearchFeature/Sources/ViewControllers/SongSearchResultViewController.swift
Projects/Modules/Utility/Sources/Extensions/Extension+UICollectionView.swift
Projects/UsertInterfaces/DesignSystem/Sources/WMFontSystem.swift

검색 결과를 확장하여 보기 위해 검색 바를 불필요할 때 위로 밀어버립니다.
Resolves: #757 #650
https://github.com/wakmusic/wakmusic-iOS/assets/48616183/6dc3f5a2-72c7-4c93-97ec-643059ed086d
- searchGlobalScrollState을 구현하여 화면을 뛰어넘은 이벤트 전달을 연결했했습니다.
- 하위 스크롤 정보를 상단에 전달합니다.
- 하단 탭바에서 검색을 두번 클릭 시 현재 검색화면의 결과를 상단으로 끌어 올립니다.
>
>

🔀 :: (#757) 검색에서 스크롤 올릴 때 pinned Header 걸치기 

---

Projects/Domains/SearchDomain/Interface/Enum/Option.swift
Projects/Features/SearchFeature/Resources/Search.storyboard
Projects/Features/SearchFeature/Sources/CompositionalLayout/Layout/BeforeSearchCollectionViewLayout.swift
Projects/Features/SearchFeature/Sources/CompositionalLayout/Layout/RecommendCollectionViewLayout.swift
Projects/Features/SearchFeature/Sources/View/ListResultCell.swift
Projects/Features/SearchFeature/Sources/View/SearchFilterCell.swift
Projects/Features/SearchFeature/Sources/View/SearchSortOptionCell.swift
Projects/Features/SearchFeature/Sources/View/SongResultCell.swift
Projects/Features/SearchFeature/Sources/ViewControllers/ListSearchResultViewController.swift
Projects/Features/SearchFeature/Sources/ViewControllers/SearchSortOptionViewController.swift
Projects/Features/SearchFeature/Sources/ViewControllers/WakmusicRecommendViewController.swift

검색화면 디자인 검수를 진행했습니다.
Resolves: #762
간단한 레이아웃 간격 조절정도 있습니다.
>
>

🔀 :: (#762) 검색 탭 디자인 검수 완료

---

Projects/Features/PlaylistFeature/Sources/Analytics/PlaylistAnalyticsLog.swift
Projects/Features/PlaylistFeature/Sources/Reactors/MyPlaylistDetailReactor.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/UnknownPlaylistDetailViewController.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/WakmusicPlaylistDetailViewController.swift
Projects/Features/PlaylistFeature/Sources/Views/MyPlaylistHeaderView.swift
Projects/Features/PlaylistFeature/Sources/Views/PlaylistDateTableViewCell.swift
Projects/Features/PlaylistFeature/Sources/Views/UnknownPlaylistHeaderView.swift
Projects/Features/PlaylistFeature/Sources/Views/WakmusicPlaylistHeaderView.swift
Projects/Features/SearchFeature/Sources/Analytics/SearchAnalyticsLog.swift
Projects/Features/SearchFeature/Sources/View/ListResultCell.swift
Projects/Features/SearchFeature/Sources/View/SongResultCell.swift
Projects/Features/SearchFeature/Sources/ViewControllers/BeforeSearchContentViewController.swift
Projects/Features/SearchFeature/Sources/ViewControllers/ListSearchResultViewController.swift
Projects/Features/SearchFeature/Sources/ViewControllers/WakmusicRecommendViewController.swift
Projects/Modules/LogManager/Sources/CommonAnalyticsLog.swift
Projects/UsertInterfaces/DesignSystem/Sources/Extension+UILabel.swift
Projects/UsertInterfaces/DesignSystem/Sources/WMLabel.swift

lineHeight 누락된 것을 채워넣습니다.
Resolves: #765
- playlistDetail lineHeight을 기입했습니다.
- 이미지 선택 관련 로깅을 변경합니다.
>
>

🔀 :: (#765) 플레이리스트 디테일 디자인 검수

---

Projects/App/Sources/Application/AppDelegate.swift
Projects/Features/BaseFeature/Sources/Etc/PlayState/PlayState+Playlist.swift
Projects/Features/BaseFeature/Sources/Etc/PlayState/PlayState+Public.swift
Projects/Features/BaseFeature/Sources/Etc/PlayState/PlayState.swift
Projects/Features/BaseFeature/Sources/Etc/PlayState/PlaylistItem.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/PlayListViewController+Delegate.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/PlayListViewController.swift
Projects/Features/PlaylistFeature/Sources/ViewModels/PlayListViewModel.swift
Projects/Features/PlaylistFeature/Sources/Views/PlaylistTableViewCell.swift
Projects/Modules/Utility/Sources/Realm/RealmManager.swift

- 재생목록에 노래를 추가할 역할을 가진 PlayState의 함수 인터페이스를 뚫어놓았어요.
Resolves: #654 
- 재생목록에 노래를 추가할 역할을 가진 PlayState의 함수 인터페이스를 뚫어놓았어요.
- 추상화는 안되어있고 구체타입에 요청 보내시면 돼요
- 노래 눌렀을 때 재생목록에 추가해야하는 분들 요기에다가 PlayState.shared.append 해주시면 돼용

♻️ :: (#654) PlayState API 노출 및 playlist 캡슐화

---

Projects/Features/HomeFeature/Resources/Home.storyboard
Projects/Features/HomeFeature/Sources/Analytics/HomeAnalyticsLog.swift
Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
Projects/Features/HomeFeature/Sources/ViewModels/HomeViewModel.swift
Projects/Features/HomeFeature/Sources/Views/HomeNewSongCell.swift

- 홈화면과 음악 상세 페이지를 연결해요
Resolves: #807
- 홈화면의 최신 음악 cell 영역의 행동과 상세 페이지를 연결

🔀 :: (#807) 홈화면 음악 상세 연결

---

Projects/Features/BaseFeature/Sources/ViewControllers/ContainSongsViewController.swift
Projects/Features/BaseFeature/Sources/ViewModels/ContainSongsViewModel.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/PlayListViewController+Delegate.swift

플레이리스트에 50곡 이상 담는 것을 방지합니다.
Resolves: #836
https://github.com/user-attachments/assets/64a80e1d-a536-4362-a41e-db800a726fab
불필요한 코드를 제거하고 제한사항 및 토스트 처리
>
>

🔀 :: (#836) ContainSong에 제약 조건 및 에러 토스트 메시지 구현

---

Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
Projects/Modules/Utility/Sources/Enums/WMToastOptions.swift
Projects/Modules/Utility/Sources/Extensions/Extension+UIViewController.swift

- 토스트 offSet 하드코딩의 오류 가능성 제기
Resolves: #854 
- WMToastOptions 추가
- showToast 익스텐션 수정
- after use

🔀 :: (#854) 토스트 옵션 추가

---

Projects/Features/MainTabFeature/Sources/ViewControllers/MainContainerViewController.swift

- drag dismiss시 검은 배경 노출 오류 해결
Resolves: #800 
- showBottomSheet로 프레젠트하면서 자연스런 딤 배경이 깔리도록 변경
x

🔀 :: (#800) drag dismiss시 검은 배경 노출 오류 해결

---

Projects/Features/PlaylistFeature/Sources/Reactors/UnknownPlaylistDetailReactor.swift
Projects/Features/PlaylistFeature/Sources/Reactors/WakmusicPlaylistDetailReactor.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/UnknownPlaylistDetailViewController.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/WakmusicPlaylistDetailViewController.swift

https://github.com/user-attachments/assets/6e812d60-9d47-4bb6-872a-7dd0bd00399b
Resolves: #852
로딩 플래그에 맞춰 hidden을 컨트롤 합니다.
>
>

🔀 :: (#852) 플레이리스트 상세 페이지에서 로딩 전 EmptyView가 보이는 버그를 해결합니다.

---

Projects/Domains/TeamDomain/Interface/Entity/TeamListEntity.swift
Projects/Domains/TeamDomain/Sources/ResponseDTO/FetchTeamListResponseDTO.swift
Projects/Features/TeamFeature/Interface/TeamInfoType.swift
Projects/Features/TeamFeature/Sources/ViewControllers/TeamInfoContentViewController.swift
Projects/Features/TeamFeature/Sources/ViewControllers/TeamInfoViewController.swift
Projects/Features/TeamFeature/Sources/ViewModels/TeamInfoContentViewModel.swift
Projects/Features/TeamFeature/Sources/ViewModels/TeamInfoViewModel.swift

- 하드코딩 해뒀던 2개의 팀을 > 팀 갯수에 맞게 확장되도록 변경
Resolves: #868 
- responseDTO, entity에 part 추가
- 유니크한 team 항목으로 탭 컨트롤러 셋팅
이 또한 api 없이 상상코딩임.

🔀 :: (#868) 팀 소개:: 데이터 구조 변경

---

Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistDetailViewController.swift
Projects/Features/ArtistFeature/Sources/ViewModels/ArtistDetailViewModel.swift

- 아티스트 구독/구독취소 시 상태 값이 바로 반영 안되는 오류 수정
Resolves: #877 
- Completable.andThen() 처리
x

🔀 :: (#877) 아티스트:: 구독 상태 반영 오류 수정

---

Projects/Features/RootFeature/Sources/ViewModels/IntroViewModel.swift

- 앱 접속 시 유저 정보 셋팅
Resolves: #887 
- Intro(스플래쉬) 뷰모델에서 유저 로그인 토큰 만료 체크 때문에 유저 정보를 요청하고 있어  그 요청에 끼워 넣음.
x

🔀 :: (#887) 앱 접속 시 유저 정보 셋팅

---

Projects/App/Sources/Application/AppComponent+Credit.swift
Projects/Domains/BaseDomain/Sources/WMAPI/SecretURL.swift
Projects/Domains/BaseDomain/Sources/WMAPI/WMAPI.swift
Projects/Domains/CreditDomain/Interface/CreditSongOrderType.swift
Projects/Domains/CreditDomain/Interface/DataSource/RemoteCreditDataSource.swift
Projects/Domains/CreditDomain/Interface/Repository/CreditRepository.swift
Projects/Domains/CreditDomain/Interface/UseCase/FetchCreditSongListUseCase.swift
Projects/Domains/CreditDomain/Sources/API/CreditAPI.swift
Projects/Domains/CreditDomain/Sources/DataSource/RemoteCreditDataSourceImpl.swift
Projects/Domains/CreditDomain/Sources/Repository/CreditRepositoryImpl.swift
Projects/Domains/CreditDomain/Sources/ResponseDTO/FetchCreditSongListResponseDTO.swift
Projects/Domains/CreditDomain/Sources/UseCase/FetchCreditSongListUseCaseImpl.swift

CreditDomain을 구현했어요
- FetchCreditSongList API 연결
- Credit 관련 필요 객체 DI Regist

🔀 :: (#812) CreditDomain 구현

---

Projects/App/Support/Info.plist
Projects/Features/BaseFeature/Sources/Protocols/SongCartViewType.swift
Projects/Features/BaseFeature/Sources/Views/SongCartView.swift
Projects/Features/CreditSongListFeature/Demo/Sources/AppDelegate.swift
Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/Component/CreditSongListTabItemComponent.swift
Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabItemReactor.swift
Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabItemViewController.swift
Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/View/CreditSongCollectionHeaderView.swift
Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
Projects/Features/SongCreditFeature/Sources/SongCreditViewController.swift
Projects/Modules/Utility/Sources/Extensions/Extension+UIApplication.swift

Credit 노래 리스트 페이지에서 노래를 선택했을 때의 인터렉션을 추가했어요
Resolves: #910
- Credit 노래 리스트 페이지에서 노래를 선택했을 때의 인터렉션을 추가
- 전체 선택
- 노래 담기
- 재생목록 추가
- 재생

🔀 :: (#910) Credit 작업자 노래 리스트 인터렉션 추가

---

Projects/Features/CreditSongListFeature/Sources/CreditSongList/CreditSongListViewController.swift
Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift

작업자 노래 리스트 화면에서 상단 Gradient가 표시되지 않는 이슈 해결
Resolves: #918 
- 작업자 노래 리스트 화면에서 상단 Gradient가 표시되지 않는 이슈 해결
- viewDidLayout에서 gradientLayer에서 frame 지정을 해주었으나 객체에 지정해줬어야했는데 nil인곳에 지정해버리는 휴먼 에러가 있었어요

🔀  :: (#918) 작업자 노래 리스트 화면에서 상단 Gradient가 표시되지 않는 이슈 해결

---

Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricHighlightingViewController.swift
Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailView.swift
Projects/Features/PlaylistFeature/Sources/Components/PlaylistComponent.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/PlayListViewController+Delegate.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/PlayListViewController.swift
Projects/Features/PlaylistFeature/Sources/Views/PlayListView.swift
Projects/Features/PlaylistFeature/Sources/Views/PlaylistTableViewCell.swift

- 재생목록 화면 인터렉션 추가
- UI 변경사항 반영
Resolves: #912 
Resolved: #798 
- 전체재생, 랜덤재생 추가
- 재생목록 PanGesture 제거
- 곡이 있음에도 재생목록 페이지 최하단에 "곡이 없습니다" 가 뜨는 이슈 해결
이외
- MusicDetail, LyricsHighlighting 등 배경에 썸네일을 블러로 표시하는 로직에 다운로드 options에 onlyFromCache 옵션 제거
- waitForCache와 onlyFromCache가 동시에 있으면 오직 캐시를 기다릴 줄 알았는데.. 캐시가 그냥 없으면 넘어가더라구요.. wait도 안하구요.
- 여타 Play 버튼이 있는 화면에 Youtube Play 추가 (재생목록, MyPlaylist)
#921 
https://discord.com/channels/979764222424657930/1267850815113269350
현재 재생목록 화면이 노래들의 Drag 가 동작을 할 수 없는 상황이에요. 
혹시나 FittedSheets를 사용하면서 이를 해결할 수 없다면 showBottomSheet 대신 overFullScreen present로 다시 돌아가는걸 고려해야할 상황일 수도 있어요. @KangTaeHoon

🔀  :: (#912) 재생목록 화면 인터렉션 및 UI 반영

---

Projects/Features/MusicDetailFeature/Sources/MusicDetail/Views/MusicControlView/MusicControlView.swift
Projects/UsertInterfaces/DesignSystem/Sources/WMFlowLabel.swift

음악 제목 혹은 아티스트(이건 실제로 그런지 케이스 확인 없음) 문자열이 길어서 텍스트가 짤리는 현상이 있었어요
음악 상세 페이지 음악 제목, 아티스트 WMLabel -> WMFlowLabel 전환
Resolves: #899
- 음악 상세 페이지 음악 제목, 아티스트 WMLabel -> WMFlowLabel 전환

🔀  :: (#899) 음악 상세 페이지 음악 제목, 아티스트 WMLabel -> WMFlowLabel 전환

---

Projects/Features/FruitDrawFeature/Sources/Components/FruitDrawComponent.swift
Projects/Features/FruitDrawFeature/Sources/ViewModels/FruitDrawViewModel.swift
Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricHighlightingViewController.swift
Projects/Features/RootFeature/Sources/ViewControllers/IntroViewController.swift
Projects/Features/RootFeature/Sources/ViewModels/IntroViewModel.swift

- 토큰 만료 로직 제거
Resolves: #954 
Resolves: #955 
- 토큰 만료 로직 제거
- 기타 접근 지정자 수정
x

🔀 :: (#954, #955) 불필요 로직 제거

---

Projects/Features/MyInfoFeature/Sources/Reactors/MyInfoReactor.swift
Projects/Features/MyInfoFeature/Sources/Views/FruitDrawButtonView.swift

- 로그아웃을 해도 로그인 상태였을때 열매 갯수가 그대로 남아있음
Resolves: #961 
- 폰트 변경(medium > bold)
- n"개" 텍스트 추가
- 로그인/아웃 시 열매 카운트 갱신 (로그아웃 상태는 카운트를 "마이너스" 값으로 보내 표기하지 않음)
x

🔀 :: (#961) 내 정보:: 로그인/아웃 시 열매 카운트 갱신

---

Projects/Features/BaseFeature/Sources/ViewControllers/ContainSongsViewController.swift
Projects/Features/BaseFeature/Sources/ViewControllers/TextPopupViewController.swift
Projects/Features/MyInfoFeature/Sources/Components/MyInfoComponent.swift
Projects/Features/MyInfoFeature/Sources/Reactors/MyInfoReactor.swift
Projects/Features/MyInfoFeature/Sources/ViewControllers/MyInfo/MyInfoViewController.swift
Projects/Features/MyInfoFeature/Sources/Views/FruitDrawButtonView.swift
Projects/Features/MyInfoFeature/Sources/Views/MyInfoView.swift
Projects/Features/PlaylistFeature/Sources/Reactors/MyPlaylistDetailReactor.swift
Projects/Features/PlaylistFeature/Sources/Reactors/UnknownPlaylistDetailReactor.swift
Projects/Features/PlaylistFeature/Sources/Service/PlaylistCommonService.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/UnknownPlaylistDetailViewController.swift
Projects/Features/StorageFeature/Sources/Reactors/ListStorageReactor.swift
Projects/Features/StorageFeature/Sources/Service/StorageCommonService.swift
Projects/Modules/Utility/Sources/Extensions/Extension+Notification.Name.swift

서로다른 탭에서 수정사항이 일어날 때 다른 탭에도 결과가 적용되야합니다.
Resolves 876이지만 남아있는 작업이 있어 명시는 안함
- 곡 담기 후 보관함에 반영
- 곡 삭제 후 보관함에 반영
- 구독 / 구독해제 시 보관함에 반영
- 보관함에서 삭제 시 , 플레이리스트 상세 구독 상태 변경
- pivate 처리 
>
>

🔀 :: (876) 상호작용이 일어나는 페이지 체크

---

Projects/Domains/UserDomain/Sources/Repository/UserRepositoryImpl.swift
Projects/Features/MyInfoFeature/Sources/Reactors/MyInfoReactor.swift
Projects/Features/RootFeature/Sources/ViewModels/IntroViewModel.swift
Projects/Features/SignInFeature/Sources/ViewModels/LoginViewModel.swift

- 피쳐별로 사용하던 로직을 한 군데로 모음.
Resolves: #965 
- 레파지토리로 로직 이동
- 각 피쳐에서 사용하던 로직 제거
x

🔀 :: (#965) Preference.useInfo 저장 로직 레파지토리로 이동

---

Projects/Features/CreditSongListFeature/Demo/Sources/AppDelegate.swift
Projects/Features/CreditSongListFeature/Project.swift
Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/Component/CreditSongListTabItemComponent.swift
Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabItemReactor.swift
Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabItemViewController.swift
Projects/Features/MusicDetailFeature/Demo/Sources/AppDelegate.swift
Projects/Features/MusicDetailFeature/Project.swift
Projects/Features/MusicDetailFeature/Sources/MusicDetail/Component/MusicDetailComponent.swift
Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailReactor.swift
Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailViewController.swift
Projects/Modules/Utility/Sources/GoogleOAuth/GoogleLoginManager.swift

- 음악 상세 좋아요, 노래 담기 비로그인 처리
Resolves: #932
- 음악 상세 페이지에서 좋아요와 노래 담기를 행동할 때 비로그인을 처리했어요
- Google 로그인을 위한 웹뷰를 present할 때 최상단의 viewController가 아닌 최상단에 보여지는 viewController에 present하도록 변경했어요.
- 스읍 UIApplication.topVisibleViewController() 이 친구 너무 많이 쓰면 계층 구조가 복잡해질 수 있어 자제하고는 싶지만 계속 써야되게 되네요 present위에 present위에 present 🤔 
- 보일러 플레이트가 굉장히 많지만,, 이후 개선 여지는 보이지만 당장은 건드리지 않을거에요.
- 사실 아이디어도 잘 떠오르지는 않아요 🤔🤔🤔🤔🤔🤔🤔🤔

🔀 :: (#932) 음악 좋아요 비로그인 처리

---

Projects/Domains/AuthDomain/Sources/UseCase/FetchTokenUseCaseImpl.swift
Projects/Domains/AuthDomain/Sources/UseCase/LogoutUseCaseImpl.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistDetailContainerViewController.swift
Projects/Features/StorageFeature/Sources/Reactors/LikeStorageReactor.swift
Projects/Features/StorageFeature/Sources/Reactors/ListStorageReactor.swift
Projects/Features/StorageFeature/Sources/Reactors/StorageReactor.swift
Projects/Features/StorageFeature/Sources/Service/StorageCommonService.swift

기존에 `$userInfo`로 옵저빙하여 프로필 변경에도 감지되었습니다.
Resolves: #971
id값과 중복코드를 통해 쓸데 없는 옵저빙을 방지합니다.
>
>

🔀 :: (#971) 플레이리스트 디테일 컨테이너에 로그인 갱신 로직을 변경해요

---

Projects/Features/BaseFeature/Sources/ViewModels/ContainSongsViewModel.swift
Projects/Features/MyInfoFeature/Sources/Reactors/MyInfoReactor.swift
Projects/Features/MyInfoFeature/Sources/Service/MyInfoCommonService.swift
Projects/Features/PlaylistFeature/Sources/Reactors/MyPlaylistDetailReactor.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
Projects/Modules/Utility/Sources/Extensions/Extension+Notification.Name.swift

음표 열매 사용 후 동기화처리가 없었습니다.
Resolves: #976
- NotificationCenter를 이용하여 플리 생성 및 커스텀 이미지 제작 시 음표열매를 사용 후 갱신합니다.
>
>

🔀 :: (#976) 열매 소비가 필요한 로직 이후 유저정보를 갱신합니다.

---

Projects/Domains/AuthDomain/Interface/Repository/AuthRepository.swift
Projects/Domains/AuthDomain/Interface/UseCase/LogoutUseCase.swift
Projects/Domains/AuthDomain/Sources/Repository/AuthRepositoryImpl.swift
Projects/Domains/AuthDomain/Sources/UseCase/LogoutUseCaseImpl.swift
Projects/Domains/AuthDomain/Testing/LogoutUseCaseSpy.swift
Projects/Features/BaseFeature/Sources/ViewModels/ContainSongsViewModel.swift
Projects/Features/MyInfoFeature/Sources/Reactors/SettingReactor.swift
Projects/Features/RootFeature/Sources/ViewControllers/IntroViewController.swift
Projects/Features/RootFeature/Sources/ViewModels/IntroViewModel.swift

- 인트로에서 유저정보 api 호출이 불필요하다는 결론
Resolves: #981 
- 유저정보 api 호출 제거
- 로그인 상태로 앱을 삭제한 유저의 앱 재설치 상황에서 엑세스토큰을 날려주는데, logoutUsecase는 remote와 local 로그아웃이 둘다 이뤄지기 때문에 localOnly 플래그를 추가하였음.
- 기타 네이밍 수정
x

🔀 :: (#981) 인트로(스플래쉬) > 유저정보 api 호출 제거

---

Projects/Features/BaseFeature/Sources/Etc/PlayState/PlayState+Playlist.swift
Projects/Features/BaseFeature/Sources/Etc/PlayState/PlayState.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/PlayListViewController.swift
Projects/Features/PlaylistFeature/Sources/ViewModels/PlayListViewModel.swift

- 재생목록 페이지에서 모든 노래를 삭제가 불가능한 이슈 해결
- 간단하게 말하면 모든 노래를 삭제시키면 화면 dismiss를 시키는데 편집한걸 로컬에 반영하는 트리거를 실행하지 않은채로 dismiss만 시켜서 삭제가 안됐어요
Resolves: #984 
- 모든 노래 삭제를 할 때 editState를 false로 만들어서 PlayState에 보내는 트리거를 실행함

🔀 :: (#984) 재생목록 페이지에서 모든 노래를 삭제가 불가능한 이슈 해결

---

Projects/App/Sources/Application/AppComponent+Playlist.swift
Projects/Domains/PlaylistDomain/Interface/DataSource/RemotePlaylistDataSource.swift
Projects/Domains/PlaylistDomain/Interface/Repository/PlaylistRepository.swift
Projects/Domains/PlaylistDomain/Sources/DataSource/RemotePlaylistDataSourceImpl.swift
Projects/Domains/PlaylistDomain/Sources/Repository/PlaylistRepositoryImpl.swift
Projects/Domains/PlaylistDomain/Sources/UseCase/FetchPlaylistSongsUseCaseImpl.swift
Projects/Features/StorageFeature/Sources/Components/LikeStorageComponent.swift
Projects/Features/StorageFeature/Sources/Components/ListStorageComponent.swift
Projects/Features/StorageFeature/Sources/Components/StorageComponent.swift
Projects/Features/StorageFeature/Sources/Reactors/LikeStorageReactor.swift
Projects/Features/StorageFeature/Sources/Reactors/ListStorageReactor.swift
Projects/Features/StorageFeature/Sources/Service/StorageCommonService.swift
Projects/Features/StorageFeature/Sources/ViewControllers/LikeStorageViewController.swift
Projects/Features/StorageFeature/Sources/ViewControllers/ListStorageViewController.swift

재생목록에 추가하는 기능들 빨리 구현해야겠다 해서 처리했슴다
Resolves: #769
- DefaultStorageCommonService 싱글톤 복구
> 편집 상태 공유 등 storage, list, like 셋이서 같은 상태를 공유하기 위함이었는데, 각각 인스턴스를 생성하면 상태를 공유하지 못함..
- 플레이리스트 key값을 통해 곡들 가져오는 UseCase 추가
- 플레이리스트를 재생목록에 추가 기능 구현
- 플레이리스트를 재생목록에 추가 및 재생 기능 구현
- 구독중인 리스트 삭제 시 노티 전송
- 좋아요한 곡 재생목록에 추가 시 50곡 제한 코드 추가

🔀 :: (#769) 보관함 플레이리스트를 현재 재생목록에 추가하는 기능들 구현

---

Projects/Features/BaseFeature/Sources/Etc/PlayState/PlayState+Playlist.swift
Projects/Features/BaseFeature/Sources/Etc/PlayState/PlayState.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/PlayListViewController.swift
Projects/Features/PlaylistFeature/Sources/ViewModels/PlayListViewModel.swift

- 재생목록에 노래를 최대 50개만 제한할 수 있게 했어요.
- 노래를 저장할 시 50개 이상이면 오래된순으로 잘라서 저장되게 해요.
Resolves: #983

🔀 :: (#983) 재생목록 저장 최대 50개로 제한

---

Projects/Features/MyInfoFeature/Sources/Reactors/MyInfoReactor.swift
Projects/Features/MyInfoFeature/Sources/Service/MyInfoCommonService.swift
Projects/Features/MyInfoFeature/Sources/ViewControllers/MyInfo/MyInfoViewController.swift

기존엔 내 정보 리액터가 생성되면 PreferenceManager.userInfo 와 바인딩을 맺어 유저정보를 fetch 해오는 방식이었습니다.
PreferenceManager.userInfo 는 어디까지나 로컬 정보이기에 가져오는 타이밍에 따라 서버와 다른 값을 가지고 있을 수 있다는 위험성이 존재했습니다.
따라서 버그 방지 및 동작 일관성을 위해 viewDidLoad시 api를 호출해 유저정보를 갱신하도록 변경합니다.
Resolves: #990
- viewDidLoad 시 서버로부터 유저정보 fetch
- 리액터에서 직접 옵저빙하던 코드들 transform 으로 리팩토링
- 변수명, extension 등 코드 가독성 개선
```swift
private extension MyInfoReactor {
func mutateFetchUserInfoUseCase() -> Observable<Mutation> {
return fetchUserInfoUseCase.execute()
.asObservable()
.flatMap { _ in Observable.empty() }
.catch { error in
let error = error.asWMError
return Observable.just(.showToast(error.errorDescription ?? "알 수 없는 오류가 발생하였습니다."))
}
}
func mutateSetRemoteUserNameUseCase(_ newNickname: String) -> Observable<Mutation> {
setUsernameUseCase.execute(name: …
```

🔀 :: (#990) 내 정보 viewDidLoad 시 서버로부터 유저정보 fetch

---

Projects/Features/PlaylistFeature/Sources/Components/PlaylistComponent.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistViewController+Delegate.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistViewController.swift
Projects/Features/PlaylistFeature/Sources/ViewModels/PlayListViewModel.swift

재생목록 곡 담기 시 편집상태 동기화 깨짐 문제발견
Resolves: #986
- 비로그인 시 로그인 로직 추가
- 노래담기 시 편집상태 동기화
>
>

🔀 :: (#986)  재생목록 편집 상태 동기화

---

Projects/Features/BaseFeature/Sources/ViewModels/ContainSongsViewModel.swift
Projects/Features/MyInfoFeature/Sources/Reactors/MyInfoReactor.swift
Projects/Features/StorageFeature/Sources/Reactors/ListStorageReactor.swift
Projects/Features/StorageFeature/Sources/ViewControllers/ListStorageViewController.swift

Resolves: #993
- 플리 생성 시 열매 차감 안됨 -> 서버에서 차감 로직이 적용안된걸로 확인 -> 서버에서 로직 추가하면 정상적으로 동작할거에요 아마?
- 보관함 탭에서 열매 뽑기시 바로 반영 안됨 -> 열매를 뽑은 다음 노티를 발송해서 갱신하도록 수정

🔀 :: (#993) 열매 갯수 변동 시 내 정보에 바로 반영되지 않는 문제 수정

---

Projects/Features/StorageFeature/Sources/Service/StorageCommonService.swift

> 내 정보 페이지 접근 후 호출된 api 목록
[GET] ~~/app/check
[GET] ~~/user/profile
[GET] ~~/user/playlists << ?
[GET] ~~/user/likes << ?
[GET] ~~notice/ids
[GET] ~~/notice/popup
그리고 보관함으로 가면
[GET] ~~/user/playlists
[GET] ~~/user/likes
또 호출됨
위와 같은 문제가 발생하고 있었습니다. 확인해본 결과
```swift
loginStateDidChangedEvent = PreferenceManager.$userInfo.map(\.?.ID).distinctUntilChanged()
```
해당 로직에 문제가 있었습니다. 위 이벤트는 api 호출과 바인딩이 되어있는데, 앱이 실행되고 reactor-service간 바인딩이될 때 이벤트를 방출하기 때문에, api가 호출되고 있었습니다.
```swift
loginStateDidChangedEvent = PreferenceManager.$userInfo.map(\.?.ID).skip(1).distinctUntilChanged()
```
그래서 초기 이벤트를 skip 시켜 해결했습니다.
Resolves: #978
> skip 추가

🔀 :: (#978) 앱이 실행되자마자 보관함을 갱신하는 문제 수정

---

Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailView.swift
Projects/Features/MusicDetailFeature/Sources/MusicDetail/Views/MusicToolbarView.swift

Resolves: #998
- 음악 상세 UI 제약조건 변경
- 유틸리티 전역 함수 사용에서 safeAreaLayoutGuide로 변경
- MusicToolbarView에 layoutMargin 적용

🔀 :: (#998) 음악 상세 UI 제약조건 변경

---

Projects/Features/MyInfoFeature/Sources/Reactors/MyInfoReactor.swift

근본적인 문제는 해결이 안되었다고 생각해서 이슈는 열어두겠습니다.
- 비로그인시 fetchUserInfo api 요청하지 않도록 guard 처리

🔀 :: [#1001] 비로그인 상태에서 토큰이 필요한 api를 요청하면, 토큰을 재발급하려고 시도하는 문제 수정

---

Projects/Features/MyInfoFeature/Sources/Reactors/SettingReactor.swift
Projects/Features/StorageFeature/Sources/Views/ListStorageTableViewCell.swift

플레이스홀더에 이미지를 박아놔서 캐싱되지 않은 이미지를 다운로드 하는 과정에서 보이나봐요.
플레이스홀더를 제거했습니다.
Resolves: #1008
- 보관함 리스트 썸네일 플레이스홀더 제거
- 캐시 삭제 로직 수정

🔀 :: [#1008] 보관함 리스트 썸네일이 깜빡이는 문제 수정

---

Projects/Features/MyInfoFeature/Sources/Reactors/SettingReactor.swift
Projects/Features/MyInfoFeature/Sources/ViewControllers/Setting/SettingViewController.swift
Projects/Features/MyInfoFeature/Sources/Views/SettingView.swift
Projects/Features/StorageFeature/Sources/ViewControllers/ListStorageViewController.swift

https://github.com/user-attachments/assets/fcb5a059-dea0-4686-8f2a-443511909865
로그인 팝업 서순이 바텀시트 -> 풀스크린 으로 되어있음.
두번 뜨는게 UX적으로 좋아보이진 않음.
바로 풀스크린 로그인 팝업이 뜨도록 수정
Resolves: #{이슈번호}
- 로그인 팝업 바로 풀스크린으로 수정
- 로그아웃 진행 시 인디케이터 추가
- settingReactor 작은 코드 리팩토링

🔀 :: [#1007] 로그인 이중 팝업 UX 수정

---

Projects/Features/MainTabFeature/Sources/ViewModels/MainTabBarViewModel.swift

- 3.0 대상 사용자에게 일어날 상황은 아닌데,  지금 개발버전에서 푸시 기능이 추가 된 이후로 발생한 것으로 보임
Resolves: #1013 
- throttle 구문 삭제
x

🔀 :: (#1013) 푸시 토큰 등록 오류 의심 로직 제거

---

Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailReactor.swift

음악 상세에서 노래 재생 시 플리에 추가
Resolves: #1021
- 음악 상세에서 노래 재생 시 플리에 추가

🔀 :: (#1021) 음악 상세에서 노래 재생 시 플리에 추가

---

Projects/Features/StorageFeature/Sources/Service/StorageCommonService.swift

로그인 상태로 앱을 켰을 때, 내정보화면에서 시작했고 보관함 탭으로 이동한 상황
Resolves: #978
보관함 탭은 userinfo.id를 옵저빙하고 있음.
앱이 시작되면 userinfo.id와 바인딩이 시작되고, 첫번째 옵저버블이 방출
내정보 탭이 viewDidLoad 되면 fetchUserInfo를 호출하고 userinfo를 덮어쓰면서, 두번째 옵저버블이 방출됨
```swift
PreferenceManager.$userInfo.map(.?.ID).skip(1).distinctUntilChanged()
```
문제 상황을 재현해보면 userInfo.id = 123 이 들어있는 상태이고, fetch를 땡겨도 123이 넘어오는 상황이라고 가정.
skip(1).distinctUntilChanged() 이면
1. 바인딩될때 123 옵저버블이 skip에 의해 사라짐
2. fetch하면 id가 덮어씌워지고 123 옵저버블이 방출되는데, skip은 이미 썼고 disChanged()는 직전에 방출한 값이 없기 때문에 그대로 123이 방출됨
```swift
PreferenceManager.$userInfo.map(.?.ID).distinctUntilChanged().skip(1)
```
disChanged().skip(1) 이면
1. 바인딩될때 123 옵저버블이 distinctUntilChanged()를 거쳐 방출됨
2. skip에서 123이 사라짐
3. fetch하면 id가 123이 넘어오는데, disChanged가 직전에 방출했던 123이랑 똑같기 때문에 방출하지 않음
distinctUntilChanged()는 …

🔀 :: (#978) 내정보화면에서 불필요한 api가 호출되던 문제 수정

---

Projects/Features/PlaylistFeature/Sources/Reactors/PlaylistDetailContainerReactor.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistDetailContainerViewController.swift

이전에는 container 내용 불러오기 전 까지 비어있는 화면이 깁니다.
Resolves: #1046
- 눈속임 네비게이션 처리
- ownerId 처리 방식 변경
>
>

🔀 :: (#1046) 플레이리시트 컨테이너 로딩 중 처리

---

Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistViewController.swift
Projects/Features/BaseFeature/Sources/ViewModels/ContainSongsViewModel.swift
Projects/Features/MyInfoFeature/Sources/Reactors/MyInfoReactor.swift
Projects/Features/PlaylistFeature/Sources/Reactors/MyPlaylistDetailReactor.swift
Projects/Features/PlaylistFeature/Sources/Reactors/UnknownPlaylistDetailReactor.swift
Projects/Features/PlaylistFeature/Sources/Reactors/WakmusicPlaylistDetailReactor.swift
Projects/Features/SearchFeature/Sources/After/Reactors/ListSearchResultReactor.swift
Projects/Features/SearchFeature/Sources/After/Reactors/SongSearchResultReactor.swift
Projects/Features/SearchFeature/Sources/Before/Reactors/BeforeSearchReactor.swift
Projects/Features/SearchFeature/Sources/Before/Reactors/WakmusicRecommendReactor.swift
Projects/Features/SignInFeature/Sources/ViewModels/LoginViewModel.swift
Projects/Features/StorageFeature/Sources/Reactors/LikeStorageReactor.swift
Projects/Features/StorageFeature/Sources/Reactors/ListStorageReactor.swift
Projects/Modules/Localization/Resources/en.lproj/Localizable.strings
Projects/Modules/Localization/Resources/ko.lproj/Localizable.strings
Projects/UsertInterfaces/DesignSystem/Sources/WMRetryWarningView.swift

- 네트워크 통신 실패 시 빈 UI가 나타남
Resolves: #1048 
- Retry UI 추가
- 로컬라이징에 공통 문구 추가(알 수 없는 오류), 하드코딩 사용처 모두 변경
x

🔀 :: (#1048) 아티스트:: Retry UI 추가

---

Projects/Features/PlaylistFeature/Sources/Reactors/PlaylistDetailContainerReactor.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistDetailContainerViewController.swift

비로그인 시 플레이리스트 디테일 화면의 indicator가 꺼지지 않는 버그가 있습니다.
Resolves: #1054
- 비로그인 시 인디케이터 처리를 해줬씁니다.
>
>

🔀 :: (#1054)  비 로그인 시 무한로딩 버그 해결

---

Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailReactor.swift
Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailViewController.swift
Projects/Features/StorageFeature/Sources/Reactors/LikeStorageReactor.swift
Projects/Features/StorageFeature/Sources/Service/StorageCommonService.swift

음악 상세에서 좋아요 클릭 시 보관함 좋아요 페이지 리스트 갱신
Resolves: #1047
- 음악 상세에서 좋아요 클릭 시 보관함 좋아요 페이지 리스트 갱신
- shouldRefreshLikeList를 만든 이유는 좋아요 클릭할때마다 갱신 요청하면 좀 엄일거같아서 화면 닫힐때 판단해서 리프레시 요청 보내게 해놨어요.

🔀 :: (#1047) 음악 상세에서 좋아요 클릭 시 보관함 좋아요 페이지 리스트 갱신

---

Projects/Features/MainTabFeature/Sources/ViewControllers/MainContainerViewController.swift
Projects/Features/StorageFeature/Sources/ViewControllers/StorageViewController.swift
Projects/Modules/Utility/Sources/Extensions/Extension+Notification.Name.swift

- 플로팅 버튼 탭에 따른 위치 조절
Resolves: #1057 
- 플로팅 버튼 탭에 따른 위치 조절
x

🔀 :: (#1057) 플로팅 버튼 탭에 따른 위치 조절

---

Projects/Features/BaseFeature/Sources/Protocols/EditSheetViewType.swift
Projects/Features/BaseFeature/Sources/Protocols/PlaylistEditSheetViewType.swift
Projects/Features/BaseFeature/Sources/Protocols/SongCartViewType.swift
Projects/Features/BaseFeature/Sources/Protocols/WMBottomSheetViewType.swift
Projects/Features/BaseFeature/Sources/ViewControllers/ContainSongsViewController.swift
Projects/Features/BaseFeature/Sources/Views/WMBottomSheetView.swift
Projects/Features/FruitDrawFeature/Sources/ViewControllers/FruitStorageViewController.swift
Projects/Features/MainTabFeature/Sources/ViewControllers/BottomTabBarViewController.swift
Projects/Features/MainTabFeature/Sources/ViewControllers/MainContainerViewController.swift
Projects/Features/MainTabFeature/Sources/Views/TabItemView.swift
Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailReactor.swift
Projects/Features/PlaylistFeature/Sources/Reactors/MyPlaylistDetailReactor.swift
Projects/Features/PlaylistFeature/Sources/Service/PlaylistCommonService.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistViewController.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/UnknownPlaylistDetailViewController.swift
Projects/Features/PlaylistFeature/Sources/Views/PlayListView.swift
Projects/Features/SearchFeature/Sources/Root/ViewControllers/SearchViewController.swift
Projects/Features/StorageFeature/Sources/Reactors/ListStorageReactor.swift
Projects/Features/StorageFeature/Sources/Service/StorageCommonService.swift
Projects/Modules/Utility/Sources/Extensions/Extension+Notification.Name.swift

- 노티 이름을 규칙에 맞게 바꿔봄
Resolves: #970 
- 노티 이름을 규칙에 맞게 바꿔봄
- 미사용 노티 제거 등
- 재생목록 화면:: 하단 쏭카트 show/hide시 UI 조정
- 개선할 점이 있다? 리뷰좀

🔀 :: (#970) 노티피케이션 이름 정리

---

Projects/Features/MainTabFeature/Sources/ViewControllers/MainContainerViewController.swift
Projects/Features/PlaylistFeature/Sources/ViewModels/PlayListViewModel.swift

재생목록에 곡이 없을 시 FAB 버튼 숨김 처리
Resolves: #1063
- 재생목록에 곡이 없을 시 FAB 버튼 숨김 처리
- 재생목록의 전체 삭제가 동작하지 않는 이슈 해결

🔀 :: (#1063) 재생목록에 곡이 없을 시 FAB 버튼 숨김 처리

---

Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
Projects/Features/FruitDrawFeature/Sources/ViewControllers/FruitDrawViewController.swift
Projects/Features/MainTabFeature/Sources/ViewControllers/MainTabBarViewController.swift
Projects/Features/MyInfoFeature/Sources/ViewControllers/Question/QuestionViewController.swift
Projects/Features/MyInfoFeature/Sources/ViewModels/QuestionViewModel.swift

- 아티스트 상세:: 크레딧에서 접근한 경우 노래 썸네일이 눌리지않는 오류 수정
Resolves: #1069
- present 로직 수정
- (PR외) 열매뽑기:: 리워드 이미지 콘텐트모드 수정
- (PR외) 문의하기:: 충족기준보기 기능 제거
- 노래 상세는 중복 뎁스를 비허용으로 가는게 좋겠습니다. 노래상세에서 재생목록으로 전환을 한다던지, 좋아요 누름/취소 등의 여러 액션이 일어나는경우 여러개가 띄워진 상태면 혼동이 올 것도 같고 그로인한 사이드이펙트가 예상이 되질않네요.

🔀 :: (#1069) 아티스트 상세:: 크레딧에서 접근한 경우 노래 썸네일이 눌리지않는 오류 수정 외 2

---

Projects/UsertInterfaces/DesignSystem/Sources/SingleActionButtonView.swift

- 최신음악:: 전체재생 버튼 텍스트의 센터정렬이 맞지않음
Resolves: #1078 
- 센터정렬 수정
x

🔀 :: (#1078) 최신음악:: 전체재생 버튼 텍스트의 센터정렬이 맞지않음

---

Projects/Features/PlaylistFeature/Sources/Reactors/MyPlaylistDetailReactor.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift

기존에 편집 하단뷰를 선택하지 않으면 닫히지 않았습니다.
Resolves: #1093
더보기 버튼을 다시 누르면 내려갑니다.
>
>

🔀 :: (#1093) 더보기 버튼을 통해 하단 뷰 숨기기

---

Projects/Features/PlaylistFeature/Sources/Components/PlaylistDetailComponent.swift
Projects/Features/PlaylistFeature/Sources/Components/UnkwonPlaylistDetailComponent.swift
Projects/Features/PlaylistFeature/Sources/Reactors/PlaylistDetailContainerReactor.swift
Projects/Features/PlaylistFeature/Sources/Reactors/UnknownPlaylistDetailReactor.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistDetailContainerViewController.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/UnknownPlaylistDetailViewController.swift

private 플리 접근 시 화면이 숨김처리되는 버그가 있습니다.
Resolves: #1091
private 알림을 unknown playlist에서 container VC쪽으로 옮겼습니다.
>
>

🔀 :: (#1091) private 플리 접근 처리

---

Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabItemReactor.swift

- Credit 로딩 인디케이터가 불필요한 상황에 표시되는 이슈 해결
Resolves #1099
- Credit 로딩 인디케이터가 불필요한 상황에 표시되는 이슈 해결

🔀 :: (#1099) Credit 로딩 인디케이터가 불필요한 상황에 표시되는 이슈 해결

---

Projects/Features/StorageFeature/Sources/ViewControllers/LikeStorageViewController.swift
Projects/Features/StorageFeature/Sources/Views/LikeStorageTableViewCell.swift
Projects/Features/StorageFeature/Sources/Views/LikeStorageView.swift

- 보관함 - 좋아요 창에서도 제목부분 클릭시 곡상세로 가도록
Resolves: #1101 
- 터치영역 셀 전체로 확장
x

🔀 :: (#1101) 보관함 - 좋아요 창에서도 제목부분 클릭시 곡 상세로 가도록

---

Projects/Features/PlaylistFeature/Sources/Reactors/MyPlaylistDetailReactor.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift

기존에 오래걸리는 작업 시 완료버튼이 계속 클릭되어 음표열매가 삭제되는 버그가 있습니다.
Resolves: #1105
https://github.com/user-attachments/assets/7dcf9531-a733-4b16-9c2f-6cd5b567d245
완료버튼을 숨기고 응답을 기다리는 동안 인디케이터를 노출합니다.
>
>

🔀 :: (#1105)  My 플리 저장 시 인디케이터 작업

---

.github/workflows/AutoCloseIssueByPullRequest.yml

PR merge시 연관 이슈 자동 close가 동작하지 않는 이슈
Resolves: #1123 
PR merge시 연관 이슈 자동 close가 동작하지 않는 이슈

🔀 :: (#1123) PR merge시 연관 이슈 자동 close가 동작하지 않는 이슈

---

Projects/App/Project.swift
Projects/Domains/BaseDomain/Sources/Logging/CustomLoggingPlugin.swift

네트워크 로그가 길기 때문에 콘솔 창이 복잡해지고, 원하는 로그를 찾으려면 스크롤을 한참 올려야하는 문제가 있어요.
로그를 자세히 보고 싶을때 도 있고, 로그를 간소화하여 콘솔창을 간결하게 보고 싶을 때도 있을테니 선택해서 볼 수 있게 개선하면 좋을 것 같아요
Resolves: #1121
Scheme 의 환경 변수를 통해 네트워크 로그를 기존처럼 detail로 볼건지, short으로 볼건지를 분기하도록 했습니다.
tuist 세팅을 통해 앱 스킴에 기본값으로 short으로 설정해두었습니다.
Scheme - Environment Values 에 `NETWORK_LOG_LEVEL: short` 또는 `NETWORK_LOG_LEVEL: detail` 입력
short 양식 추천받습니다

🔀 :: (#1121) 네트워크 로그를 디테일/간소화 로 분기처리

---

Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
Projects/Features/MusicDetailFeature/Demo/Sources/AppDelegate.swift
Projects/Features/MusicDetailFeature/Sources/MusicDetail/Component/MusicDetailComponent.swift
Projects/Features/MusicDetailFeature/Sources/MusicDetail/Model/SongModel.swift
Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailReactor.swift
Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailViewController.swift

- 음악 상세 노래방 번호 표시가 안되는 이슈 해결
- 놀랍게도 상태를 바인딩 시켜놓지 않았어요
- 금영, 태진이 모두 태진으로만 표시되는 이슈도 있었어요
Resolves: #1129 
- 음악 상세 노래방 번호 표시가 안되는 이슈 해결

🔀 :: (#1129) 음악 상세 노래방 번호 표시가 안되는 이슈 해결

---

Projects/Features/MyInfoFeature/Sources/Views/ProfileView.swift

마이 페이지 프로필 버튼 bouncy 이펙트 추가
Resolves: #1114
- 마이 페이지 프로필 버튼 bouncy 이펙트 추가
https://github.com/user-attachments/assets/1cbe29b2-3eea-4581-96bf-bfbf76a56308

🔀 :: (#1114) 마이 페이지 프로필 버튼 bouncy 이펙트 추가

---

Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistViewController.swift

- 아티스트 리스트 페이지 translucent 적용
Resolves: #1138
- 아티스트 리스트 페이지 translucent 적용
https://github.com/user-attachments/assets/441e61fd-5b9c-4a9c-880c-edc0ac1e49d3

🔀 :: (#1138) 아티스트 리스트 페이지 translucent 적용

---

Projects/Features/BaseFeature/Interface/TextPopUp/TextPopUpFactory.swift
Projects/Features/MyInfoFeature/Sources/ViewControllers/Setting/SettingViewController.swift
Projects/Features/MyInfoFeature/Sources/Views/WithDrawLabel.swift

회원탈퇴 버튼에서 '여기' 텍스트 이외에도 탈퇴 동작이 이루어짐
Resolves: #1139
- 회원탈퇴 버튼에서 '여기' 텍스트를 눌렀을 때만 회원탈퇴 프로세스 시작
- 회원탈퇴 프로세스를 시작할 때 textPopupViewController를 두개를 미리 만들어서 하고있었으나, 더블체크 단계의 ViewController를 lazy하게 생성하도록 리팩토링
- TextPopupViewController Factory에 기본 파라미터 지정

🔀 :: (#1139) 회원탈퇴 버튼에서 '여기' 텍스트 이외에도 탈퇴 동작이 이루어짐

---

Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailReactor.swift
Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailViewController.swift

- 노래 상세에서 좋아요를 할 때 내부 로직을 고도화했어요.
Resolves: #950 
- 노래 상세에서 좋아요를 할 때 내부 로직을 고도화했어요.
요청이 닿기 전에 다른 좋아요 요청이 왔을 떄의 처리를 했어요.
- 좋아요 요청을 보내고, 요청이 끝나면 마지막으로 온 요청의 좋아요 여부를 확인해 마지막의 요청이 끝난 좋아요와 다르다면 새로운 요청, 만약 같다면 요청 안보냄
- 좋아요 요청을 보내고 요청이 끝나기 전에 다른 음악의 좋아요를 한다면 다른 음악의 좋아요 로직을 먼저 처리함 (현재 화면에 보여지는 노래의 좋아요를 먼저 처리함)
시나리오
1. 좋아요 클릭
좋아요 요청
2. 좋아요 클릭 -> 좋아요 클릭
좋아요 요청 -> 좋아요 취소 요청 (좋아요 요청 완료 이후)
3. 좋아요 클릭 -> 좋아요 클릭 -> 좋아요 클릭
좋아요 요청 (취소 요청 보내지 않음)
4. A노래 좋아요 클릭 -> B노래로 이동 -> B노래 좋아요 클릭
A노래 좋아요 요청 -> B노래 좋아요 요청
5. A노래 좋아요 클릭 -> A노래 좋아요 취소 클릭 -> B노래로 이동 -> B노래 좋아요 클릭
- (A노래 좋아요 요청이 끝나지 않은 상태에서 좋아요 취소 클릭과 B노래 좋아요를 클릭했을 때)
A노래 좋아요 요청 -> B노래 좋아요 요청 -> A노래 좋아요 취소 요청
- (A노래 좋아요 요청이 끝난 상태에서 좋아요 취소 클릭 후 B노래 좋아요를 클릭했을 때)
A노래 좋아요 요청 -> A노래 좋아요 취소 요청->  B노래 좋아요 요청
6. A노래 좋아요 클릭 -> A노래 좋아요 클릭 -> B노래로 이동 -> B노래 좋아요 클릭 -> …

🔀 :: (#950) 좋아요 로직 고도화

---

Projects/Features/BaseFeature/Sources/Analytics/ContainSongsAnalyticsLog.swift
Projects/Features/BaseFeature/Sources/ViewControllers/ContainSongsViewController.swift
Projects/Features/StorageFeature/Sources/Analytics/StorageAnalyticsLog.swift
Projects/Features/StorageFeature/Sources/ViewControllers/LikeStorageViewController.swift
Projects/Features/StorageFeature/Sources/ViewControllers/ListStorageViewController.swift
Projects/Features/StorageFeature/Sources/ViewControllers/StorageViewController.swift
Projects/Features/StorageFeature/Sources/Views/ListStorageTableViewCell.swift
Projects/Modules/LogManager/Sources/CommonAnalyticsLog.swift

보관함 탭 로그를 추가했어요
Resolves: #1150 
- 보관함 화면 보여짐 (내리스트, 좋아요)✅
- 내 리스트 탭 클릭함 ✅
- 좋아요 탭 클릭함 ✅
- 내 리스트 - 리스트 만들기 클릭함 ✅
- 내 리스트 - 리스트 클릭함 (id) ✅
- 내 리스트 - 플레이버튼 클릭함 (id) ✅
- 내 리스트 - 편집 버튼 클릭함 ✅
- 내 리스트 - 열매 뽑기 버튼 클릭함 ✅
- 내 리스트 - 로그인 버튼 클릭함 ✅
- 좋아요 탭 - 곡 클릭함 (id) ✅
- 좋아요 탭 - 플레이버튼 클릭함 (id) ✅
- 좋아요 탭 - 편집 버튼 클릭함 ✅
- 좋아요 탭 - 로그인 버튼 클릭함 ✅

🔀 :: [#1150] 보관함 탭 로그 추가

---

Projects/Features/SearchFeature/Sources/After/Reactors/ListSearchResultReactor.swift
Projects/Features/SearchFeature/Sources/After/Reactors/SongSearchResultReactor.swift
Projects/Features/SearchFeature/Sources/After/ViewControllers/ListSearchResultViewController.swift
Projects/Features/SearchFeature/Sources/After/ViewControllers/SongSearchResultViewController.swift
Projects/Features/SearchFeature/Sources/Before/ViewControllers/BeforeSearchContentViewController.swift

검색 결과가 append되면서 같은 id를 갖는 데이터들이 중복되는 버그가 있습니다.
Resolves: #1148
Resolves: #1163 
scrollPage가 1일 때는 비어있는 배열로 데이터를 처리했습니다.

🔀 :: (#1148) 검색 결과 로딩 중  필터나 정렬을 누를 때 앱이 터지는 버그

---

Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistViewController+Delegate.swift
Projects/Features/PlaylistFeature/Sources/Views/RandomPlayButtonHeaderView.swift

- 재생목록화면 재생버튼 UI 변경
- 아티스트나 크레딧 작업자 노래 리스트 페이지에서 사용된 버튼과 동일하게 변경
Resolves: #1186
- 재생목록화면 재생버튼 UI 변경
- - 아티스트나 크레딧 작업자 노래 리스트 페이지에서 사용된 버튼과 동일하게 변경

🔀 :: (#1186) 재생목록화면 재생버튼 UI 변경

---

Projects/Modules/LogManager/Sources/AnalyticsLogManager.swift
Projects/Modules/Utility/Sources/Extensions/Extension+PreferenceManager.swift

- Firebase에 원격으로 에러를 남길 수 있음
Resolves: #1167
- Firebase에 원격으로 에러를 남길 수 있음

🔀 :: (#1167) Firebase Send Error

---

Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
Projects/UsertInterfaces/DesignSystem/Sources/WMNavigationBarView.swift

- 로딩 인디케이터 위치가 안맞음
Resolves: #1193 
- 센터정렬

🔀 :: (#1193) 플리 이미지 변경 시 로딩 인디케이터 센터 정렬

---

Projects/Features/MainTabFeature/Sources/ViewControllers/MainContainerViewController.swift
Projects/Features/MainTabFeature/Sources/ViewControllers/MainTabBarViewController.swift
Projects/Features/StorageFeature/Sources/ViewControllers/ListStorageViewController.swift
Projects/Features/StorageFeature/Sources/ViewControllers/StorageViewController.swift
Projects/Modules/Utility/Sources/Enums/PlaylistFloatingButtonPosition.swift
Projects/Modules/Utility/Sources/Extensions/Extension+Notification.Name.swift

- 플로팅 버튼 위치가 안맞음 
Resolves: #1199
- 플로팅 버튼 위치 조정
- 최대한 코드를 적게 작성하려 했으나, 이게 최선으로 결론 지음.

🔀 :: (#1199) 보관함 > 내 플리 상세 진입 시 플로팅 버튼 위치 안맞는 UI 오류 수정

---

Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricHighlightingViewController+Bind.swift
Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricHighlightingViewController.swift
Projects/Features/LyricHighlightingFeature/Sources/ViewModels/LyricHighlightingViewModel.swift

- 가사 하이라이팅 활성화 UI 추가
Resolves: #1210 
- 활성화 UI 추가
x

🔀:: (#1210) 가사 하이라이팅 활성화 UI 추가

---

Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/UnknownPlaylistDetailViewController.swift

구독 버튼 보여지는 시기가 ux상 맞지 않아 수정합니다.
https://discord.com/channels/1269673735380537404/1276982247412727862
Resolves: #1221
isHidden 시점을 tableview와 같게 맞춰줍니다.

🔀 :: (#1221) 구독 버튼 보여지는 시기 변경

---

Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
Projects/Features/ChartFeature/Sources/ViewContrillers/ChartContentViewController.swift
Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabItemReactor.swift
Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
Projects/Features/MainTabFeature/Sources/ViewControllers/MainTabBarViewController.swift
Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailViewController.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/UnknownPlaylistDetailViewController.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/WakmusicPlaylistDetailViewController.swift
Projects/Features/SearchFeature/Sources/After/ViewControllers/SongSearchResultViewController.swift
Projects/Features/StorageFeature/Sources/ViewControllers/LikeStorageViewController.swift

노래 상세에 진입 시 진입점 구분 없이 노래 상세의 데이터를 사용하도록 변경
Resolves: #1227 
노래 상세에 진입 시 진입점 구분 없이 노래 상세의 데이터를 사용하도록 변경
혹시나 단일 노래를 보여줘야하는 상황이 생기거나 할 수도 있을거라 생각해서 일단 id, ids 파라미터는 남기고 직접 재생목록 데이터를 보내주는 식으로 바꿔놓았어요.
혹은 songDetailPresenter.present() 이렇게 id없이보내면 재생목록 데이터를 자동으로 사용하게 할 수도 있겠네요

🔀 :: (#1227) 노래 상세에 진입 시 진입점 구분 없이 노래 상세의 데이터를 사용하도록 변경

---

Projects/App/Sources/Application/AppDelegate.swift
Projects/Features/MyInfoFeature/Sources/Analytics/SettingAnalyticsLog.swift
Projects/Features/MyInfoFeature/Sources/Reactors/SettingReactor.swift
Projects/Features/MyInfoFeature/Sources/ViewControllers/PlayTypeTogglePopup/PlayTypeTogglePopupViewController.swift
Projects/Features/MyInfoFeature/Sources/ViewControllers/Setting/SettingViewController.swift
Projects/Features/MyInfoFeature/Sources/Views/SettingItemTableViewCell.swift
Projects/Modules/LogManager/Sources/AnalyticsUserProperty.swift
Projects/Modules/Utility/Sources/Manager/PreferenceManager.swift
Projects/Modules/Utility/Sources/Player/WakmusicYoutubePlayer.swift

신규 기능이 추가됨에 따라 신규 로그를 추가했어요.
Resolves: #1237 
신규 기능이 추가됨에 따라 신규 로그를 추가했어요.
- song_play_platform UserProperty 정의
- click song play platform Event 정의
- complete song play platform Event 정의

🔀 :: (#1237) 신규 로그 추가

---

Projects/Features/MyInfoFeature/Sources/ViewControllers/PlayTypeTogglePopup/PlayTypeTogglePopupViewController.swift
Projects/Features/MyInfoFeature/Sources/ViewControllers/Setting/SettingViewController.swift

음악 재생 타입 Animation Spec 변경
Resolves: #1238 
음악 재생 타입 Animation Spec 변경
노출 애니메이션 - 0.3초, curveEaseInOut, 80만큼 아래에서부터 표시 시작, Opacity 0 -> 1
탈출 애니메이션 - 애니메이션 X
https://github.com/user-attachments/assets/4570f8c4-08ae-4277-92af-27cfb1cff3de

🔀 :: (#1238) 음악 재생 타입 팝업 Animation Spec 변경

---

Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/WakmusicPlaylistDetailViewController.swift
Projects/Modules/Utility/Sources/Player/WakmusicYoutubePlayer.swift
Projects/Modules/Utility/Sources/Youtube/YoutubeURLGenerator.swift

유튜브 뮤직 플레이리스트 재생 지원
Resolves: #1205
유튜브 뮤직 플레이리스트 재생 지원

🔀 :: (#1205) 유튜브 뮤직 플레이리스트 재생 지원

---

Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailReactor.swift
Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailViewController.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistViewController+Delegate.swift
Projects/Features/PlaylistFeature/Sources/Views/PlaylistTableViewCell.swift
Projects/Features/SearchFeature/Sources/Before/ViewControllers/BeforeSearchContentViewController.swift
Projects/Features/StorageFeature/Sources/Reactors/LikeStorageReactor.swift
Projects/Modules/Utility/Sources/Extensions/Extension+String.swift
Projects/Modules/Utility/Sources/Player/WakmusicYoutubePlayer.swift

단일곡 재생 시 제목에 Shorts를 의미하는 텍스트가 포함되어있을 시Youtube로 재생
Resolves: #1248
단일곡 재생 시 제목에 Shorts를 의미하는 텍스트가 포함되어있을 시Youtube로 재생

🔀 :: (#1248) 단일곡 재생 시 제목에 Shorts를 의미하는 텍스트가 포함되어있을 시Youtube로 재생

---

Projects/Features/BaseFeature/Sources/GlobalState/PlayListPresenterGlobalState.swift
Projects/Features/MainTabFeature/Sources/ViewControllers/MainContainerViewController.swift
Projects/Features/MusicDetailFeature/Demo/Sources/AppDelegate.swift
Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailReactor.swift
Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailViewController.swift
Projects/Features/PlaylistFeature/Interface/PlaylistFactory.swift
Projects/Features/PlaylistFeature/Sources/Components/PlaylistComponent.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistViewController.swift

노래 상세에서 재생목록 접근 시 재생목록 자동 스크롤
Resolves: #1230
노래 상세에서 재생목록 접근 시 재생목록 자동 스크롤
- 스크롤되는 애니메이션을 넣을까요? 너무 그냥 훅 바뀌는 느낌이라 안넣었는데
<details>
https://github.com/user-attachments/assets/8bd32247-20f8-4f28-a114-8c733cf8dab8
</details>
https://github.com/user-attachments/assets/b71d5ecc-3bba-47ff-b495-4414cfe614e5

🔀 :: (#1230) 노래 상세에서 재생목록 접근 시 재생목록 자동 스크롤

---

Projects/Features/BaseFeature/Resources/Base.storyboard
Projects/Features/BaseFeature/Sources/ViewControllers/ContainSongsViewController.swift
Projects/Features/BaseFeature/Sources/Views/ContainPlaylistHeaderView.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistViewController.swift
Projects/Features/PlaylistFeature/Sources/ViewModels/PlaylistViewModel.swift

디자인 수정에 대한 반영
Resolves: #1252
- blur 효과 적용
-border color opacitiy 변경
- talbeview header 및 section header 적용

🔀 :: (#1252) 곡 담기 blur 처리 

---

Projects/Features/BaseFeature/Sources/ViewControllers/ContractViewController.swift

- 이용약관, 개인정보 처리방침 로드실패에 대한 처리
Resolves: #1244 
- pdf파일 URL이 변경되는건지 뭔지 몰라서 그냥 둠 
- 일부러 안 보여줄 필요까지는 없다고 봐요. 변경되면 URL바꾸고 아니면 놔두면 됩니다.
x

🔀 :: (#1244) PDF 로드 실패 처리

---

Projects/Features/ArtistFeature/Resources/Artist.storyboard
Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistDetailHeaderViewController.swift
Projects/UsertInterfaces/DesignSystem/Sources/Extension+UILabel.swift

- 아티스트 설명글이 짤림
Resolves: #1259
- 텍스트 간격 피그마와 최대한 일치 (설명 글 하단 간격이 쓸데없이 크게 잡혀있었음)
- 설명글은 한글 텍스트 라인브레이크 적용
- UILabel 특성상 다각형 레이아웃을 구성할 수 없어 김치만두, 데스해머쵸로키 같은 레이아웃은 구성할 수가 없음.
- '우왁굳' 이름 폰트 크기가 맞지않는 것도 옆에 영문 이름이 따라붙어야 하는(줄바꿈 조건 포함) 공통의 조건을 만족시키기 위함.

🔀 :: (#1259) 아티스트 설명글 짤림 보완

---

Projects/Modules/Utility/Sources/Extensions/Extension+UIViewController.swift

- deprecated 레거시 제거
Resolves: #1208 
-  deprecated 토스트 함수 제거
x

🔀 :: (#1208) deprecated 토스트 함수 제거

---

Projects/App/Sources/Application/AppDelegate.swift
Projects/Features/ArtistFeature/Resources/Artist.storyboard
Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistViewController.swift

- 이스터에그 제거 
Resolves: #1264 
- 이스터에그 제거 
- 푸시 수신관련 레거시 함수 제거
x

🔀 :: (#1264) 푸시발송 이스터에그 제거 

---

Projects/Features/MyInfoFeature/Sources/Views/PlayTypeTogglePopupItemButton.swift

디자인 요구사항 변경에 따라 터치 영역을 확장합니다.
Resolves: #1243
- 미설치 버튼 뷰 분리
| 화면 | 하이어라키 |
|--------|--------|
| ![simulator_screenshot_8E01ACE1-E3AD-4C6E-8691-5FA607F3F096](https://github.com/user-attachments/assets/fca59f83-01e1-4e41-a6e5-d8db1aff43ec) | <img width="100%" alt="image" src="https://github.com/user-attachments/assets/131206eb-b0d3-423a-b6b0-dc6901115821"> | 
지금보니 디자인이 많이 바뀌었네요.. 다음 PR에서 이어집니다 😄

🔀 :: (#1243) fix 미설치 버튼 터치 영역 확장

---

Projects/Features/StorageFeature/Sources/ViewControllers/ListStorageViewController.swift
Projects/Features/StorageFeature/Sources/Views/CreateListButton.swift
Projects/Features/StorageFeature/Sources/Views/ListStorageView.swift

Resolves: #1262
- 테이블 뷰 헤더로 변경

🔀 :: (#1262) 보관함 리스트 만들기 버튼 UI 수정

---

Projects/Features/BaseFeature/Resources/Base.storyboard
Projects/Features/BaseFeature/Sources/ViewControllers/MultiPurposePopupViewController.swift

- 닉네임, 플리 이름 입력시 마지막 글자에서 한글 자모 조합이 되지 않는 문제 발생
Resolves: #1258 
- 현재 작성한 조건(백스페이스, 글자수 제한)에서 입력한 '마지막' 글자가 완성된 한글이 아니거나, 추가로 자음이 결합될 수 있는 조건을 추가
- 이런 조건을 추가했을때, 마지막 글자가 ex: '일' 이라면 추가로 받침이 더 올 수 있으므로 글자 수 제한을 넘어 계속 입력이 가능합니다. 하지만 빨간 경고 UI를 띄워 보여주고 있으므로 괜찮을듯 함.

🔀 :: (#1258) 닉네임 입력 조건 추가

---

Projects/Features/StorageFeature/Sources/ViewControllers/ListStorageViewController.swift
Projects/Features/StorageFeature/Sources/Views/ListStorageView.swift
Projects/Features/StorageFeature/Sources/Views/ParticleAnimationView.swift

- 뷰가 나타날때 애니메이션 초기화 과정이 눈에 보여서 어색함
Resolves: #974 
- 뷰가 나타난 후 애니메이션을 시작하고, 뷰가 사라진 후 애니메이션을 초기화 시킴
- 영상있는데 용량커서 안올라감...

🔀 :: (#974) (보관함 > 내 리스트) 애니메이션 초기화 과정 안보이게 수정

---

Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
Projects/Features/ChartFeature/Sources/ViewContrillers/ChartContentViewController.swift
Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabItemReactor.swift
Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabItemViewController.swift
Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistViewController+Delegate.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/UnknownPlaylistDetailViewController.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/WakmusicPlaylistDetailViewController.swift
Projects/Features/SearchFeature/Sources/After/ViewControllers/SongSearchResultViewController.swift
Projects/Features/SearchFeature/Sources/Before/ViewControllers/BeforeSearchContentViewController.swift
Projects/Features/StorageFeature/Sources/Reactors/ListStorageReactor.swift

쇼츠로만 구성하여 재생 시 항상 유튜브로만 재생
Resolves: #1283
쇼츠로만 구성하여 재생 시 항상 유튜브로만 재생
음 뭔가가 뭔가네요
괜히 분기친건가 싶기도하고 분기쳐놨으면 재생 타입 설정할때 말 더 해놔야하나 싶기도하고 🤔 이네요

🔀 :: (#1283) 쇼츠로만 구성하여 재생 시 항상 유튜브로만 재생

---

Projects/Features/SongCreditFeature/Sources/SongCreditViewController.swift

- 신곡의 경우 크레딧 정보가 없는 상태가 있음
Resolves: #1285 
- 빈 데이터 UI 처리
x

🔀 :: (#1285) 참여정보(크레딧) > 데이터 없을 때 UI 처리

---

Projects/App/Support/Info.plist
Projects/Features/BaseFeature/Sources/ViewControllers/ContractViewController.swift
Projects/Modules/Utility/Sources/Utils/Secrets.swift

- 개인정보 처리방침, 서비스 이용약관 pdf 로드 주소가 변경 됨
Resolves: #1287 
- CDN 도메인 Secrets.xcconfig에 추가 (노션 업데이트)
- 미사용 도메인 경로 Secrets.xcconfig에서 제거 (노션 업데이트)
- privacy, terms 주소 변경
x

🔀 :: (#1287) privacy, terms 주소 변경

---

Projects/Features/ArtistFeature/Resources/Artist.storyboard
Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistDetailHeaderViewController.swift

- 터치영역 변경
Resolves: #1291 
- 터치영역 변경
x

🔀 :: (#1291) 아티스트 소개글 터치영역 변경

---

Projects/Features/MyInfoFeature/Sources/ViewControllers/MyInfo/MyInfoViewController.swift
Projects/Features/MyInfoFeature/Sources/Views/FruitDrawButtonView.swift
Projects/Features/MyInfoFeature/Sources/Views/MyInfoView.swift

기능 누락
Resolves: #1289
- 열매함 바로가기 투명 버튼 추가

🔀  ::  (#1289) 누락된 열매함 바로가기 기능 추가

---

Projects/Domains/UserDomain/Sources/API/UserAPI.swift
Projects/Features/BaseFeature/Sources/ViewControllers/MultiPurposePopupViewController.swift
Projects/Features/MyInfoFeature/Sources/Reactors/MyInfoReactor.swift

- 키워드, 중복 닉네임에 대한 처리 미흡
Resolves: #1293 
- '자' 텍스트 추가된 UI 수정: (n자/12 > n자/12자)
- 409 conflict 에러 캐치
- 이제 develop으로 머지

🔀 :: (#1293) 중복 닉네임 에러 캐치 등

---

Projects/Features/PlaylistFeature/Sources/Reactors/MyPlaylistDetailReactor.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistViewController+Delegate.swift
Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistViewController.swift
Projects/Features/PlaylistFeature/Sources/ViewModels/PlaylistViewModel.swift
Projects/Features/StorageFeature/Sources/Reactors/LikeStorageReactor.swift
Projects/Features/StorageFeature/Sources/Reactors/ListStorageReactor.swift
Projects/Features/StorageFeature/Sources/ViewControllers/LikeStorageViewController.swift
Projects/Features/StorageFeature/Sources/ViewControllers/ListStorageViewController.swift

Long Press 진입점의 UX가 비정상적인 이슈 해결
https://github.com/user-attachments/assets/ba7b3c4d-14db-439f-953d-bc0bd11c285b
https://github.com/user-attachments/assets/b187264e-b26e-4974-b670-555d93034e04
Resolves: #1309 
Long Press 진입점의 UX가 비정상적인 이슈 해결

🔀 :: [#1309] Long Press 진입점의 UX가 비정상적인 이슈

---

Projects/App/Sources/Application/AppComponent+Artist.swift
Projects/Domains/ArtistDomain/Interface/DataSource/RemoteArtistDataSource.swift
Projects/Domains/ArtistDomain/Interface/Repository/ArtistRepository.swift
Projects/Domains/ArtistDomain/Interface/UseCase/FindArtistIDUseCase.swift
Projects/Domains/ArtistDomain/Sources/API/ArtistAPI.swift
Projects/Domains/ArtistDomain/Sources/DataSource/RemoteArtistDataSourceImpl.swift
Projects/Domains/ArtistDomain/Sources/Repository/ArtistRepositoryImpl.swift
Projects/Domains/ArtistDomain/Sources/ResponseDTO/FindArtistIDResponseDTO.swift
Projects/Domains/ArtistDomain/Sources/UseCase/FindArtistIDUseCaseImpl.swift
Projects/Domains/ArtistDomain/Testing/UseCase/FindArtistIDUseCaseSpy.swift
Projects/Features/MusicDetailFeature/Demo/Sources/AppDelegate.swift
Projects/Features/MusicDetailFeature/Project.swift
Projects/Features/MusicDetailFeature/Sources/MusicDetail/Component/MusicDetailComponent.swift
Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailReactor.swift
Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailView.swift
Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailViewController.swift
Projects/Features/MusicDetailFeature/Sources/MusicDetail/Views/MusicControlView/MusicControlView.swift
Projects/Modules/Utility/Sources/Utils/UniquedSequence.swift

음악 상세에서 아티스트 이름 클릭 시 크레딧 혹은 아티스트 상세로 이동
Resolves: #1316
음악 상세에서 아티스트 이름 클릭 시 크레딧 혹은 아티스트 상세로 이동

🔀 :: (#1316) 음악 상세에서 아티스트 이름 클릭 시 크레딧 혹은 아티스트 상세로 이동

---

Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift

마이 플리 재생 시 플리 제목이 '왁타버스 뮤직'으로 노출됨
Resolves: #1323
마이 플리 재생 시 플리 제목이 '왁타버스 뮤직'으로 노출되는 이슈 해결

🔀 :: (#1323) 마이 플리 재생 시 플리 제목이 '왁타버스 뮤직'으로 노출됨
